; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra-unknown-none -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; 64-bit (and wider) add/sub lower to the hardware carry chain: the low half
; sets SR.C and the high half consumes it via ADC/SBC, with no branch, no
; compare, and no stack frame.

define i64 @add_i64(i64 %a, i64 %b) {
; CHECK-LABEL: add_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    add r1, r3
; CHECK-NEXT:    adc r2, r4
; CHECK-NEXT:    jmp lr
  %r = add i64 %a, %b
  ret i64 %r
}

define i64 @sub_i64(i64 %a, i64 %b) {
; CHECK-LABEL: sub_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub r1, r3
; CHECK-NEXT:    sbc r2, r4
; CHECK-NEXT:    jmp lr
  %r = sub i64 %a, %b
  ret i64 %r
}

; i128 extends the chain: one ADD then a run of ADC.  Result returned through a
; pointer (the i128-by-value return ABI is a separate, unrelated gap).
define void @add_i128(ptr %p, i128 %a, i128 %b) {
; CHECK-LABEL: add_i128:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 16
; CHECK-NEXT:    stw r5, [sp + 12] // 4-byte Folded Spill
; CHECK-NEXT:    stw r6, [sp + 8] // 4-byte Folded Spill
; CHECK-NEXT:    stw r7, [sp + 4] // 4-byte Folded Spill
; CHECK-NEXT:    stw r8, [sp + 0] // 4-byte Folded Spill
; CHECK-NEXT:    ldw r11, [sp + 16]
; CHECK-NEXT:    ldw r5, [sp + 20]
; CHECK-NEXT:    ldw r6, [sp + 24]
; CHECK-NEXT:    ldw r7, [sp + 28]
; CHECK-NEXT:    ldw r8, [sp + 32]
; CHECK-NEXT:    add r2, r5
; CHECK-NEXT:    adc r3, r6
; CHECK-NEXT:    adc r4, r7
; CHECK-NEXT:    adc r11, r8
; CHECK-NEXT:    stw r2, [r1 + 0]
; CHECK-NEXT:    stw r3, [r1 + 4]
; CHECK-NEXT:    stw r4, [r1 + 8]
; CHECK-NEXT:    stw r11, [r1 + 12]
; CHECK-NEXT:    ldw r8, [sp + 0] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r7, [sp + 4] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r6, [sp + 8] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r5, [sp + 12] // 4-byte Folded Reload
; CHECK-NEXT:    add sp, 16
; CHECK-NEXT:    jmp lr
  %r = add i128 %a, %b
  store i128 %r, ptr %p
  ret void
}
