; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; Backend half of the slot-based aggregate convention (doc/system/abi.md
; "Argument Passing" / "Return Values").  The frontend coercion is pinned by
; clang/test/CodeGen/Penumbra/aggregate-abi.c; here we check that the backend
; places the coerced forms in the right registers: a two-slot [2 x i32]
; aggregate occupies R1:R2, an over-8-byte return uses the sret pointer in R1,
; and an over-8-byte argument is a plain pointer in a register.

%struct.S16 = type { i32, i32, i32, i32 }

; A [2 x i32] argument arrives in R1:R2; the trailing pointer takes R3.
define void @take_pair([2 x i32] %s, ptr %out) {
; CHECK-LABEL: take_pair:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    stw r1, [r3 + 0]
; CHECK-NEXT:    stw r2, [r3 + 4]
; CHECK-NEXT:    jmp lr
  %lo = extractvalue [2 x i32] %s, 0
  %hi = extractvalue [2 x i32] %s, 1
  store i32 %lo, ptr %out
  %p1 = getelementptr i32, ptr %out, i32 1
  store i32 %hi, ptr %p1
  ret void
}

; A [2 x i32] return comes back in R1:R2.
define [2 x i32] @ret_pair(i32 %a, i32 %b) {
; CHECK-LABEL: ret_pair:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    jmp lr
  %agg0 = insertvalue [2 x i32] poison, i32 %a, 0
  %agg1 = insertvalue [2 x i32] %agg0, i32 %b, 1
  ret [2 x i32] %agg1
}

; An over-8-byte aggregate return writes through the caller's sret pointer (R1).
define void @ret_sret(ptr sret(%struct.S16) %agg) {
; CHECK-LABEL: ret_sret:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    lli r2, 1
; CHECK-NEXT:    stw r2, [r1 + 0]
; CHECK-NEXT:    jmp lr
  store i32 1, ptr %agg
  ret void
}

; The caller materializes the two slots into R1:R2 before the call.
define void @call_pair(ptr %out) {
; CHECK-LABEL: call_pair:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 4
; CHECK-NEXT:    stw lr, [sp + 0] // 4-byte Folded Spill
; CHECK-NEXT:    mov r3, r1
; CHECK-NEXT:    lli r1, 7
; CHECK-NEXT:    lli r2, 8
; CHECK-NEXT:    bl take_pair
; CHECK-NEXT:    ldw lr, [sp + 0] // 4-byte Folded Reload
; CHECK-NEXT:    add sp, 4
; CHECK-NEXT:    jmp lr
  call void @take_pair([2 x i32] [i32 7, i32 8], ptr %out)
  ret void
}
