; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; With a variable-sized stack object the call frame is not reserved:
; calls with stack arguments must open their own argument area below
; SP, or the argument store lands on a local or the alloca'd buffer.

declare i32 @g5(i32, i32, i32, i32, i32)
declare i32 @g4(i32, i32, i32, i32)
declare void @keep(ptr)

; Fifth argument goes on the stack: SP drops around the call.
define i32 @dyn_alloca_stack_args(i32 %n) {
; CHECK-LABEL: dyn_alloca_stack_args:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 16
; CHECK-NEXT:    stw r5, [sp + 12] // 4-byte Folded Spill
; CHECK-NEXT:    stw r6, [sp + 8] // 4-byte Folded Spill
; CHECK-NEXT:    stw r10, [sp + 4] // 4-byte Folded Spill
; CHECK-NEXT:    stw lr, [sp + 0] // 4-byte Folded Spill
; CHECK-NEXT:    mov r10, sp
; CHECK-NEXT:    add r1, 3
; CHECK-NEXT:    llis r2, -4
; CHECK-NEXT:    and r1, r2
; CHECK-NEXT:    mov r5, sp
; CHECK-NEXT:    sub r5, r1
; CHECK-NEXT:    mov sp, r5
; CHECK-NEXT:    sub sp, 4
; CHECK-NEXT:    mov r1, sp
; CHECK-NEXT:    lli r2, 77
; CHECK-NEXT:    stw r2, [r1 + 0]
; CHECK-NEXT:    lli r1, 1
; CHECK-NEXT:    lli r2, 2
; CHECK-NEXT:    lli r3, 3
; CHECK-NEXT:    lli r4, 4
; CHECK-NEXT:    bl g5
; CHECK-NEXT:    add sp, 4
; CHECK-NEXT:    mov r6, r1
; CHECK-NEXT:    mov r1, r5
; CHECK-NEXT:    bl keep
; CHECK-NEXT:    mov r1, r6
; CHECK-NEXT:    mov sp, r10
; CHECK-NEXT:    ldw r5, [sp + 12] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r6, [sp + 8] // 4-byte Folded Reload
; CHECK-NEXT:    ldw lr, [sp + 0] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r10, [sp + 4] // 4-byte Folded Reload
; CHECK-NEXT:    add sp, 16
; CHECK-NEXT:    jmp lr
  %buf = alloca i8, i32 %n
  %r = call i32 @g5(i32 1, i32 2, i32 3, i32 4, i32 77)
  call void @keep(ptr %buf)
  ret i32 %r
}

; Zero-byte call frame: no SP traffic between the alloca and the call.
define i32 @dyn_alloca_reg_args(i32 %n) {
; CHECK-LABEL: dyn_alloca_reg_args:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 16
; CHECK-NEXT:    stw r5, [sp + 12] // 4-byte Folded Spill
; CHECK-NEXT:    stw r6, [sp + 8] // 4-byte Folded Spill
; CHECK-NEXT:    stw r10, [sp + 4] // 4-byte Folded Spill
; CHECK-NEXT:    stw lr, [sp + 0] // 4-byte Folded Spill
; CHECK-NEXT:    mov r10, sp
; CHECK-NEXT:    add r1, 3
; CHECK-NEXT:    llis r2, -4
; CHECK-NEXT:    and r1, r2
; CHECK-NEXT:    mov r5, sp
; CHECK-NEXT:    sub r5, r1
; CHECK-NEXT:    mov sp, r5
; CHECK-NEXT:    lli r1, 1
; CHECK-NEXT:    lli r2, 2
; CHECK-NEXT:    lli r3, 3
; CHECK-NEXT:    lli r4, 4
; CHECK-NEXT:    bl g4
; CHECK-NEXT:    mov r6, r1
; CHECK-NEXT:    mov r1, r5
; CHECK-NEXT:    bl keep
; CHECK-NEXT:    mov r1, r6
; CHECK-NEXT:    mov sp, r10
; CHECK-NEXT:    ldw r5, [sp + 12] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r6, [sp + 8] // 4-byte Folded Reload
; CHECK-NEXT:    ldw lr, [sp + 0] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r10, [sp + 4] // 4-byte Folded Reload
; CHECK-NEXT:    add sp, 16
; CHECK-NEXT:    jmp lr
  %buf = alloca i8, i32 %n
  %r = call i32 @g4(i32 1, i32 2, i32 3, i32 4)
  call void @keep(ptr %buf)
  ret i32 %r
}

; No alloca: reserved call frame, no per-call SP adjustment.
define i32 @fixed_frame_stack_args() {
; CHECK-LABEL: fixed_frame_stack_args:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 8
; CHECK-NEXT:    stw lr, [sp + 4] // 4-byte Folded Spill
; CHECK-NEXT:    mov r1, sp
; CHECK-NEXT:    lli r2, 77
; CHECK-NEXT:    stw r2, [r1 + 0]
; CHECK-NEXT:    lli r1, 1
; CHECK-NEXT:    lli r2, 2
; CHECK-NEXT:    lli r3, 3
; CHECK-NEXT:    lli r4, 4
; CHECK-NEXT:    bl g5
; CHECK-NEXT:    ldw lr, [sp + 4] // 4-byte Folded Reload
; CHECK-NEXT:    add sp, 8
; CHECK-NEXT:    jmp lr
  %r = call i32 @g5(i32 1, i32 2, i32 3, i32 4, i32 77)
  ret i32 %r
}
