; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

define i32 @add_reg_reg(i32 %a, i32 %b) {
; CHECK-LABEL: add_reg_reg:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    add r1, r2
; CHECK-NEXT:    jmp lr
  %result = add i32 %a, %b
  ret i32 %result
}

define i32 @sub_reg_reg(i32 %a, i32 %b) {
; CHECK-LABEL: sub_reg_reg:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub r1, r2
; CHECK-NEXT:    jmp lr
  %result = sub i32 %a, %b
  ret i32 %result
}

define i32 @and_reg_reg(i32 %a, i32 %b) {
; CHECK-LABEL: and_reg_reg:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    and r1, r2
; CHECK-NEXT:    jmp lr
  %result = and i32 %a, %b
  ret i32 %result
}

define i32 @or_reg_reg(i32 %a, i32 %b) {
; CHECK-LABEL: or_reg_reg:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    or r1, r2
; CHECK-NEXT:    jmp lr
  %result = or i32 %a, %b
  ret i32 %result
}

define i32 @xor_reg_reg(i32 %a, i32 %b) {
; CHECK-LABEL: xor_reg_reg:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    xor r1, r2
; CHECK-NEXT:    jmp lr
  %result = xor i32 %a, %b
  ret i32 %result
}

define i32 @shl_reg_reg(i32 %a, i32 %b) {
; CHECK-LABEL: shl_reg_reg:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    shl r1, r2
; CHECK-NEXT:    jmp lr
  %result = shl i32 %a, %b
  ret i32 %result
}

define i32 @shr_reg_reg(i32 %a, i32 %b) {
; CHECK-LABEL: shr_reg_reg:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    shr r1, r2
; CHECK-NEXT:    jmp lr
  %result = lshr i32 %a, %b
  ret i32 %result
}

define i32 @sar_reg_reg(i32 %a, i32 %b) {
; CHECK-LABEL: sar_reg_reg:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sar r1, r2
; CHECK-NEXT:    jmp lr
  %result = ashr i32 %a, %b
  ret i32 %result
}

define i32 @shl_imm(i32 %a) {
; CHECK-LABEL: shl_imm:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    shl r1, 3
; CHECK-NEXT:    jmp lr
  %result = shl i32 %a, 3
  ret i32 %result
}

define i32 @shr_imm(i32 %a) {
; CHECK-LABEL: shr_imm:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    shr r1, 8
; CHECK-NEXT:    jmp lr
  %result = lshr i32 %a, 8
  ret i32 %result
}

define i32 @sar_imm(i32 %a) {
; CHECK-LABEL: sar_imm:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sar r1, 16
; CHECK-NEXT:    jmp lr
  %result = ashr i32 %a, 16
  ret i32 %result
}
