; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs -O1 < %s \
; RUN:   | FileCheck %s

; Test that branch analysis, insertion, removal, and reversal work correctly
; at -O1+ where branch optimization passes run.

; Simple if/else — optimizer should eliminate redundant branches.
define i32 @branch_simple(i32 %a, i32 %b, i32 %x, i32 %y) {
; CHECK-LABEL: branch_simple:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    cmp r1, r2
; CHECK-NEXT:    bne .LBB0_2
; CHECK-NEXT:  // %bb.1: // %if.then
; CHECK-NEXT:    mov r1, r3
; CHECK-NEXT:    jmp lr
; CHECK-NEXT:  .LBB0_2: // %if.else
; CHECK-NEXT:    mov r1, r4
; CHECK-NEXT:    jmp lr
  %cmp = icmp eq i32 %a, %b
  br i1 %cmp, label %if.then, label %if.else
if.then:
  ret i32 %x
if.else:
  ret i32 %y
}

; Diamond with common tail — branch folding should merge the tails.
define i32 @diamond_merge(i32 %a, i32 %b) {
; CHECK-LABEL: diamond_merge:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    cmp r1, 0
; CHECK-NEXT:    ble .LBB1_2
; CHECK-NEXT:  // %bb.1: // %pos
; CHECK-NEXT:    add r1, r2
; CHECK-NEXT:    jmp lr
; CHECK-NEXT:  .LBB1_2: // %neg
; CHECK-NEXT:    sub r1, r2
; CHECK-NEXT:    jmp lr
  %cmp = icmp sgt i32 %a, 0
  br i1 %cmp, label %pos, label %neg
pos:
  %sum = add i32 %a, %b
  br label %done
neg:
  %diff = sub i32 %a, %b
  br label %done
done:
  %result = phi i32 [%sum, %pos], [%diff, %neg]
  ret i32 %result
}

; Loop with condition — tests analyzeBranch on loop backedges.
define i32 @loop_sum(i32 %n) {
; CHECK-LABEL: loop_sum:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mov r2, r1
; CHECK-NEXT:    mov r1, zero
; CHECK-NEXT:    mov r3, r1
; CHECK-NEXT:  .LBB2_1: // %loop
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    add r1, r3
; CHECK-NEXT:    add r3, 1
; CHECK-NEXT:    cmp r3, r2
; CHECK-NEXT:    blt .LBB2_1
; CHECK-NEXT:  // %bb.2: // %exit
; CHECK-NEXT:    jmp lr
entry:
  br label %loop
loop:
  %i = phi i32 [0, %entry], [%next, %loop]
  %sum = phi i32 [0, %entry], [%newsum, %loop]
  %newsum = add i32 %sum, %i
  %next = add i32 %i, 1
  %cmp = icmp slt i32 %next, %n
  br i1 %cmp, label %loop, label %exit
exit:
  ret i32 %newsum
}

; Branch reversal — condition inverted so true block is fallthrough.
define i32 @branch_reversal(i32 %a) {
; CHECK-LABEL: branch_reversal:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    cmp r1, 0
; CHECK-NEXT:    bne .LBB3_1
; CHECK-NEXT:  // %bb.2: // %is_zero
; CHECK-NEXT:    lli r1, 42
; CHECK-NEXT:    jmp lr
; CHECK-NEXT:  .LBB3_1: // %not_zero
; CHECK-NEXT:    add r1, 1
; CHECK-NEXT:    jmp lr
  %cmp = icmp eq i32 %a, 0
  br i1 %cmp, label %is_zero, label %not_zero
not_zero:
  %inc = add i32 %a, 1
  ret i32 %inc
is_zero:
  ret i32 42
}

; Multiple conditions — tests two-way branch analysis.
define i32 @multi_cond(i32 %a, i32 %b) {
; CHECK-LABEL: multi_cond:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    cmp r1, r2
; CHECK-NEXT:    bge .LBB4_1
; CHECK-NEXT:  // %bb.3: // %lt
; CHECK-NEXT:    llis r1, -1
; CHECK-NEXT:    jmp lr
; CHECK-NEXT:  .LBB4_1: // %ge
; CHECK-NEXT:    cmp r1, r2
; CHECK-NEXT:    bne .LBB4_2
; CHECK-NEXT:  // %bb.4: // %eq
; CHECK-NEXT:    mov r1, zero
; CHECK-NEXT:    jmp lr
; CHECK-NEXT:  .LBB4_2: // %gt
; CHECK-NEXT:    lli r1, 1
; CHECK-NEXT:    jmp lr
  %c1 = icmp slt i32 %a, %b
  br i1 %c1, label %lt, label %ge
lt:
  ret i32 -1
ge:
  %c2 = icmp eq i32 %a, %b
  br i1 %c2, label %eq, label %gt
eq:
  ret i32 0
gt:
  ret i32 1
}

; Unsigned comparison — tests BHI/BLS branch reversal.
define i32 @unsigned_cmp(i32 %a, i32 %b) {
; CHECK-LABEL: unsigned_cmp:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    cmp r1, r2
; CHECK-NEXT:    bls .LBB5_2
; CHECK-NEXT:  // %bb.1: // %high
; CHECK-NEXT:    lli r1, 1
; CHECK-NEXT:    jmp lr
; CHECK-NEXT:  .LBB5_2: // %low
; CHECK-NEXT:    mov r1, zero
; CHECK-NEXT:    jmp lr
  %cmp = icmp ugt i32 %a, %b
  br i1 %cmp, label %high, label %low
high:
  ret i32 1
low:
  ret i32 0
}
