; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; Test sub-word G_BSWAP legalization (widens to s32, then lowers).

declare i16 @llvm.bswap.i16(i16)

define i16 @bswap16(i16 %x) {
; CHECK-LABEL: bswap16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r3, r1
; CHECK-NEXT:    shl r3, 24
; CHECK-NEXT:    mov r2, r1
; CHECK-NEXT:    shr r2, 24
; CHECK-NEXT:    or r2, r3
; CHECK-NEXT:    mov r3, r1
; CHECK-NEXT:    and r3, 65280
; CHECK-NEXT:    shl r3, 8
; CHECK-NEXT:    or r2, r3
; CHECK-NEXT:    shr r1, 8
; CHECK-NEXT:    and r1, 65280
; CHECK-NEXT:    or r2, r1
; CHECK-NEXT:    shr r2, 16
; CHECK-NEXT:    mov r1, r2
; CHECK-NEXT:    jmp lr
  %r = call i16 @llvm.bswap.i16(i16 %x)
  ret i16 %r
}
