; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; Test s64 G_BSWAP.  Penumbra narrows s64 -> two s32 bswaps and
; merges the halves in reverse, matching the RISC-V 32-bit pattern.
; Directly lowering at s64 (`.lowerFor({s64})`) would trip an
; upstream UB in LegalizerHelper::lowerBswap: its per-byte mask
; for i=3 uses `APInt(64, 0xFF << 24)`, but `0xFF << 24` overflows
; signed int and sign-extends to 0xFFFFFFFFFF000000 when widened
; to uint64_t, corrupting the i64 mask and producing stray
; high-byte OR terms in the result.

declare i64 @llvm.bswap.i64(i64)

define i64 @bswap_i64(i64 %x) {
; CHECK-LABEL: bswap_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r4, r2
; CHECK-NEXT:    shl r4, 24
; CHECK-NEXT:    mov r3, r2
; CHECK-NEXT:    shr r3, 24
; CHECK-NEXT:    or r3, r4
; CHECK-NEXT:    mov r4, r2
; CHECK-NEXT:    and r4, 65280
; CHECK-NEXT:    shl r4, 8
; CHECK-NEXT:    or r3, r4
; CHECK-NEXT:    shr r2, 8
; CHECK-NEXT:    and r2, 65280
; CHECK-NEXT:    or r3, r2
; CHECK-NEXT:    mov r4, r1
; CHECK-NEXT:    shl r4, 24
; CHECK-NEXT:    mov r2, r1
; CHECK-NEXT:    shr r2, 24
; CHECK-NEXT:    or r2, r4
; CHECK-NEXT:    mov r4, r1
; CHECK-NEXT:    and r4, 65280
; CHECK-NEXT:    shl r4, 8
; CHECK-NEXT:    or r2, r4
; CHECK-NEXT:    shr r1, 8
; CHECK-NEXT:    and r1, 65280
; CHECK-NEXT:    or r2, r1
; CHECK-NEXT:    mov r1, r3
; CHECK-NEXT:    jmp lr
  %r = call i64 @llvm.bswap.i64(i64 %x)
  ret i64 %r
}
