; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

declare i32 @extern_func(i32, i32)

define i32 @call_two_args(i32 %a, i32 %b) {
; CHECK-LABEL: call_two_args:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 4
; CHECK-NEXT:    stw lr, [sp + 0] // 4-byte Folded Spill
; CHECK-NEXT:    bl extern_func
; CHECK-NEXT:    ldw lr, [sp + 0] // 4-byte Folded Reload
; CHECK-NEXT:    add sp, 4
; CHECK-NEXT:    jmp lr
  %result = call i32 @extern_func(i32 %a, i32 %b)
  ret i32 %result
}

define i32 @call_four_args(i32 %a, i32 %b, i32 %c, i32 %d) {
; CHECK-LABEL: call_four_args:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 4
; CHECK-NEXT:    stw lr, [sp + 0] // 4-byte Folded Spill
; CHECK-NEXT:    mov r1, r3
; CHECK-NEXT:    mov r2, r4
; CHECK-NEXT:    bl extern_func
; CHECK-NEXT:    ldw lr, [sp + 0] // 4-byte Folded Reload
; CHECK-NEXT:    add sp, 4
; CHECK-NEXT:    jmp lr
  %result = call i32 @extern_func(i32 %c, i32 %d)
  ret i32 %result
}

; Callee-saved register preservation
define i32 @callee_saved(i32 %a) {
; CHECK-LABEL: callee_saved:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 8
; CHECK-NEXT:    stw r5, [sp + 4] // 4-byte Folded Spill
; CHECK-NEXT:    stw lr, [sp + 0] // 4-byte Folded Spill
; CHECK-NEXT:    mov r5, r1
; CHECK-NEXT:    mov r2, r5
; CHECK-NEXT:    bl extern_func
; CHECK-NEXT:    mov r2, r5
; CHECK-NEXT:    bl extern_func
; CHECK-NEXT:    ldw lr, [sp + 0] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r5, [sp + 4] // 4-byte Folded Reload
; CHECK-NEXT:    add sp, 8
; CHECK-NEXT:    jmp lr
  %call1 = call i32 @extern_func(i32 %a, i32 %a)
  %call2 = call i32 @extern_func(i32 %call1, i32 %a)
  ret i32 %call2
}

; Simple leaf function (no calls)
define i32 @leaf_add(i32 %a, i32 %b) {
; CHECK-LABEL: leaf_add:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    add r1, r2
; CHECK-NEXT:    jmp lr
  %sum = add i32 %a, %b
  ret i32 %sum
}
