; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs -O2 < %s \
; RUN:   | FileCheck %s

; Compare-elimination peephole: a `CMPi Rx, 0` whose Z/N can be supplied by
; an earlier flag-setting ALU op that defines Rx is deleted, with the
; producer spliced down to immediately precede the (former) CMP so its
; flags reach the consuming Bcc.  See PenumbraInstrInfo.cpp.

;; Baseline: SUBi immediately before CMPi.  This is the simple case the
;; peephole has always handled — included as a regression guard.
define i32 @simple_decr_loop(i32 %n) {
; CHECK-LABEL: simple_decr_loop:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:  .LBB0_1: // %loop
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    sub r1, 1
; CHECK-NEXT:    bne .LBB0_1
; CHECK-NEXT:  // %bb.2: // %exit
; CHECK-NEXT:    mov r1, zero
; CHECK-NEXT:    jmp lr
entry:
  br label %loop
loop:
  %i = phi i32 [ %n, %entry ], [ %dec, %loop ]
  %dec = sub i32 %i, 1
  %c = icmp ne i32 %dec, 0
  br i1 %c, label %loop, label %exit
exit:
  ret i32 0
}

;; Memcpy-style: SUBi at the top of the loop is separated from the CMPi
;; at the bottom by intervening pointer-increment ADDis that clobber SR.
;; The peephole must walk back through those clobbers, find the SUBi
;; that defines the loop counter, splice it adjacent to the CMPi, and
;; erase the CMPi.  No `cmp` should appear inside the inner loop.
define void @memcpy_decr_loop(ptr %dst, ptr %src, i32 %n) {
; CHECK-LABEL: memcpy_decr_loop:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    cmp r3, 0
; CHECK-NEXT:    beq .LBB1_2
; CHECK-NEXT:  .LBB1_1: // %loop
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ldb r4, [r2 + 0]
; CHECK-NEXT:    stb r4, [r1 + 0]
; CHECK-NEXT:    add r2, 1
; CHECK-NEXT:    add r1, 1
; CHECK-NEXT:    sub r3, 1
; CHECK-NEXT:    bne .LBB1_1
; CHECK-NEXT:  .LBB1_2: // %exit
; CHECK-NEXT:    jmp lr
entry:
  %z = icmp eq i32 %n, 0
  br i1 %z, label %exit, label %loop
loop:
  %i = phi i32 [ %n, %entry ], [ %i_next, %loop ]
  %s = phi ptr [ %src, %entry ], [ %s_next, %loop ]
  %d = phi ptr [ %dst, %entry ], [ %d_next, %loop ]
  %v = load i8, ptr %s
  store i8 %v, ptr %d
  %s_next = getelementptr i8, ptr %s, i32 1
  %d_next = getelementptr i8, ptr %d, i32 1
  %i_next = sub i32 %i, 1
  %again = icmp ne i32 %i_next, 0
  br i1 %again, label %loop, label %exit
exit:
  ret void
}

;; Negative: the post-decrement value is read between SUBi and CMPi (here
;; via a store).  Sinking the SUBi past the store would change which value
;; the store sees, so the peephole must bail and the CMPi must remain.
define i32 @no_elide_value_used_between(i32 %n, ptr %out) {
; CHECK-LABEL: no_elide_value_used_between:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    sub r1, 1
; CHECK-NEXT:    mov r3, r1
; CHECK-NEXT:  .LBB2_1: // %loop
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    stw r1, [r2 + 0]
; CHECK-NEXT:    sub r3, 1
; CHECK-NEXT:    cmp r1, 0
; CHECK-NEXT:    mov r1, r3
; CHECK-NEXT:    bne .LBB2_1
; CHECK-NEXT:  // %bb.2: // %exit
; CHECK-NEXT:    mov r1, zero
; CHECK-NEXT:    jmp lr
entry:
  br label %loop
loop:
  %i = phi i32 [ %n, %entry ], [ %dec, %loop ]
  %dec = sub i32 %i, 1
  store volatile i32 %dec, ptr %out
  %c = icmp ne i32 %dec, 0
  br i1 %c, label %loop, label %exit
exit:
  ret i32 0
}

;; Negative: the gap between the producer and the CMPi contains an SR
;; reader — the ADC consuming the carry of the `sub lo, 1`.  Sinking the
;; producer past its own carry consumer would hand the ADC stale flags,
;; so the peephole must bail and the CMPi must remain.
define void @no_elide_carry_read_in_gap(i64 %x, ptr %p, ptr %q) {
; CHECK-LABEL: no_elide_carry_read_in_gap:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    sub sp, 4
; CHECK-NEXT:    stw r5, [sp + 0] // 4-byte Folded Spill
; CHECK-NEXT:    llis r11, -1
; CHECK-NEXT:    llis r5, -1
; CHECK-NEXT:    add r1, r11
; CHECK-NEXT:    adc r2, r5
; CHECK-NEXT:    stw r2, [r3 + 0]
; CHECK-NEXT:    cmp r1, 0
; CHECK-NEXT:    bne .LBB3_2
; CHECK-NEXT:  // %bb.1: // %a
; CHECK-NEXT:    lli r1, 1
; CHECK-NEXT:    stw r1, [r4 + 0]
; CHECK-NEXT:  .LBB3_2: // %b
; CHECK-NEXT:    ldw r5, [sp + 0] // 4-byte Folded Reload
; CHECK-NEXT:    add sp, 4
; CHECK-NEXT:    jmp lr
entry:
  %dec = sub i64 %x, 1
  %hi64 = lshr i64 %dec, 32
  %hi = trunc i64 %hi64 to i32
  store i32 %hi, ptr %p
  %lo = trunc i64 %dec to i32
  %cmp = icmp eq i32 %lo, 0
  br i1 %cmp, label %a, label %b
a:
  store i32 1, ptr %q
  br label %b
b:
  ret void
}
