; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; Small positive: single LLI
define i32 @const_small() {
; CHECK-LABEL: const_small:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    lli r1, 42
; CHECK-NEXT:    jmp lr
  ret i32 42
}

; Max unsigned 16-bit: single LLI
define i32 @const_ffff() {
; CHECK-LABEL: const_ffff:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    lli r1, 65535
; CHECK-NEXT:    jmp lr
  ret i32 65535
}

; Small negative: single LLIS
define i32 @const_neg1() {
; CHECK-LABEL: const_neg1:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    llis r1, -1
; CHECK-NEXT:    jmp lr
  ret i32 -1
}

; Negative in LLIS range: single LLIS
define i32 @const_neg100() {
; CHECK-LABEL: const_neg100:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    llis r1, -100
; CHECK-NEXT:    jmp lr
  ret i32 -100
}

; Needs LLI+LUI (upper bits set, low bits nonzero)
define i32 @const_large() {
; CHECK-LABEL: const_large:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    lli r1, 22136
; CHECK-NEXT:    lui r1, 4660
; CHECK-NEXT:    jmp lr
  ret i32 305419896  ; 0x12345678
}

; Upper half only: LLI 0 + LUI, or LLIS+LUI
define i32 @const_upper_only() {
; CHECK-LABEL: const_upper_only:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    lli r1, 0
; CHECK-NEXT:    lui r1, 65535
; CHECK-NEXT:    jmp lr
  ret i32 -65536  ; 0xFFFF0000
}

; All ones in upper half, pattern in lower
define i32 @const_deadbeef() {
; CHECK-LABEL: const_deadbeef:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    lli r1, 48879
; CHECK-NEXT:    lui r1, 57005
; CHECK-NEXT:    jmp lr
  ret i32 -559038737  ; 0xDEADBEEF
}
