; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

define i32 @branch_eq(i32 %a, i32 %b, i32 %x, i32 %y) {
; CHECK-LABEL: branch_eq:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    cmp r1, r2
; CHECK-NEXT:    beq .LBB0_1
; CHECK-NEXT:    b .LBB0_2
; CHECK-NEXT:  .LBB0_1: ; %if.then
; CHECK-NEXT:    mov r1, r3
; CHECK-NEXT:    jmp r13
; CHECK-NEXT:  .LBB0_2: ; %if.else
; CHECK-NEXT:    mov r1, r4
; CHECK-NEXT:    jmp r13
  %cmp = icmp eq i32 %a, %b
  br i1 %cmp, label %if.then, label %if.else
if.then:
  ret i32 %x
if.else:
  ret i32 %y
}

define i32 @branch_slt(i32 %a, i32 %b, i32 %x, i32 %y) {
; CHECK-LABEL: branch_slt:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    cmp r1, r2
; CHECK-NEXT:    blt .LBB1_1
; CHECK-NEXT:    b .LBB1_2
; CHECK-NEXT:  .LBB1_1: ; %if.then
; CHECK-NEXT:    mov r1, r3
; CHECK-NEXT:    jmp r13
; CHECK-NEXT:  .LBB1_2: ; %if.else
; CHECK-NEXT:    mov r1, r4
; CHECK-NEXT:    jmp r13
  %cmp = icmp slt i32 %a, %b
  br i1 %cmp, label %if.then, label %if.else
if.then:
  ret i32 %x
if.else:
  ret i32 %y
}

define i32 @select_eq(i32 %a, i32 %b, i32 %x, i32 %y) {
; CHECK-LABEL: select_eq:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    mov r11, r1
; CHECK-NEXT:    mov r1, r3
; CHECK-NEXT:    cmp r11, r2
; CHECK-NEXT:    beq .LBB2_2
; CHECK-NEXT:  ; %bb.1:
; CHECK-NEXT:    mov r1, r4
; CHECK-NEXT:    b .LBB2_2
; CHECK-NEXT:  .LBB2_2:
; CHECK-NEXT:    jmp r13
  %cmp = icmp eq i32 %a, %b
  %result = select i1 %cmp, i32 %x, i32 %y
  ret i32 %result
}

define i32 @phi_loop(i32 %n) {
; CHECK-LABEL: phi_loop:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    mov r2, r1
; CHECK-NEXT:    lli r1, 0
; CHECK-NEXT:    mov r3, r1
; CHECK-NEXT:    b .LBB3_1
; CHECK-NEXT:  .LBB3_1: ; %loop
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    add r1, r3
; CHECK-NEXT:    add r3, 1
; CHECK-NEXT:    cmp r3, r2
; CHECK-NEXT:    blt .LBB3_1
; CHECK-NEXT:    b .LBB3_2
; CHECK-NEXT:  .LBB3_2: ; %exit
; CHECK-NEXT:    jmp r13
entry:
  br label %loop
loop:
  %i = phi i32 [0, %entry], [%next, %loop]
  %sum = phi i32 [0, %entry], [%newsum, %loop]
  %newsum = add i32 %sum, %i
  %next = add i32 %i, 1
  %cmp = icmp slt i32 %next, %n
  br i1 %cmp, label %loop, label %exit
exit:
  ret i32 %newsum
}
