; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra -global-isel -O0 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=O0
; RUN: llc -mtriple=penumbra -global-isel -O1 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=O1

; Division/remainder test: exercises G_FREEZE, G_ABS, and libcall lowering.

define i32 @udiv(i32 %a, i32 %b) {
; O0-LABEL: udiv:
; O0:         .cfi_startproc
; O0-NEXT:  // %bb.1:
; O0-NEXT:    divu r1, r2
; O0-NEXT:    jmp lr
;
; O1-LABEL: udiv:
; O1:         .cfi_startproc
; O1-NEXT:  // %bb.0:
; O1-NEXT:    divu r1, r2
; O1-NEXT:    jmp lr
  %result = udiv i32 %a, %b
  ret i32 %result
}

define i32 @sdiv(i32 %a, i32 %b) {
; O0-LABEL: sdiv:
; O0:         .cfi_startproc
; O0-NEXT:  // %bb.1:
; O0-NEXT:    div r1, r2
; O0-NEXT:    jmp lr
;
; O1-LABEL: sdiv:
; O1:         .cfi_startproc
; O1-NEXT:  // %bb.0:
; O1-NEXT:    div r1, r2
; O1-NEXT:    jmp lr
  %result = sdiv i32 %a, %b
  ret i32 %result
}

define i32 @urem(i32 %a, i32 %b) {
; O0-LABEL: urem:
; O0:         .cfi_startproc
; O0-NEXT:  // %bb.1:
; O0-NEXT:    sub sp, 4
; O0-NEXT:    stw r1, [sp + 0] // 4-byte Folded Spill
; O0-NEXT:    mov r1, r2
; O0-NEXT:    ldw r2, [sp + 0] // 4-byte Folded Reload
; O0-NEXT:    divu r2, r1, r1
; O0-NEXT:    add sp, 4
; O0-NEXT:    jmp lr
;
; O1-LABEL: urem:
; O1:         .cfi_startproc
; O1-NEXT:  // %bb.0:
; O1-NEXT:    divu r1, r2, r2
; O1-NEXT:    mov r1, r2
; O1-NEXT:    jmp lr
  %result = urem i32 %a, %b
  ret i32 %result
}

define i32 @srem(i32 %a, i32 %b) {
; O0-LABEL: srem:
; O0:         .cfi_startproc
; O0-NEXT:  // %bb.1:
; O0-NEXT:    sub sp, 4
; O0-NEXT:    stw r1, [sp + 0] // 4-byte Folded Spill
; O0-NEXT:    mov r1, r2
; O0-NEXT:    ldw r2, [sp + 0] // 4-byte Folded Reload
; O0-NEXT:    div r2, r1, r1
; O0-NEXT:    add sp, 4
; O0-NEXT:    jmp lr
;
; O1-LABEL: srem:
; O1:         .cfi_startproc
; O1-NEXT:  // %bb.0:
; O1-NEXT:    div r1, r2, r2
; O1-NEXT:    mov r1, r2
; O1-NEXT:    jmp lr
  %result = srem i32 %a, %b
  ret i32 %result
}
