; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra-unknown-none -O0 < %s | FileCheck %s

; Dynamic stack allocation (VLA / alloca with runtime size).
; Verifies G_DYN_STACKALLOC lowering: round up size, subtract from SP.

define ptr @dynamic_alloca(i32 %n) {
; CHECK-LABEL: dynamic_alloca:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    sub sp, 4
; CHECK-NEXT:    stw r10, [sp + 0] // 4-byte Folded Spill
; CHECK-NEXT:    mov r10, sp
; CHECK-NEXT:    mov r2, r1
; CHECK-NEXT:    shl r2, 0
; CHECK-NEXT:    add r2, 3
; CHECK-NEXT:    llis r1, -4
; CHECK-NEXT:    and r2, r1
; CHECK-NEXT:    mov r1, sp
; CHECK-NEXT:    sub r1, r2
; CHECK-NEXT:    mov sp, r1
; CHECK-NEXT:    mov sp, r10
; CHECK-NEXT:    ldw r10, [sp + 0] // 4-byte Folded Reload
; CHECK-NEXT:    add sp, 4
; CHECK-NEXT:    jmp lr
  %p = alloca i8, i32 %n
  ret ptr %p
}
