; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra-unknown-none -global-isel < %s | FileCheck %s

; Extending loads into i64 destinations: InstCombine merges adjacent
; bitfield / i128 struct accesses into single wide zext/sext loads.
; The legalizer must narrow the s64 destination into two s32 halves —
; low half is the loaded (and if sub-word, extended) value; high half
; is either zero (G_ZEXTLOAD) or the sign replication of the low half
; (G_SEXTLOAD).

define i64 @zextload_i8_to_i64(ptr %p) {
; CHECK-LABEL: zextload_i8_to_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ldb r1, [r1 + 0]
; CHECK-NEXT:    mov r2, zero
; CHECK-NEXT:    jmp lr
  %v = load i8, ptr %p
  %ext = zext i8 %v to i64
  ret i64 %ext
}

define i64 @zextload_i16_to_i64(ptr %p) {
; CHECK-LABEL: zextload_i16_to_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ldh r1, [r1 + 0]
; CHECK-NEXT:    mov r2, zero
; CHECK-NEXT:    jmp lr
  %v = load i16, ptr %p
  %ext = zext i16 %v to i64
  ret i64 %ext
}

define i64 @zextload_i32_to_i64(ptr %p) {
; CHECK-LABEL: zextload_i32_to_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ldw r1, [r1 + 0]
; CHECK-NEXT:    mov r2, zero
; CHECK-NEXT:    jmp lr
  %v = load i32, ptr %p
  %ext = zext i32 %v to i64
  ret i64 %ext
}

define i64 @sextload_i8_to_i64(ptr %p) {
; CHECK-LABEL: sextload_i8_to_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ldbs r1, [r1 + 0]
; CHECK-NEXT:    mov r2, r1
; CHECK-NEXT:    sar r2, 31
; CHECK-NEXT:    jmp lr
  %v = load i8, ptr %p
  %ext = sext i8 %v to i64
  ret i64 %ext
}

define i64 @sextload_i16_to_i64(ptr %p) {
; CHECK-LABEL: sextload_i16_to_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ldhs r1, [r1 + 0]
; CHECK-NEXT:    mov r2, r1
; CHECK-NEXT:    sar r2, 31
; CHECK-NEXT:    jmp lr
  %v = load i16, ptr %p
  %ext = sext i16 %v to i64
  ret i64 %ext
}

define i64 @sextload_i32_to_i64(ptr %p) {
; CHECK-LABEL: sextload_i32_to_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ldw r1, [r1 + 0]
; CHECK-NEXT:    mov r2, r1
; CHECK-NEXT:    sar r2, 31
; CHECK-NEXT:    jmp lr
  %v = load i32, ptr %p
  %ext = sext i32 %v to i64
  ret i64 %ext
}
