; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra-unknown-none -verify-machineinstrs < %s | FileCheck %s

; The ABI requires SP to stay 4-byte aligned at every instruction, not
; only at call sites.  Leaf-function frames are rounded by PEI to the
; transient stack alignment, so a byte-sized spill slot in a leaf must
; still produce a 4-byte-multiple frame — a `sub sp, 1` here once let
; an interrupt land on an odd SP.

define i8 @leaf_byte_spill(i8 %v) {
; CHECK-LABEL: leaf_byte_spill:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 4
; CHECK-NEXT:    stb r1, [sp + 3]
; CHECK-NEXT:    ldb r1, [sp + 3]
; CHECK-NEXT:    add sp, 4
; CHECK-NEXT:    jmp lr
  %slot = alloca i8
  store volatile i8 %v, ptr %slot
  %r = load volatile i8, ptr %slot
  ret i8 %r
}
