; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; Funnel shift left (s8): sub-word rotate recognized by InstCombine at -O2
; from `(x >> c) | (x << (8 - c))` idioms (e.g. GCC PR target/56866).
; Lowered via lowerFunnelShiftAsShifts at the original s8 width, then the
; underlying SHL/LSHR/OR instructions get widened to s32 by the legalizer.
declare i8 @llvm.fshl.i8(i8, i8, i8)
define i8 @fshl_i8(i8 %a, i8 %b, i8 %sh) {
; CHECK-LABEL: fshl_i8:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r4, r3
; CHECK-NEXT:    and r4, 7
; CHECK-NEXT:    not r3, r3
; CHECK-NEXT:    and r3, 7
; CHECK-NEXT:    shl r1, r4
; CHECK-NEXT:    and r2, 255
; CHECK-NEXT:    shr r2, 1
; CHECK-NEXT:    shr r2, r3
; CHECK-NEXT:    or r1, r2
; CHECK-NEXT:    jmp r13
  %r = call i8 @llvm.fshl.i8(i8 %a, i8 %b, i8 %sh)
  ret i8 %r
}

; Funnel shift left (s16).
declare i16 @llvm.fshl.i16(i16, i16, i16)
define i16 @fshl_i16(i16 %a, i16 %b, i16 %sh) {
; CHECK-LABEL: fshl_i16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r4, r3
; CHECK-NEXT:    and r4, 15
; CHECK-NEXT:    not r3, r3
; CHECK-NEXT:    and r3, 15
; CHECK-NEXT:    shl r1, r4
; CHECK-NEXT:    and r2, 65535
; CHECK-NEXT:    shr r2, 1
; CHECK-NEXT:    shr r2, r3
; CHECK-NEXT:    or r1, r2
; CHECK-NEXT:    jmp r13
  %r = call i16 @llvm.fshl.i16(i16 %a, i16 %b, i16 %sh)
  ret i16 %r
}

; Funnel shift left (s32): used by compiler-rt __udivsi3.
declare i32 @llvm.fshl.i32(i32, i32, i32)
define i32 @fshl_i32(i32 %a, i32 %b, i32 %sh) {
; CHECK-LABEL: fshl_i32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r4, r3
; CHECK-NEXT:    and r4, 31
; CHECK-NEXT:    not r3, r3
; CHECK-NEXT:    and r3, 31
; CHECK-NEXT:    shl r1, r4
; CHECK-NEXT:    shr r2, 1
; CHECK-NEXT:    shr r2, r3
; CHECK-NEXT:    or r1, r2
; CHECK-NEXT:    jmp r13
  %r = call i32 @llvm.fshl.i32(i32 %a, i32 %b, i32 %sh)
  ret i32 %r
}

; Funnel shift right (s32).
declare i32 @llvm.fshr.i32(i32, i32, i32)
define i32 @fshr_i32(i32 %a, i32 %b, i32 %sh) {
; CHECK-LABEL: fshr_i32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r4, r3
; CHECK-NEXT:    and r4, 31
; CHECK-NEXT:    not r3, r3
; CHECK-NEXT:    and r3, 31
; CHECK-NEXT:    shl r1, 1
; CHECK-NEXT:    shl r1, r3
; CHECK-NEXT:    shr r2, r4
; CHECK-NEXT:    or r1, r2
; CHECK-NEXT:    jmp r13
  %r = call i32 @llvm.fshr.i32(i32 %a, i32 %b, i32 %sh)
  ret i32 %r
}

; Funnel shift left (s64): used by SHA512.
declare i64 @llvm.fshl.i64(i64, i64, i64)
define i64 @fshl_i64(i64 %a, i64 %b, i64 %sh) {
; CHECK-LABEL: fshl_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub r14, 36
; CHECK-NEXT:    stw r5, [r14 + 32] // 4-byte Folded Spill
; CHECK-NEXT:    stw r6, [r14 + 28] // 4-byte Folded Spill
; CHECK-NEXT:    stw r7, [r14 + 24] // 4-byte Folded Spill
; CHECK-NEXT:    stw r8, [r14 + 20] // 4-byte Folded Spill
; CHECK-NEXT:    stw r9, [r14 + 16] // 4-byte Folded Spill
; CHECK-NEXT:    stw r10, [r14 + 12] // 4-byte Folded Spill
; CHECK-NEXT:    stw r13, [r14 + 8] // 4-byte Folded Spill
; CHECK-NEXT:    stw r2, [r14 + 4] // 4-byte Folded Spill
; CHECK-NEXT:    stw r3, [r14 + 0] // 4-byte Folded Spill
; CHECK-NEXT:    ldw r2, [r14 + 36]
; CHECK-NEXT:    mov r13, r0
; CHECK-NEXT:    mov r7, r2
; CHECK-NEXT:    and r7, 63
; CHECK-NEXT:    not r5, r2
; CHECK-NEXT:    and r5, 63
; CHECK-NEXT:    lli r11, 32
; CHECK-NEXT:    mov r8, r7
; CHECK-NEXT:    sub r8, r11
; CHECK-NEXT:    mov r9, r11
; CHECK-NEXT:    sub r9, r7
; CHECK-NEXT:    lli r6, 1
; CHECK-NEXT:    lli r2, 0
; CHECK-NEXT:    cmp r7, r11
; CHECK-NEXT:    bcc .LBB4_2
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    mov r6, r2
; CHECK-NEXT:  .LBB4_2:
; CHECK-NEXT:    lli r2, 1
; CHECK-NEXT:    lli r11, 0
; CHECK-NEXT:    cmp r13, r13
; CHECK-NEXT:    bcc .LBB4_4
; CHECK-NEXT:  // %bb.3:
; CHECK-NEXT:    mov r2, r11
; CHECK-NEXT:  .LBB4_4:
; CHECK-NEXT:    mov r11, r0
; CHECK-NEXT:    cmp r13, r13
; CHECK-NEXT:    beq .LBB4_6
; CHECK-NEXT:  // %bb.5:
; CHECK-NEXT:    mov r6, r2
; CHECK-NEXT:  .LBB4_6:
; CHECK-NEXT:    mov r10, r7
; CHECK-NEXT:    xor r10, r11
; CHECK-NEXT:    mov r3, r1
; CHECK-NEXT:    shl r3, r7
; CHECK-NEXT:    mov r11, r1
; CHECK-NEXT:    shr r11, r9
; CHECK-NEXT:    ldw r9, [r14 + 4] // 4-byte Folded Reload
; CHECK-NEXT:    shl r9, r7
; CHECK-NEXT:    or r11, r9
; CHECK-NEXT:    shl r1, r8
; CHECK-NEXT:    test r6, 1
; CHECK-NEXT:    bne .LBB4_8
; CHECK-NEXT:  // %bb.7:
; CHECK-NEXT:    mov r3, r0
; CHECK-NEXT:  .LBB4_8:
; CHECK-NEXT:    mov r7, r0
; CHECK-NEXT:    test r6, 1
; CHECK-NEXT:    ldw r2, [r14 + 0] // 4-byte Folded Reload
; CHECK-NEXT:    bne .LBB4_10
; CHECK-NEXT:  // %bb.9:
; CHECK-NEXT:    mov r11, r1
; CHECK-NEXT:  .LBB4_10:
; CHECK-NEXT:    cmp r10, r7
; CHECK-NEXT:    beq .LBB4_12
; CHECK-NEXT:  // %bb.11:
; CHECK-NEXT:    stw r11, [r14 + 4] // 4-byte Folded Spill
; CHECK-NEXT:  .LBB4_12:
; CHECK-NEXT:    shr r2, 1
; CHECK-NEXT:    mov r1, r4
; CHECK-NEXT:    shl r1, 31
; CHECK-NEXT:    or r2, r1
; CHECK-NEXT:    shr r4, 1
; CHECK-NEXT:    lli r9, 32
; CHECK-NEXT:    mov r1, r0
; CHECK-NEXT:    mov r6, r5
; CHECK-NEXT:    sub r6, r9
; CHECK-NEXT:    mov r7, r9
; CHECK-NEXT:    sub r7, r5
; CHECK-NEXT:    lli r11, 1
; CHECK-NEXT:    lli r8, 0
; CHECK-NEXT:    cmp r5, r9
; CHECK-NEXT:    bcc .LBB4_14
; CHECK-NEXT:  // %bb.13:
; CHECK-NEXT:    mov r11, r8
; CHECK-NEXT:  .LBB4_14:
; CHECK-NEXT:    lli r8, 1
; CHECK-NEXT:    lli r9, 0
; CHECK-NEXT:    cmp r13, r1
; CHECK-NEXT:    bcc .LBB4_16
; CHECK-NEXT:  // %bb.15:
; CHECK-NEXT:    mov r8, r9
; CHECK-NEXT:  .LBB4_16:
; CHECK-NEXT:    mov r9, r0
; CHECK-NEXT:    cmp r13, r1
; CHECK-NEXT:    beq .LBB4_18
; CHECK-NEXT:  // %bb.17:
; CHECK-NEXT:    mov r11, r8
; CHECK-NEXT:  .LBB4_18:
; CHECK-NEXT:    mov r1, r0
; CHECK-NEXT:    mov r8, r5
; CHECK-NEXT:    xor r8, r9
; CHECK-NEXT:    mov r13, r4
; CHECK-NEXT:    shr r13, r5
; CHECK-NEXT:    mov r9, r2
; CHECK-NEXT:    shr r9, r5
; CHECK-NEXT:    mov r5, r4
; CHECK-NEXT:    shl r5, r7
; CHECK-NEXT:    or r9, r5
; CHECK-NEXT:    shr r4, r6
; CHECK-NEXT:    test r11, 1
; CHECK-NEXT:    beq .LBB4_19
; CHECK-NEXT:  // %bb.20:
; CHECK-NEXT:    cmp r8, r1
; CHECK-NEXT:    bne .LBB4_21
; CHECK-NEXT:  .LBB4_22:
; CHECK-NEXT:    test r11, 1
; CHECK-NEXT:    bne .LBB4_24
; CHECK-NEXT:  .LBB4_23:
; CHECK-NEXT:    mov r13, r0
; CHECK-NEXT:  .LBB4_24:
; CHECK-NEXT:    or r3, r2
; CHECK-NEXT:    ldw r2, [r14 + 4] // 4-byte Folded Reload
; CHECK-NEXT:    or r2, r13
; CHECK-NEXT:    mov r1, r3
; CHECK-NEXT:    ldw r13, [r14 + 8] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r10, [r14 + 12] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r9, [r14 + 16] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r8, [r14 + 20] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r7, [r14 + 24] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r6, [r14 + 28] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r5, [r14 + 32] // 4-byte Folded Reload
; CHECK-NEXT:    add r14, 36
; CHECK-NEXT:    jmp r13
; CHECK-NEXT:  .LBB4_19:
; CHECK-NEXT:    mov r9, r4
; CHECK-NEXT:    cmp r8, r1
; CHECK-NEXT:    beq .LBB4_22
; CHECK-NEXT:  .LBB4_21:
; CHECK-NEXT:    mov r2, r9
; CHECK-NEXT:    test r11, 1
; CHECK-NEXT:    beq .LBB4_23
; CHECK-NEXT:    b .LBB4_24
  %r = call i64 @llvm.fshl.i64(i64 %a, i64 %b, i64 %sh)
  ret i64 %r
}

; Byte swap (s32): used by SHA1, networking.
declare i32 @llvm.bswap.i32(i32)
define i32 @bswap_i32(i32 %a) {
; CHECK-LABEL: bswap_i32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r3, r1
; CHECK-NEXT:    shl r3, 24
; CHECK-NEXT:    mov r2, r1
; CHECK-NEXT:    shr r2, 24
; CHECK-NEXT:    or r2, r3
; CHECK-NEXT:    mov r3, r1
; CHECK-NEXT:    and r3, 65280
; CHECK-NEXT:    shl r3, 8
; CHECK-NEXT:    or r2, r3
; CHECK-NEXT:    shr r1, 8
; CHECK-NEXT:    and r1, 65280
; CHECK-NEXT:    or r2, r1
; CHECK-NEXT:    mov r1, r2
; CHECK-NEXT:    jmp r13
  %r = call i32 @llvm.bswap.i32(i32 %a)
  ret i32 %r
}

; Byte swap (s64): used by SHA512.
declare i64 @llvm.bswap.i64(i64)
define i64 @bswap_i64(i64 %a) {
; CHECK-LABEL: bswap_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r4, r2
; CHECK-NEXT:    shl r4, 24
; CHECK-NEXT:    mov r3, r2
; CHECK-NEXT:    shr r3, 24
; CHECK-NEXT:    or r3, r4
; CHECK-NEXT:    mov r4, r2
; CHECK-NEXT:    and r4, 65280
; CHECK-NEXT:    shl r4, 8
; CHECK-NEXT:    or r3, r4
; CHECK-NEXT:    shr r2, 8
; CHECK-NEXT:    and r2, 65280
; CHECK-NEXT:    or r3, r2
; CHECK-NEXT:    mov r4, r1
; CHECK-NEXT:    shl r4, 24
; CHECK-NEXT:    mov r2, r1
; CHECK-NEXT:    shr r2, 24
; CHECK-NEXT:    or r2, r4
; CHECK-NEXT:    mov r4, r1
; CHECK-NEXT:    and r4, 65280
; CHECK-NEXT:    shl r4, 8
; CHECK-NEXT:    or r2, r4
; CHECK-NEXT:    shr r1, 8
; CHECK-NEXT:    and r1, 65280
; CHECK-NEXT:    or r2, r1
; CHECK-NEXT:    mov r1, r3
; CHECK-NEXT:    jmp r13
  %r = call i64 @llvm.bswap.i64(i64 %a)
  ret i64 %r
}
