; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; Funnel shift left (s8): sub-word rotate recognized by InstCombine at -O2
; from `(x >> c) | (x << (8 - c))` idioms (e.g. GCC PR target/56866).
; Lowered via lowerFunnelShiftAsShifts at the original s8 width, then the
; underlying SHL/LSHR/OR instructions get widened to s32 by the legalizer.
declare i8 @llvm.fshl.i8(i8, i8, i8)
define i8 @fshl_i8(i8 %a, i8 %b, i8 %sh) {
; CHECK-LABEL: fshl_i8:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r4, r3
; CHECK-NEXT:    and r4, 7
; CHECK-NEXT:    not r3, r3
; CHECK-NEXT:    and r3, 7
; CHECK-NEXT:    shl r1, r4
; CHECK-NEXT:    and r2, 255
; CHECK-NEXT:    shr r2, 1
; CHECK-NEXT:    shr r2, r3
; CHECK-NEXT:    or r1, r2
; CHECK-NEXT:    jmp lr
  %r = call i8 @llvm.fshl.i8(i8 %a, i8 %b, i8 %sh)
  ret i8 %r
}

; Funnel shift left (s16).
declare i16 @llvm.fshl.i16(i16, i16, i16)
define i16 @fshl_i16(i16 %a, i16 %b, i16 %sh) {
; CHECK-LABEL: fshl_i16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r4, r3
; CHECK-NEXT:    and r4, 15
; CHECK-NEXT:    not r3, r3
; CHECK-NEXT:    and r3, 15
; CHECK-NEXT:    shl r1, r4
; CHECK-NEXT:    and r2, 65535
; CHECK-NEXT:    shr r2, 1
; CHECK-NEXT:    shr r2, r3
; CHECK-NEXT:    or r1, r2
; CHECK-NEXT:    jmp lr
  %r = call i16 @llvm.fshl.i16(i16 %a, i16 %b, i16 %sh)
  ret i16 %r
}

; Funnel shift left (s32): used by compiler-rt __udivsi3.
declare i32 @llvm.fshl.i32(i32, i32, i32)
define i32 @fshl_i32(i32 %a, i32 %b, i32 %sh) {
; CHECK-LABEL: fshl_i32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r4, r3
; CHECK-NEXT:    and r4, 31
; CHECK-NEXT:    not r3, r3
; CHECK-NEXT:    and r3, 31
; CHECK-NEXT:    shl r1, r4
; CHECK-NEXT:    shr r2, 1
; CHECK-NEXT:    shr r2, r3
; CHECK-NEXT:    or r1, r2
; CHECK-NEXT:    jmp lr
  %r = call i32 @llvm.fshl.i32(i32 %a, i32 %b, i32 %sh)
  ret i32 %r
}

; Funnel shift right (s32).
declare i32 @llvm.fshr.i32(i32, i32, i32)
define i32 @fshr_i32(i32 %a, i32 %b, i32 %sh) {
; CHECK-LABEL: fshr_i32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r4, r3
; CHECK-NEXT:    and r4, 31
; CHECK-NEXT:    not r3, r3
; CHECK-NEXT:    and r3, 31
; CHECK-NEXT:    shl r1, 1
; CHECK-NEXT:    shl r1, r3
; CHECK-NEXT:    shr r2, r4
; CHECK-NEXT:    or r1, r2
; CHECK-NEXT:    jmp lr
  %r = call i32 @llvm.fshr.i32(i32 %a, i32 %b, i32 %sh)
  ret i32 %r
}

; Funnel shift left (s64): used by SHA512.
declare i64 @llvm.fshl.i64(i64, i64, i64)
define i64 @fshl_i64(i64 %a, i64 %b, i64 %sh) {
; CHECK-LABEL: fshl_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 36
; CHECK-NEXT:    stw r5, [sp + 32] // 4-byte Folded Spill
; CHECK-NEXT:    stw r6, [sp + 28] // 4-byte Folded Spill
; CHECK-NEXT:    stw r7, [sp + 24] // 4-byte Folded Spill
; CHECK-NEXT:    stw r8, [sp + 20] // 4-byte Folded Spill
; CHECK-NEXT:    stw r9, [sp + 16] // 4-byte Folded Spill
; CHECK-NEXT:    stw r10, [sp + 12] // 4-byte Folded Spill
; CHECK-NEXT:    stw lr, [sp + 8] // 4-byte Folded Spill
; CHECK-NEXT:    stw r2, [sp + 4] // 4-byte Folded Spill
; CHECK-NEXT:    stw r3, [sp + 0] // 4-byte Folded Spill
; CHECK-NEXT:    ldw r2, [sp + 36]
; CHECK-NEXT:    mov lr, zero
; CHECK-NEXT:    mov r7, r2
; CHECK-NEXT:    and r7, 63
; CHECK-NEXT:    not r5, r2
; CHECK-NEXT:    and r5, 63
; CHECK-NEXT:    lli r9, 32
; CHECK-NEXT:    mov r8, r7
; CHECK-NEXT:    sub r8, r9
; CHECK-NEXT:    sub r9, r7
; CHECK-NEXT:    cmp r7, 32
; CHECK-NEXT:    mov r6, lr
; CHECK-NEXT:    sbc r6, zero
; CHECK-NEXT:    and r6, 1
; CHECK-NEXT:    cmp lr, 0
; CHECK-NEXT:    mov r2, lr
; CHECK-NEXT:    sbc r2, zero
; CHECK-NEXT:    and r2, 1
; CHECK-NEXT:    cmp lr, 0
; CHECK-NEXT:    beq .LBB4_2
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    mov r6, r2
; CHECK-NEXT:  .LBB4_2:
; CHECK-NEXT:    mov r10, r7
; CHECK-NEXT:    xor r10, lr
; CHECK-NEXT:    mov r3, r1
; CHECK-NEXT:    shl r3, r7
; CHECK-NEXT:    mov r11, r1
; CHECK-NEXT:    shr r11, r9
; CHECK-NEXT:    ldw r9, [sp + 4] // 4-byte Folded Reload
; CHECK-NEXT:    shl r9, r7
; CHECK-NEXT:    or r11, r9
; CHECK-NEXT:    shl r1, r8
; CHECK-NEXT:    test r6, 1
; CHECK-NEXT:    ldw r2, [sp + 0] // 4-byte Folded Reload
; CHECK-NEXT:    beq .LBB4_3
; CHECK-NEXT:  // %bb.4:
; CHECK-NEXT:    test r6, 1
; CHECK-NEXT:    beq .LBB4_5
; CHECK-NEXT:  .LBB4_6:
; CHECK-NEXT:    cmp r10, 0
; CHECK-NEXT:    beq .LBB4_8
; CHECK-NEXT:  .LBB4_7:
; CHECK-NEXT:    stw r11, [sp + 4] // 4-byte Folded Spill
; CHECK-NEXT:  .LBB4_8:
; CHECK-NEXT:    shr r2, 1
; CHECK-NEXT:    mov r1, r4
; CHECK-NEXT:    shl r1, 31
; CHECK-NEXT:    or r2, r1
; CHECK-NEXT:    shr r4, 1
; CHECK-NEXT:    lli r7, 32
; CHECK-NEXT:    mov r6, r5
; CHECK-NEXT:    sub r6, r7
; CHECK-NEXT:    sub r7, r5
; CHECK-NEXT:    mov r1, zero
; CHECK-NEXT:    cmp r5, 32
; CHECK-NEXT:    mov r11, r1
; CHECK-NEXT:    sbc r11, zero
; CHECK-NEXT:    and r11, 1
; CHECK-NEXT:    cmp lr, 0
; CHECK-NEXT:    mov r8, r1
; CHECK-NEXT:    sbc r8, zero
; CHECK-NEXT:    and r8, 1
; CHECK-NEXT:    cmp lr, 0
; CHECK-NEXT:    beq .LBB4_10
; CHECK-NEXT:  // %bb.9:
; CHECK-NEXT:    mov r11, r8
; CHECK-NEXT:  .LBB4_10:
; CHECK-NEXT:    mov r8, r5
; CHECK-NEXT:    xor r8, r1
; CHECK-NEXT:    mov lr, r4
; CHECK-NEXT:    shr lr, r5
; CHECK-NEXT:    mov r1, r2
; CHECK-NEXT:    shr r1, r5
; CHECK-NEXT:    mov r5, r4
; CHECK-NEXT:    shl r5, r7
; CHECK-NEXT:    or r1, r5
; CHECK-NEXT:    shr r4, r6
; CHECK-NEXT:    test r11, 1
; CHECK-NEXT:    beq .LBB4_11
; CHECK-NEXT:  // %bb.12:
; CHECK-NEXT:    cmp r8, 0
; CHECK-NEXT:    bne .LBB4_13
; CHECK-NEXT:  .LBB4_14:
; CHECK-NEXT:    test r11, 1
; CHECK-NEXT:    bne .LBB4_16
; CHECK-NEXT:  .LBB4_15:
; CHECK-NEXT:    mov lr, zero
; CHECK-NEXT:  .LBB4_16:
; CHECK-NEXT:    or r3, r2
; CHECK-NEXT:    ldw r2, [sp + 4] // 4-byte Folded Reload
; CHECK-NEXT:    or r2, lr
; CHECK-NEXT:    mov r1, r3
; CHECK-NEXT:    ldw lr, [sp + 8] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r10, [sp + 12] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r9, [sp + 16] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r8, [sp + 20] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r7, [sp + 24] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r6, [sp + 28] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r5, [sp + 32] // 4-byte Folded Reload
; CHECK-NEXT:    add sp, 36
; CHECK-NEXT:    jmp lr
; CHECK-NEXT:  .LBB4_3:
; CHECK-NEXT:    mov r3, zero
; CHECK-NEXT:    test r6, 1
; CHECK-NEXT:    bne .LBB4_6
; CHECK-NEXT:  .LBB4_5:
; CHECK-NEXT:    mov r11, r1
; CHECK-NEXT:    cmp r10, 0
; CHECK-NEXT:    bne .LBB4_7
; CHECK-NEXT:    b .LBB4_8
; CHECK-NEXT:  .LBB4_11:
; CHECK-NEXT:    mov r1, r4
; CHECK-NEXT:    cmp r8, 0
; CHECK-NEXT:    beq .LBB4_14
; CHECK-NEXT:  .LBB4_13:
; CHECK-NEXT:    mov r2, r1
; CHECK-NEXT:    test r11, 1
; CHECK-NEXT:    beq .LBB4_15
; CHECK-NEXT:    b .LBB4_16
  %r = call i64 @llvm.fshl.i64(i64 %a, i64 %b, i64 %sh)
  ret i64 %r
}

; Byte swap (s32): used by SHA1, networking.
declare i32 @llvm.bswap.i32(i32)
define i32 @bswap_i32(i32 %a) {
; CHECK-LABEL: bswap_i32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r3, r1
; CHECK-NEXT:    shl r3, 24
; CHECK-NEXT:    mov r2, r1
; CHECK-NEXT:    shr r2, 24
; CHECK-NEXT:    or r2, r3
; CHECK-NEXT:    mov r3, r1
; CHECK-NEXT:    and r3, 65280
; CHECK-NEXT:    shl r3, 8
; CHECK-NEXT:    or r2, r3
; CHECK-NEXT:    shr r1, 8
; CHECK-NEXT:    and r1, 65280
; CHECK-NEXT:    or r2, r1
; CHECK-NEXT:    mov r1, r2
; CHECK-NEXT:    jmp lr
  %r = call i32 @llvm.bswap.i32(i32 %a)
  ret i32 %r
}

; Byte swap (s64): used by SHA512.
declare i64 @llvm.bswap.i64(i64)
define i64 @bswap_i64(i64 %a) {
; CHECK-LABEL: bswap_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r4, r2
; CHECK-NEXT:    shl r4, 24
; CHECK-NEXT:    mov r3, r2
; CHECK-NEXT:    shr r3, 24
; CHECK-NEXT:    or r3, r4
; CHECK-NEXT:    mov r4, r2
; CHECK-NEXT:    and r4, 65280
; CHECK-NEXT:    shl r4, 8
; CHECK-NEXT:    or r3, r4
; CHECK-NEXT:    shr r2, 8
; CHECK-NEXT:    and r2, 65280
; CHECK-NEXT:    or r3, r2
; CHECK-NEXT:    mov r4, r1
; CHECK-NEXT:    shl r4, 24
; CHECK-NEXT:    mov r2, r1
; CHECK-NEXT:    shr r2, 24
; CHECK-NEXT:    or r2, r4
; CHECK-NEXT:    mov r4, r1
; CHECK-NEXT:    and r4, 65280
; CHECK-NEXT:    shl r4, 8
; CHECK-NEXT:    or r2, r4
; CHECK-NEXT:    shr r1, 8
; CHECK-NEXT:    and r1, 65280
; CHECK-NEXT:    or r2, r1
; CHECK-NEXT:    mov r1, r3
; CHECK-NEXT:    jmp lr
  %r = call i64 @llvm.bswap.i64(i64 %a)
  ret i64 %r
}
