; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; Tests global address materialization (LLI+LUI with lo16/hi16).
; This exercises the SSA-correct intermediate vreg pattern.

@gvar = global i32 0

define i32 @load_global() {
; CHECK-LABEL: load_global:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    lli r1, %lo16(gvar)
; CHECK-NEXT:    lui r1, %hi16(gvar)
; CHECK-NEXT:    ldw r1, [r1 + 0]
; CHECK-NEXT:    jmp lr
  %v = load i32, ptr @gvar
  ret i32 %v
}

define void @store_global(i32 %v) {
; CHECK-LABEL: store_global:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    lli r2, %lo16(gvar)
; CHECK-NEXT:    lui r2, %hi16(gvar)
; CHECK-NEXT:    stw r1, [r2 + 0]
; CHECK-NEXT:    jmp lr
  store i32 %v, ptr @gvar
  ret void
}

define ptr @addr_global() {
; CHECK-LABEL: addr_global:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    lli r1, %lo16(gvar)
; CHECK-NEXT:    lui r1, %hi16(gvar)
; CHECK-NEXT:    jmp lr
  ret ptr @gvar
}

@array = global [4 x i32] zeroinitializer

define i32 @load_global_offset() {
; CHECK-LABEL: load_global_offset:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    lli r1, %lo16(array)
; CHECK-NEXT:    lui r1, %hi16(array)
; CHECK-NEXT:    ldw r1, [r1 + 8]
; CHECK-NEXT:    jmp lr
  %p = getelementptr [4 x i32], ptr @array, i32 0, i32 2
  %v = load i32, ptr %p
  ret i32 %v
}
