; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra -global-isel -O0 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=O0
; RUN: llc -mtriple=penumbra -global-isel -O1 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=O1

; i64 division/remainder/multiply: all go to 64-bit libcalls.

define i64 @udiv64(i64 %a, i64 %b) {
; O0-LABEL: udiv64:
; O0:         .cfi_startproc
; O0-NEXT:  // %bb.1:
; O0-NEXT:    sub r14, 4
; O0-NEXT:    stw r13, [r14 + 0] // 4-byte Folded Spill
; O0-NEXT:    bl __udivdi3
; O0-NEXT:    ldw r13, [r14 + 0] // 4-byte Folded Reload
; O0-NEXT:    add r14, 4
; O0-NEXT:    jmp r13
;
; O1-LABEL: udiv64:
; O1:         .cfi_startproc
; O1-NEXT:  // %bb.0:
; O1-NEXT:    sub r14, 4
; O1-NEXT:    stw r13, [r14 + 0] // 4-byte Folded Spill
; O1-NEXT:    bl __udivdi3
; O1-NEXT:    ldw r13, [r14 + 0] // 4-byte Folded Reload
; O1-NEXT:    add r14, 4
; O1-NEXT:    jmp r13
  %r = udiv i64 %a, %b
  ret i64 %r
}

define i64 @sdiv64(i64 %a, i64 %b) {
; O0-LABEL: sdiv64:
; O0:         .cfi_startproc
; O0-NEXT:  // %bb.1:
; O0-NEXT:    sub r14, 4
; O0-NEXT:    stw r13, [r14 + 0] // 4-byte Folded Spill
; O0-NEXT:    bl __divdi3
; O0-NEXT:    ldw r13, [r14 + 0] // 4-byte Folded Reload
; O0-NEXT:    add r14, 4
; O0-NEXT:    jmp r13
;
; O1-LABEL: sdiv64:
; O1:         .cfi_startproc
; O1-NEXT:  // %bb.0:
; O1-NEXT:    sub r14, 4
; O1-NEXT:    stw r13, [r14 + 0] // 4-byte Folded Spill
; O1-NEXT:    bl __divdi3
; O1-NEXT:    ldw r13, [r14 + 0] // 4-byte Folded Reload
; O1-NEXT:    add r14, 4
; O1-NEXT:    jmp r13
  %r = sdiv i64 %a, %b
  ret i64 %r
}

define i64 @urem64(i64 %a, i64 %b) {
; O0-LABEL: urem64:
; O0:         .cfi_startproc
; O0-NEXT:  // %bb.1:
; O0-NEXT:    sub r14, 4
; O0-NEXT:    stw r13, [r14 + 0] // 4-byte Folded Spill
; O0-NEXT:    bl __umoddi3
; O0-NEXT:    ldw r13, [r14 + 0] // 4-byte Folded Reload
; O0-NEXT:    add r14, 4
; O0-NEXT:    jmp r13
;
; O1-LABEL: urem64:
; O1:         .cfi_startproc
; O1-NEXT:  // %bb.0:
; O1-NEXT:    sub r14, 4
; O1-NEXT:    stw r13, [r14 + 0] // 4-byte Folded Spill
; O1-NEXT:    bl __umoddi3
; O1-NEXT:    ldw r13, [r14 + 0] // 4-byte Folded Reload
; O1-NEXT:    add r14, 4
; O1-NEXT:    jmp r13
  %r = urem i64 %a, %b
  ret i64 %r
}

define i64 @srem64(i64 %a, i64 %b) {
; O0-LABEL: srem64:
; O0:         .cfi_startproc
; O0-NEXT:  // %bb.1:
; O0-NEXT:    sub r14, 4
; O0-NEXT:    stw r13, [r14 + 0] // 4-byte Folded Spill
; O0-NEXT:    bl __moddi3
; O0-NEXT:    ldw r13, [r14 + 0] // 4-byte Folded Reload
; O0-NEXT:    add r14, 4
; O0-NEXT:    jmp r13
;
; O1-LABEL: srem64:
; O1:         .cfi_startproc
; O1-NEXT:  // %bb.0:
; O1-NEXT:    sub r14, 4
; O1-NEXT:    stw r13, [r14 + 0] // 4-byte Folded Spill
; O1-NEXT:    bl __moddi3
; O1-NEXT:    ldw r13, [r14 + 0] // 4-byte Folded Reload
; O1-NEXT:    add r14, 4
; O1-NEXT:    jmp r13
  %r = srem i64 %a, %b
  ret i64 %r
}

define i64 @mul64(i64 %a, i64 %b) {
; O0-LABEL: mul64:
; O0:         .cfi_startproc
; O0-NEXT:  // %bb.1:
; O0-NEXT:    sub r14, 4
; O0-NEXT:    stw r13, [r14 + 0] // 4-byte Folded Spill
; O0-NEXT:    bl __muldi3
; O0-NEXT:    ldw r13, [r14 + 0] // 4-byte Folded Reload
; O0-NEXT:    add r14, 4
; O0-NEXT:    jmp r13
;
; O1-LABEL: mul64:
; O1:         .cfi_startproc
; O1-NEXT:  // %bb.0:
; O1-NEXT:    sub r14, 4
; O1-NEXT:    stw r13, [r14 + 0] // 4-byte Folded Spill
; O1-NEXT:    bl __muldi3
; O1-NEXT:    ldw r13, [r14 + 0] // 4-byte Folded Reload
; O1-NEXT:    add r14, 4
; O1-NEXT:    jmp r13
  %r = mul i64 %a, %b
  ret i64 %r
}
