; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; Return a 64-bit constant — tests i64 splitting in the return CC.
define i64 @return_i64_const() {
; CHECK-LABEL: return_i64_const:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    lli r1, 42
; CHECK-NEXT:    mov r2, zero
; CHECK-NEXT:    jmp lr
  ret i64 42
}

; Return -1 as i64 (the pattern from libsa's null_seek).
define i64 @return_neg1() {
; CHECK-LABEL: return_neg1:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    llis r1, -1
; CHECK-NEXT:    llis r2, -1
; CHECK-NEXT:    jmp lr
  ret i64 -1
}

; Accept and return an i64 argument — tests both arg and return splitting.
define i64 @passthrough_i64(i64 %x) {
; CHECK-LABEL: passthrough_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    jmp lr
  ret i64 %x
}

; i64 argument with i32 return (truncation — keeps low half in R1).
define i32 @trunc_i64(i64 %x) {
; CHECK-LABEL: trunc_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    jmp lr
  %val = trunc i64 %x to i32
  ret i32 %val
}

; Extract high 32 bits — proves we pick R2 (high half) correctly.
define i32 @high_half(i64 %x) {
; CHECK-LABEL: high_half:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r1, r2
; CHECK-NEXT:    jmp lr
  %shifted = lshr i64 %x, 32
  %hi = trunc i64 %shifted to i32
  ret i32 %hi
}

; Bitwise AND on i64 — decomposes to independent per-half ops.
define i64 @and_i64(i64 %a, i64 %b) {
; CHECK-LABEL: and_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    and r1, r3
; CHECK-NEXT:    and r2, r4
; CHECK-NEXT:    jmp lr
  %r = and i64 %a, %b
  ret i64 %r
}

; i64 equality comparison — tests multi-word compare lowering.
define i1 @cmp_i64_eq(i64 %a, i64 %b) {
; CHECK-LABEL: cmp_i64_eq:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    xor r1, r3
; CHECK-NEXT:    xor r2, r4
; CHECK-NEXT:    or r1, r2
; CHECK-NEXT:    cmp zero, r1
; CHECK-NEXT:    mov r1, zero
; CHECK-NEXT:    adc r1, zero
; CHECK-NEXT:    jmp lr
  %cmp = icmp eq i64 %a, %b
  ret i1 %cmp
}

; Zero-extend i32 to i64 — low half is source, high half is zero.
define i64 @zext_i32_to_i64(i32 %x) {
; CHECK-LABEL: zext_i32_to_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r2, zero
; CHECK-NEXT:    jmp lr
  %ext = zext i32 %x to i64
  ret i64 %ext
}

; Sign-extend i32 to i64 — high half is arithmetic shift of sign bit.
define i64 @sext_i32_to_i64(i32 %x) {
; CHECK-LABEL: sext_i32_to_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r2, r1
; CHECK-NEXT:    sar r2, 31
; CHECK-NEXT:    jmp lr
  %ext = sext i32 %x to i64
  ret i64 %ext
}

; Mixed i32 + i64 args — i32 in R1, i64 in R2:R3.
define i64 @mixed_args(i32 %x, i64 %y) {
; CHECK-LABEL: mixed_args:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r1, r2
; CHECK-NEXT:    mov r2, r3
; CHECK-NEXT:    jmp lr
  ret i64 %y
}
