; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra-unknown-none -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; An icmp that becomes a value (rather than feeding a branch) is materialised
; branchlessly: a CMP sets SR.C, then ADC/SBC of zeros reads the flag into a 0/1
; GPR.  Unsigned predicates read the carry directly (operand swap folds the
; "greater" forms onto the "less" forms); eq/ne test the difference against zero;
; signed predicates fall back to the SELECT_CC branch form.

define i32 @ult(i32 %a, i32 %b) {
; CHECK-LABEL: ult:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    cmp r1, r2
; CHECK-NEXT:    mov r1, r0
; CHECK-NEXT:    sbc r1, r0
; CHECK-NEXT:    and r1, 1
; CHECK-NEXT:    and r1, 1
; CHECK-NEXT:    jmp r13
  %c = icmp ult i32 %a, %b
  %z = zext i1 %c to i32
  ret i32 %z
}

define i32 @uge(i32 %a, i32 %b) {
; CHECK-LABEL: uge:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    cmp r1, r2
; CHECK-NEXT:    mov r1, r0
; CHECK-NEXT:    adc r1, r0
; CHECK-NEXT:    and r1, 1
; CHECK-NEXT:    jmp r13
  %c = icmp uge i32 %a, %b
  %z = zext i1 %c to i32
  ret i32 %z
}

define i32 @ugt(i32 %a, i32 %b) {
; CHECK-LABEL: ugt:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    cmp r2, r1
; CHECK-NEXT:    mov r1, r0
; CHECK-NEXT:    sbc r1, r0
; CHECK-NEXT:    and r1, 1
; CHECK-NEXT:    and r1, 1
; CHECK-NEXT:    jmp r13
  %c = icmp ugt i32 %a, %b
  %z = zext i1 %c to i32
  ret i32 %z
}

define i32 @ule(i32 %a, i32 %b) {
; CHECK-LABEL: ule:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    cmp r2, r1
; CHECK-NEXT:    mov r1, r0
; CHECK-NEXT:    adc r1, r0
; CHECK-NEXT:    and r1, 1
; CHECK-NEXT:    jmp r13
  %c = icmp ule i32 %a, %b
  %z = zext i1 %c to i32
  ret i32 %z
}

define i32 @eq(i32 %a, i32 %b) {
; CHECK-LABEL: eq:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub r1, r2
; CHECK-NEXT:    cmp r0, r1
; CHECK-NEXT:    mov r1, r0
; CHECK-NEXT:    adc r1, r0
; CHECK-NEXT:    and r1, 1
; CHECK-NEXT:    jmp r13
  %c = icmp eq i32 %a, %b
  %z = zext i1 %c to i32
  ret i32 %z
}

define i32 @ne(i32 %a, i32 %b) {
; CHECK-LABEL: ne:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub r1, r2
; CHECK-NEXT:    cmp r0, r1
; CHECK-NEXT:    mov r1, r0
; CHECK-NEXT:    sbc r1, r0
; CHECK-NEXT:    and r1, 1
; CHECK-NEXT:    and r1, 1
; CHECK-NEXT:    jmp r13
  %c = icmp ne i32 %a, %b
  %z = zext i1 %c to i32
  ret i32 %z
}

define i32 @eqz(i32 %a) {
; CHECK-LABEL: eqz:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    cmp r0, r1
; CHECK-NEXT:    mov r1, r0
; CHECK-NEXT:    adc r1, r0
; CHECK-NEXT:    and r1, 1
; CHECK-NEXT:    jmp r13
  %c = icmp eq i32 %a, 0
  %z = zext i1 %c to i32
  ret i32 %z
}

define i32 @nez(i32 %a) {
; CHECK-LABEL: nez:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    cmp r0, r1
; CHECK-NEXT:    mov r1, r0
; CHECK-NEXT:    sbc r1, r0
; CHECK-NEXT:    and r1, 1
; CHECK-NEXT:    and r1, 1
; CHECK-NEXT:    jmp r13
  %c = icmp ne i32 %a, 0
  %z = zext i1 %c to i32
  ret i32 %z
}

; Signed compare to a value still uses the branch-based SELECT_CC form.
define i32 @slt(i32 %a, i32 %b) {
; CHECK-LABEL: slt:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r3, r1
; CHECK-NEXT:    lli r1, 1
; CHECK-NEXT:    lli r4, 0
; CHECK-NEXT:    cmp r3, r2
; CHECK-NEXT:    blt .LBB8_2
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    mov r1, r4
; CHECK-NEXT:  .LBB8_2:
; CHECK-NEXT:    and r1, 1
; CHECK-NEXT:    jmp r13
  %c = icmp slt i32 %a, %b
  %z = zext i1 %c to i32
  ret i32 %z
}
