; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; Register output constraint
define i32 @reg_output() {
; CHECK-LABEL: reg_output:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    //APP
; CHECK-NEXT:    mov r1, zero
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    jmp lr
  %val = call i32 asm "mov $0, r0", "=r"()
  ret i32 %val
}

; Register input constraint
define void @reg_input(i32 %val) {
; CHECK-LABEL: reg_input:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    //APP
; CHECK-NEXT:    test r1, r1
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    jmp lr
  call void asm sideeffect "test $0, $0", "r"(i32 %val)
  ret void
}

; Immediate constraint
define void @imm_input() {
; CHECK-LABEL: imm_input:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    //APP
; CHECK-NEXT:    add r1, 42
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    jmp lr
  call void asm sideeffect "add r1, $0", "i"(i32 42)
  ret void
}

; Condition code clobber — regalloc must preserve SR liveness
define void @cc_clobber(i32 %a) {
; CHECK-LABEL: cc_clobber:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    //APP
; CHECK-NEXT:    test r1, r1
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    jmp lr
  call void asm sideeffect "test $0, $0", "r,~{cc}"(i32 %a)
  ret void
}

; Memory clobber (compiler fence)
define void @memory_fence() {
; CHECK-LABEL: memory_fence:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    //APP
; CHECK-NEXT:    di
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    jmp lr
  call void asm sideeffect "di", "~{memory}"()
  ret void
}

; Input + output with separate registers
define i32 @input_output(i32 %in) {
; CHECK-LABEL: input_output:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    //APP
; CHECK-NEXT:    mov r1, r1
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    jmp lr
  %out = call i32 asm "mov $0, $1", "=r,r"(i32 %in)
  ret i32 %out
}
