; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; returnaddress(0) captures R13 at entry-block head so it survives
; intervening BL/JALR calls which otherwise overwrite the live LR
; with their own call-site return address.

declare ptr @llvm.returnaddress(i32)
declare void @ext_fn()

; Leaf: no intervening calls, but we still route through a captured
; vreg so the selector path is the same shape for both cases.
define ptr @ret_addr_leaf() {
; CHECK-LABEL: ret_addr_leaf:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r1, lr
; CHECK-NEXT:    mov r1, r1
; CHECK-NEXT:    jmp lr
  %r = call ptr @llvm.returnaddress(i32 0)
  ret ptr %r
}

; Non-leaf: the call to ext_fn() clobbers R13.  The captured value
; must be kept alive across the call (spill, CSR, whatever RegAlloc
; picks) and read back for the return, NOT re-read from live R13.
define ptr @ret_addr_nonleaf() {
; CHECK-LABEL: ret_addr_nonleaf:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 8
; CHECK-NEXT:    stw r5, [sp + 4] // 4-byte Folded Spill
; CHECK-NEXT:    stw lr, [sp + 0] // 4-byte Folded Spill
; CHECK-NEXT:    mov r5, lr
; CHECK-NEXT:    bl ext_fn
; CHECK-NEXT:    mov r1, r5
; CHECK-NEXT:    ldw lr, [sp + 0] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r5, [sp + 4] // 4-byte Folded Reload
; CHECK-NEXT:    add sp, 8
; CHECK-NEXT:    jmp lr
  call void @ext_fn()
  %r = call ptr @llvm.returnaddress(i32 0)
  ret ptr %r
}

; frameaddress(0) → MOV from SP (R14)
declare ptr @llvm.frameaddress(i32)
define ptr @frame_addr() {
; CHECK-LABEL: frame_addr:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r1, sp
; CHECK-NEXT:    jmp lr
  %r = call ptr @llvm.frameaddress(i32 0)
  ret ptr %r
}

; stacksave/stackrestore → MOV SP
declare ptr @llvm.stacksave()
declare void @llvm.stackrestore(ptr)
define void @stack_save_restore() {
; CHECK-LABEL: stack_save_restore:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r1, sp
; CHECK-NEXT:    mov sp, r1
; CHECK-NEXT:    jmp lr
  %sp = call ptr @llvm.stacksave()
  call void @llvm.stackrestore(ptr %sp)
  ret void
}
