; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; returnaddress(0) → MOV from LR (R13)
declare ptr @llvm.returnaddress(i32)
define ptr @ret_addr() {
; CHECK-LABEL: ret_addr:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    mov r1, r13
; CHECK-NEXT:    jmp r13
  %r = call ptr @llvm.returnaddress(i32 0)
  ret ptr %r
}

; frameaddress(0) → MOV from SP (R14)
declare ptr @llvm.frameaddress(i32)
define ptr @frame_addr() {
; CHECK-LABEL: frame_addr:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    mov r1, r14
; CHECK-NEXT:    jmp r13
  %r = call ptr @llvm.frameaddress(i32 0)
  ret ptr %r
}

; stacksave/stackrestore → MOV SP
declare ptr @llvm.stacksave()
declare void @llvm.stackrestore(ptr)
define void @stack_save_restore() {
; CHECK-LABEL: stack_save_restore:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    mov r1, r14
; CHECK-NEXT:    mov r14, r1
; CHECK-NEXT:    jmp r13
  %sp = call ptr @llvm.stacksave()
  call void @llvm.stackrestore(ptr %sp)
  ret void
}
