; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs -O2 < %s \
; RUN:   | FileCheck %s

; Two-pointer iteration loops (`*d++ = *s++`) must stay in pointer-bump
; form: each pointer PHI bumped by ADDi 1 directly, no shared integer
; induction variable that materialises `base + i` per iteration.
;
; Without `PenumbraTTIImpl::isLSRCostLess`, LSR's default tuple-compare
; sorts on `NumRegs` first and rewrites the loop into a single i32 IV
; plus two `add Rb, Ri` per iteration — saving one PHI register at the
; cost of two extra ADDs every iteration, which is always a worse trade
; on Penumbra (12 free GPRs, no scaled addressing mode).
;
; Our override makes `Insns` the primary sort key (PowerPC pattern), so
; LSR keeps the natural form: two pointer PHIs, two ADDi 1 in the inner
; loop, no per-use base-add.  The remaining 2 trailing MOVs are tracked
; separately in doc/TODO.md (back-edge coalescing).

define ptr @strcpy_pointer_bump(ptr noundef returned writeonly captures(ret: address, provenance) %0, ptr noundef readonly captures(none) %1) {
; CHECK-LABEL: strcpy_pointer_bump:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov r11, r1
; CHECK-NEXT:    mov r3, r2
; CHECK-NEXT:    mov r4, r11
; CHECK-NEXT:  .LBB0_1: // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    add r3, 1
; CHECK-NEXT:    ldb r2, [r2 + 0]
; CHECK-NEXT:    add r4, 1
; CHECK-NEXT:    stb r2, [r11 + 0]
; CHECK-NEXT:    cmp r2, 0
; CHECK-NEXT:    mov r2, r3
; CHECK-NEXT:    mov r11, r4
; CHECK-NEXT:    bne .LBB0_1
; CHECK-NEXT:  // %bb.2:
; CHECK-NEXT:    jmp r13
  br label %3

3:
  %4 = phi ptr [ %1, %2 ], [ %6, %3 ]
  %5 = phi ptr [ %0, %2 ], [ %8, %3 ]
  %6 = getelementptr inbounds nuw i8, ptr %4, i32 1
  %7 = load i8, ptr %4, align 1
  %8 = getelementptr inbounds nuw i8, ptr %5, i32 1
  store i8 %7, ptr %5, align 1
  %9 = icmp eq i8 %7, 0
  br i1 %9, label %10, label %3

10:
  ret ptr %0
}
