; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs -O2 < %s \
; RUN:   | FileCheck %s

; Two-pointer iteration loops (`*d++ = *s++`) must compile to the ideal
; 6-instruction inner loop: load, post-bump source, store, post-bump dest,
; flag-test on the loaded byte, conditional branch.  No base+index
; rewrite, no trailing register-to-register MOVs at the back-edge.
;
; This test catches regressions in two cooperating fixes:
;
; 1. `PenumbraTTIImpl::isLSRCostLess` makes `Insns` the primary LSR sort
;    key — without it, LSR rewrites the natural pointer-bump form into a
;    single integer IV plus two `add Rb, Ri` per iteration (8 → 9 instr).
;
; 2. `penumbra_sink_ptr_add_past_use` post-legalizer combine sinks
;    `G_PTR_ADD %new, %old, K` past the immediately-following memory op
;    that reads `%old`.  Penumbra's destructive 2-operand `add Rd, 1`
;    needs the source register to die before its def — without the sink,
;    twoaddress inserts a COPY that the coalescer can't eliminate, and
;    we end up with a trailing MOV per pointer per iteration (6 → 8
;    instr).

define ptr @strcpy_pointer_bump(ptr noundef returned writeonly captures(ret: address, provenance) %0, ptr noundef readonly captures(none) %1) {
; CHECK-LABEL: strcpy_pointer_bump:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r3, r1
; CHECK-NEXT:  .LBB0_1: // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ldb r4, [r2 + 0]
; CHECK-NEXT:    add r2, 1
; CHECK-NEXT:    stb r4, [r3 + 0]
; CHECK-NEXT:    add r3, 1
; CHECK-NEXT:    cmp r4, 0
; CHECK-NEXT:    bne .LBB0_1
; CHECK-NEXT:  // %bb.2:
; CHECK-NEXT:    jmp lr
  br label %3

3:
  %4 = phi ptr [ %1, %2 ], [ %6, %3 ]
  %5 = phi ptr [ %0, %2 ], [ %8, %3 ]
  %6 = getelementptr inbounds nuw i8, ptr %4, i32 1
  %7 = load i8, ptr %4, align 1
  %8 = getelementptr inbounds nuw i8, ptr %5, i32 1
  store i8 %7, ptr %5, align 1
  %9 = icmp eq i8 %7, 0
  br i1 %9, label %10, label %3

10:
  ret ptr %0
}
