; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

declare i32 @llvm.umin.i32(i32, i32)
define i32 @umin_i32(i32 %a, i32 %b) {
; CHECK-LABEL: umin_i32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    cmp r1, r2
; CHECK-NEXT:    bcc .LBB0_2
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    mov r1, r2
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    jmp lr
  %r = call i32 @llvm.umin.i32(i32 %a, i32 %b)
  ret i32 %r
}

declare i32 @llvm.umax.i32(i32, i32)
define i32 @umax_i32(i32 %a, i32 %b) {
; CHECK-LABEL: umax_i32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    cmp r1, r2
; CHECK-NEXT:    bhi .LBB1_2
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    mov r1, r2
; CHECK-NEXT:  .LBB1_2:
; CHECK-NEXT:    jmp lr
  %r = call i32 @llvm.umax.i32(i32 %a, i32 %b)
  ret i32 %r
}

declare i32 @llvm.smin.i32(i32, i32)
define i32 @smin_i32(i32 %a, i32 %b) {
; CHECK-LABEL: smin_i32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    cmp r1, r2
; CHECK-NEXT:    blt .LBB2_2
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    mov r1, r2
; CHECK-NEXT:  .LBB2_2:
; CHECK-NEXT:    jmp lr
  %r = call i32 @llvm.smin.i32(i32 %a, i32 %b)
  ret i32 %r
}

declare i32 @llvm.smax.i32(i32, i32)
define i32 @smax_i32(i32 %a, i32 %b) {
; CHECK-LABEL: smax_i32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    cmp r1, r2
; CHECK-NEXT:    bgt .LBB3_2
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    mov r1, r2
; CHECK-NEXT:  .LBB3_2:
; CHECK-NEXT:    jmp lr
  %r = call i32 @llvm.smax.i32(i32 %a, i32 %b)
  ret i32 %r
}
