; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; G_SMAX/G_SMIN/G_UMAX/G_UMIN for s64 should be clamped to s32
; (narrowed by the framework), then lowered to icmp + select.

declare i64 @llvm.smax.i64(i64, i64)
define i64 @smax_i64(i64 %a, i64 %b) {
; CHECK-LABEL: smax_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 8
; CHECK-NEXT:    stw r5, [sp + 4] // 4-byte Folded Spill
; CHECK-NEXT:    stw lr, [sp + 0] // 4-byte Folded Spill
; CHECK-NEXT:    cmp r3, r1
; CHECK-NEXT:    mov r11, zero
; CHECK-NEXT:    sbc r11, zero
; CHECK-NEXT:    and r11, 1
; CHECK-NEXT:    lli lr, 1
; CHECK-NEXT:    lli r5, 0
; CHECK-NEXT:    cmp r2, r4
; CHECK-NEXT:    ble .LBB0_1
; CHECK-NEXT:  // %bb.2:
; CHECK-NEXT:    cmp r2, r4
; CHECK-NEXT:    bne .LBB0_3
; CHECK-NEXT:  .LBB0_4:
; CHECK-NEXT:    test r11, 1
; CHECK-NEXT:    beq .LBB0_5
; CHECK-NEXT:  .LBB0_6:
; CHECK-NEXT:    test r11, 1
; CHECK-NEXT:    bne .LBB0_8
; CHECK-NEXT:  .LBB0_7:
; CHECK-NEXT:    mov r2, r4
; CHECK-NEXT:  .LBB0_8:
; CHECK-NEXT:    ldw lr, [sp + 0] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r5, [sp + 4] // 4-byte Folded Reload
; CHECK-NEXT:    add sp, 8
; CHECK-NEXT:    jmp lr
; CHECK-NEXT:  .LBB0_1:
; CHECK-NEXT:    mov lr, r5
; CHECK-NEXT:    cmp r2, r4
; CHECK-NEXT:    beq .LBB0_4
; CHECK-NEXT:  .LBB0_3:
; CHECK-NEXT:    mov r11, lr
; CHECK-NEXT:    test r11, 1
; CHECK-NEXT:    bne .LBB0_6
; CHECK-NEXT:  .LBB0_5:
; CHECK-NEXT:    mov r1, r3
; CHECK-NEXT:    test r11, 1
; CHECK-NEXT:    beq .LBB0_7
; CHECK-NEXT:    b .LBB0_8
  %r = call i64 @llvm.smax.i64(i64 %a, i64 %b)
  ret i64 %r
}

declare i64 @llvm.umin.i64(i64, i64)
define i64 @umin_i64(i64 %a, i64 %b) {
; CHECK-LABEL: umin_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 4
; CHECK-NEXT:    stw lr, [sp + 0] // 4-byte Folded Spill
; CHECK-NEXT:    cmp r1, r3
; CHECK-NEXT:    mov lr, zero
; CHECK-NEXT:    mov r11, lr
; CHECK-NEXT:    sbc r11, zero
; CHECK-NEXT:    and r11, 1
; CHECK-NEXT:    cmp r2, r4
; CHECK-NEXT:    sbc lr, zero
; CHECK-NEXT:    and lr, 1
; CHECK-NEXT:    cmp r2, r4
; CHECK-NEXT:    bne .LBB1_1
; CHECK-NEXT:  // %bb.2:
; CHECK-NEXT:    test r11, 1
; CHECK-NEXT:    beq .LBB1_3
; CHECK-NEXT:  .LBB1_4:
; CHECK-NEXT:    test r11, 1
; CHECK-NEXT:    bne .LBB1_6
; CHECK-NEXT:  .LBB1_5:
; CHECK-NEXT:    mov r2, r4
; CHECK-NEXT:  .LBB1_6:
; CHECK-NEXT:    ldw lr, [sp + 0] // 4-byte Folded Reload
; CHECK-NEXT:    add sp, 4
; CHECK-NEXT:    jmp lr
; CHECK-NEXT:  .LBB1_1:
; CHECK-NEXT:    mov r11, lr
; CHECK-NEXT:    test r11, 1
; CHECK-NEXT:    bne .LBB1_4
; CHECK-NEXT:  .LBB1_3:
; CHECK-NEXT:    mov r1, r3
; CHECK-NEXT:    test r11, 1
; CHECK-NEXT:    beq .LBB1_5
; CHECK-NEXT:    b .LBB1_6
  %r = call i64 @llvm.umin.i64(i64 %a, i64 %b)
  ret i64 %r
}
