; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; G_SMAX/G_SMIN/G_UMAX/G_UMIN for s64 should be clamped to s32
; (narrowed by the framework), then lowered to icmp + select.

declare i64 @llvm.smax.i64(i64, i64)
define i64 @smax_i64(i64 %a, i64 %b) {
; CHECK-LABEL: smax_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub r14, 8
; CHECK-NEXT:    stw r5, [r14 + 4] // 4-byte Folded Spill
; CHECK-NEXT:    stw r13, [r14 + 0] // 4-byte Folded Spill
; CHECK-NEXT:    lli r11, 1
; CHECK-NEXT:    lli r13, 0
; CHECK-NEXT:    cmp r1, r3
; CHECK-NEXT:    bhi .LBB0_2
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    mov r11, r13
; CHECK-NEXT:    b .LBB0_2
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    lli r13, 1
; CHECK-NEXT:    lli r5, 0
; CHECK-NEXT:    cmp r2, r4
; CHECK-NEXT:    bgt .LBB0_4
; CHECK-NEXT:  // %bb.3:
; CHECK-NEXT:    mov r13, r5
; CHECK-NEXT:    b .LBB0_4
; CHECK-NEXT:  .LBB0_4:
; CHECK-NEXT:    cmp r2, r4
; CHECK-NEXT:    beq .LBB0_6
; CHECK-NEXT:  // %bb.5:
; CHECK-NEXT:    mov r11, r13
; CHECK-NEXT:    b .LBB0_6
; CHECK-NEXT:  .LBB0_6:
; CHECK-NEXT:    test r11, r11
; CHECK-NEXT:    bne .LBB0_8
; CHECK-NEXT:  // %bb.7:
; CHECK-NEXT:    mov r1, r3
; CHECK-NEXT:    b .LBB0_8
; CHECK-NEXT:  .LBB0_8:
; CHECK-NEXT:    test r11, r11
; CHECK-NEXT:    bne .LBB0_10
; CHECK-NEXT:  // %bb.9:
; CHECK-NEXT:    mov r2, r4
; CHECK-NEXT:    b .LBB0_10
; CHECK-NEXT:  .LBB0_10:
; CHECK-NEXT:    ldw r13, [r14 + 0] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r5, [r14 + 4] // 4-byte Folded Reload
; CHECK-NEXT:    add r14, 8
; CHECK-NEXT:    jmp r13
  %r = call i64 @llvm.smax.i64(i64 %a, i64 %b)
  ret i64 %r
}

declare i64 @llvm.umin.i64(i64, i64)
define i64 @umin_i64(i64 %a, i64 %b) {
; CHECK-LABEL: umin_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub r14, 8
; CHECK-NEXT:    stw r5, [r14 + 4] // 4-byte Folded Spill
; CHECK-NEXT:    stw r13, [r14 + 0] // 4-byte Folded Spill
; CHECK-NEXT:    lli r11, 1
; CHECK-NEXT:    lli r13, 0
; CHECK-NEXT:    cmp r1, r3
; CHECK-NEXT:    bcc .LBB1_2
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    mov r11, r13
; CHECK-NEXT:    b .LBB1_2
; CHECK-NEXT:  .LBB1_2:
; CHECK-NEXT:    lli r13, 1
; CHECK-NEXT:    lli r5, 0
; CHECK-NEXT:    cmp r2, r4
; CHECK-NEXT:    bcc .LBB1_4
; CHECK-NEXT:  // %bb.3:
; CHECK-NEXT:    mov r13, r5
; CHECK-NEXT:    b .LBB1_4
; CHECK-NEXT:  .LBB1_4:
; CHECK-NEXT:    cmp r2, r4
; CHECK-NEXT:    beq .LBB1_6
; CHECK-NEXT:  // %bb.5:
; CHECK-NEXT:    mov r11, r13
; CHECK-NEXT:    b .LBB1_6
; CHECK-NEXT:  .LBB1_6:
; CHECK-NEXT:    test r11, r11
; CHECK-NEXT:    bne .LBB1_8
; CHECK-NEXT:  // %bb.7:
; CHECK-NEXT:    mov r1, r3
; CHECK-NEXT:    b .LBB1_8
; CHECK-NEXT:  .LBB1_8:
; CHECK-NEXT:    test r11, r11
; CHECK-NEXT:    bne .LBB1_10
; CHECK-NEXT:  // %bb.9:
; CHECK-NEXT:    mov r2, r4
; CHECK-NEXT:    b .LBB1_10
; CHECK-NEXT:  .LBB1_10:
; CHECK-NEXT:    ldw r13, [r14 + 0] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r5, [r14 + 4] // 4-byte Folded Reload
; CHECK-NEXT:    add r14, 8
; CHECK-NEXT:    jmp r13
  %r = call i64 @llvm.umin.i64(i64 %a, i64 %b)
  ret i64 %r
}
