; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; SCEV rewrites `for (i = 0; i < m; i++) s += i` into the closed form
; `(m-1)*(m-2)/2 + m - 1`, using i33 to hold the multiply without
; overflow.  Non-power-of-2 widths legalize by widening to the next
; pow2 (s33 -> s64), which drops us into the s64 __muldi3 libcall path.
define i32 @inst_check_f(i32 %m) {
; CHECK-LABEL: inst_check_f:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub r14, 8
; CHECK-NEXT:    stw r5, [r14 + 4] // 4-byte Folded Spill
; CHECK-NEXT:    stw r13, [r14 + 0] // 4-byte Folded Spill
; CHECK-NEXT:    mov r2, r0
; CHECK-NEXT:    cmp r1, 0
; CHECK-NEXT:    ble .LBB0_2
; CHECK-NEXT:  // %bb.1: // %loop
; CHECK-NEXT:    mov r2, r1
; CHECK-NEXT:    sub r2, 1
; CHECK-NEXT:    mov r3, r1
; CHECK-NEXT:    sub r3, 2
; CHECK-NEXT:    mov r4, r0
; CHECK-NEXT:    mov r5, r1
; CHECK-NEXT:    mov r1, r2
; CHECK-NEXT:    mov r2, r4
; CHECK-NEXT:    bl __muldi3
; CHECK-NEXT:    llis r3, -1
; CHECK-NEXT:    and r1, r3
; CHECK-NEXT:    and r2, 1
; CHECK-NEXT:    shr r1, 1
; CHECK-NEXT:    shl r2, 31
; CHECK-NEXT:    or r1, r2
; CHECK-NEXT:    add r5, r1
; CHECK-NEXT:    sub r5, 1
; CHECK-NEXT:    mov r2, r5
; CHECK-NEXT:  .LBB0_2: // %done
; CHECK-NEXT:    mov r1, r2
; CHECK-NEXT:    ldw r13, [r14 + 0] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r5, [r14 + 4] // 4-byte Folded Reload
; CHECK-NEXT:    add r14, 8
; CHECK-NEXT:    jmp r13
  %ismt0 = icmp sgt i32 %m, 0
  br i1 %ismt0, label %loop, label %done

loop:
  %m1 = add nsw i32 %m, -1
  %m1_33 = zext i32 %m1 to i33
  %m2 = add nsw i32 %m, -2
  %m2_33 = zext i32 %m2 to i33
  %prod = mul i33 %m1_33, %m2_33
  %half = lshr i33 %prod, 1
  %half32 = trunc i33 %half to i32
  %r0 = add i32 %m, %half32
  %r = add i32 %r0, -1
  br label %done

done:
  %ret = phi i32 [ 0, %0 ], [ %r, %loop ]
  ret i32 %ret
}
