; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; The divmul unit produces both halves of a 32x32 product in one operation,
; so a widening multiply must issue a single MUL_P / MULU_P rather than a
; separate multiply per half.  A redundant divmul operation is pure cost in
; the fixed-point and bignum inner loops that dominate these workloads.

define i64 @umul_widen(i32 %a, i32 %b) {
; CHECK-LABEL: umul_widen:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mulu r1, r2, r2
; CHECK-NEXT:    jmp lr
  %za = zext i32 %a to i64
  %zb = zext i32 %b to i64
  %m = mul i64 %za, %zb
  ret i64 %m
}

define i64 @smul_widen(i32 %a, i32 %b) {
; CHECK-LABEL: smul_widen:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mul r1, r2, r2
; CHECK-NEXT:    jmp lr
  %sa = sext i32 %a to i64
  %sb = sext i32 %b to i64
  %m = mul i64 %sa, %sb
  ret i64 %m
}

; Q4.28 fixed-point multiply — the fractal demos' inner-loop shape.  The
; 64-bit product is realigned by a shift pair, so both halves are live and
; exactly one multiply must appear.
define i32 @qmul(i32 %a, i32 %b) {
; CHECK-LABEL: qmul:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mul r1, r2, r2
; CHECK-NEXT:    shr r1, 28
; CHECK-NEXT:    shl r2, 4
; CHECK-NEXT:    or r1, r2
; CHECK-NEXT:    jmp lr
  %sa = sext i32 %a to i64
  %sb = sext i32 %b to i64
  %m = mul i64 %sa, %sb
  %s = ashr i64 %m, 28
  %t = trunc i64 %s to i32
  ret i32 %t
}

; Only the high half is used: still one multiply, low half dead.
define i32 @hi_half_only(i32 %a, i32 %b) {
; CHECK-LABEL: hi_half_only:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mulu r1, r2, r2
; CHECK-NEXT:    mov r1, r2
; CHECK-NEXT:    jmp lr
  %za = zext i32 %a to i64
  %zb = zext i32 %b to i64
  %m = mul i64 %za, %zb
  %s = lshr i64 %m, 32
  %t = trunc i64 %s to i32
  ret i32 %t
}

; Only the low half is used: the plain two-operand form, no pair register.
define i32 @lo_half_only(i32 %a, i32 %b) {
; CHECK-LABEL: lo_half_only:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mul r1, r2
; CHECK-NEXT:    jmp lr
  %m = mul i32 %a, %b
  ret i32 %m
}
