; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra -global-isel -O1 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; 32-bit multiply selects to the hardware MUL (low half).  A 64-bit multiply —
; including a 32x32->64 widening multiply from sign/zero-extended operands —
; expands inline to s32 partial products on the hardware MUL/MULU (G_UMULH ->
; MULU_P for the high word) rather than a __muldi3 libcall.  Power-of-2 constants
; stay strength-reduced to shifts rather than paying for a ~34-cycle multiply.

define i32 @mul_rr(i32 %a, i32 %b) {
; CHECK-LABEL: mul_rr:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mul r1, r2
; CHECK-NEXT:    jmp lr
  %r = mul i32 %a, %b
  ret i32 %r
}

define i32 @mul_pow2(i32 %a) {
; CHECK-LABEL: mul_pow2:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    shl r1, 4
; CHECK-NEXT:    jmp lr
  %r = mul i32 %a, 16
  ret i32 %r
}

define i64 @mul_i64(i64 %a, i64 %b) {
; CHECK-LABEL: mul_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 4
; CHECK-NEXT:    stw r5, [sp + 0] // 4-byte Folded Spill
; CHECK-NEXT:    mov r11, r1
; CHECK-NEXT:    mulu r11, r3, r5
; CHECK-NEXT:    mul r2, r3
; CHECK-NEXT:    mul r1, r4
; CHECK-NEXT:    add r2, r1
; CHECK-NEXT:    add r2, r5
; CHECK-NEXT:    mov r1, r11
; CHECK-NEXT:    ldw r5, [sp + 0] // 4-byte Folded Reload
; CHECK-NEXT:    add sp, 4
; CHECK-NEXT:    jmp lr
  %r = mul i64 %a, %b
  ret i64 %r
}

; 32x32->64 signed widening multiply (the mandelbrot fixed-point qmul shape):
; expands to hardware partial products, no __muldi3.
define i64 @smul_widen(i32 %a, i32 %b) {
; CHECK-LABEL: smul_widen:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mul r1, r2, r2
; CHECK-NEXT:    jmp lr
  %sa = sext i32 %a to i64
  %sb = sext i32 %b to i64
  %r = mul i64 %sa, %sb
  ret i64 %r
}

; 32x32->64 unsigned widening multiply: the zero high words fold away, leaving
; the hardware partial products (G_UMULH -> MULU_P for the high word).
define i64 @umul_widen(i32 %a, i32 %b) {
; CHECK-LABEL: umul_widen:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mulu r1, r2, r2
; CHECK-NEXT:    jmp lr
  %za = zext i32 %a to i64
  %zb = zext i32 %b to i64
  %r = mul i64 %za, %zb
  ret i64 %r
}

; Signed i32 multiply-with-overflow lowers through G_SMULH, the one path that
; selects the signed MUL_P pair form (its high half drives the overflow check).
declare {i32, i1} @llvm.smul.with.overflow.i32(i32, i32)
define i32 @smulo_i32(i32 %a, i32 %b, ptr %ov) {
; CHECK-LABEL: smulo_i32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mul r1, r2, r2
; CHECK-NEXT:    mov r4, r1
; CHECK-NEXT:    sar r4, 31
; CHECK-NEXT:    sub r2, r4
; CHECK-NEXT:    cmp zero, r2
; CHECK-NEXT:    mov r2, zero
; CHECK-NEXT:    sbc r2, zero
; CHECK-NEXT:    and r2, 1
; CHECK-NEXT:    stb r2, [r3 + 0]
; CHECK-NEXT:    jmp lr
  %r = call {i32, i1} @llvm.smul.with.overflow.i32(i32 %a, i32 %b)
  %v = extractvalue {i32, i1} %r, 0
  %o = extractvalue {i32, i1} %r, 1
  %oz = zext i1 %o to i8
  store i8 %oz, ptr %ov
  ret i32 %v
}
