; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s | FileCheck %s

; A value pinned in R12 (curlwp) and read at several points across calls must
; coalesce to a per-use `mov rN, r12` — the read is rematerialised at each use
; rather than parked in a callee-saved register and spilled.  This works only
; because R12 is a *member* of the i32 value register class (held out of
; allocation by getReservedRegs); if R12 were dropped from the class, the
; coalescer could not substitute it and this would spill a callee-saved reg.
; Regression guard for PenumbraRegisterInfo.td's GPR_Allocatable membership.

define void @curlwp_across_calls() {
; CHECK-LABEL: curlwp_across_calls:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 4
; CHECK-NEXT:    stw lr, [sp + 0] // 4-byte Folded Spill
; CHECK-NEXT:    mov r1, tp
; CHECK-NEXT:    bl use
; CHECK-NEXT:    mov r1, tp
; CHECK-NEXT:    bl use
; CHECK-NEXT:    mov r1, tp
; CHECK-NEXT:    bl use
; CHECK-NEXT:    ldw lr, [sp + 0] // 4-byte Folded Reload
; CHECK-NEXT:    add sp, 4
; CHECK-NEXT:    jmp lr
  %a = call i32 @llvm.read_register.i32(metadata !0)
  call void @use(i32 %a)
  %b = call i32 @llvm.read_register.i32(metadata !0)
  call void @use(i32 %b)
  %c = call i32 @llvm.read_register.i32(metadata !0)
  call void @use(i32 %c)
  ret void
}

; Reading curlwp->field across a call: the load uses R12 directly as a base
; after the call, with no spill of the pointer.
define i32 @curlwp_field_after_call(i32 %off) {
; CHECK-LABEL: curlwp_field_after_call:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 4
; CHECK-NEXT:    stw lr, [sp + 0] // 4-byte Folded Spill
; CHECK-NEXT:    bl barrier
; CHECK-NEXT:    ldw r1, [tp + 8]
; CHECK-NEXT:    ldw lr, [sp + 0] // 4-byte Folded Reload
; CHECK-NEXT:    add sp, 4
; CHECK-NEXT:    jmp lr
  %l = call i32 @llvm.read_register.i32(metadata !0)
  call void @barrier()
  %p = inttoptr i32 %l to ptr
  %f = getelementptr i8, ptr %p, i32 8
  %v = load i32, ptr %f
  ret i32 %v
}

declare void @use(i32)
declare void @barrier()
declare i32 @llvm.read_register.i32(metadata)

!0 = !{!"r12"}
