; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s | FileCheck %s

; A named global register variable (`register T x __asm("r12")`) pins a value
; in a reserved register.  The kernel uses this to keep curlwp in R12 (the
; thread pointer).  Reads/writes lower to a plain register move, and the
; canonical name and its ABI alias must resolve to the same register.

define i32 @read_curlwp_r12() {
; CHECK-LABEL: read_curlwp_r12:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r1, tp
; CHECK-NEXT:    jmp lr
  %v = call i32 @llvm.read_register.i32(metadata !0)
  ret i32 %v
}

define i32 @read_curlwp_tp() {
; CHECK-LABEL: read_curlwp_tp:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r1, tp
; CHECK-NEXT:    jmp lr
  %v = call i32 @llvm.read_register.i32(metadata !1)
  ret i32 %v
}

define void @set_curlwp_tp(i32 %l) {
; CHECK-LABEL: set_curlwp_tp:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov tp, r1
; CHECK-NEXT:    jmp lr
  call void @llvm.write_register.i32(metadata !1, i32 %l)
  ret void
}

declare i32 @llvm.read_register.i32(metadata)
declare void @llvm.write_register.i32(metadata, i32)

!0 = !{!"r12"}
!1 = !{!"tp"}
