; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; Outgoing arguments that overflow R1-R4 onto the stack must store
; word-wide.  The call frame is anchored at the Align(4) SP and every
; slot is a 4-aligned CCAssignToStack<4,4> slot, so each store is a
; single stw.  A regression in the outgoing store alignment (e.g. an
; Align(1) memory operand) would expand each slot into the unaligned
; byte-store sequence (four stb + shifts per word); these checks catch
; that by pinning the stw form.

declare void @take6(i32, i32, i32, i32, i32, i32)
declare void @take_ll(i32, i32, i32, i32, i64)

; The 5th and 6th i32 arguments land in stack slots [r14+0] and [r14+4].
define void @call6() {
; CHECK-LABEL: call6:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 12
; CHECK-NEXT:    stw lr, [sp + 8] // 4-byte Folded Spill
; CHECK-NEXT:    mov r1, sp
; CHECK-NEXT:    lli r2, 5
; CHECK-NEXT:    stw r2, [r1 + 0]
; CHECK-NEXT:    lli r2, 6
; CHECK-NEXT:    stw r2, [r1 + 4]
; CHECK-NEXT:    lli r1, 1
; CHECK-NEXT:    lli r2, 2
; CHECK-NEXT:    lli r3, 3
; CHECK-NEXT:    lli r4, 4
; CHECK-NEXT:    bl take6
; CHECK-NEXT:    ldw lr, [sp + 8] // 4-byte Folded Reload
; CHECK-NEXT:    add sp, 12
; CHECK-NEXT:    jmp lr
  call void @take6(i32 1, i32 2, i32 3, i32 4, i32 5, i32 6)
  ret void
}

; A stack-passed i64 splits into two i32 slots, each a single stw.
define void @call_ll(i64 %v) {
; CHECK-LABEL: call_ll:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 12
; CHECK-NEXT:    stw lr, [sp + 8] // 4-byte Folded Spill
; CHECK-NEXT:    mov r3, sp
; CHECK-NEXT:    stw r1, [r3 + 0]
; CHECK-NEXT:    stw r2, [r3 + 4]
; CHECK-NEXT:    lli r1, 1
; CHECK-NEXT:    lli r2, 2
; CHECK-NEXT:    lli r3, 3
; CHECK-NEXT:    lli r4, 4
; CHECK-NEXT:    bl take_ll
; CHECK-NEXT:    ldw lr, [sp + 8] // 4-byte Folded Reload
; CHECK-NEXT:    add sp, 12
; CHECK-NEXT:    jmp lr
  call void @take_ll(i32 1, i32 2, i32 3, i32 4, i64 %v)
  ret void
}
