; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra -global-isel -O0 -relocation-model=pic \
; RUN:   -verify-machineinstrs < %s | FileCheck %s -check-prefix=PIC
; RUN: llc -mtriple=penumbra -global-isel -O0 -relocation-model=static \
; RUN:   -verify-machineinstrs < %s | FileCheck %s -check-prefix=STATIC

; PIC vs static global address materialization.
; In the PIC model, a *preemptible* global (default visibility) uses
; GOT-indirect: LLI/LUI got_pcrel + ADD Rd, PC + LDW from GOT.  A
; *non-preemptible* global (dso_local) uses PC-relative-direct: the same
; LLI/LUI + ADD Rd, PC anchor but with %pcrel relocations, so the ADD
; already yields &sym and there is no GOT load.
; The ADD's own PC is the anchor; LLI/LUI carry -8/-4 addends so the
; linker's sym + addend - fixup_addr formula yields (GOT[sym] or sym) - Q
; at each half.  Static uses absolute LLI+LUI.

@myvar = global i32 42
@pievar = dso_local global i32 99

define ptr @get_address() {
; PIC-LABEL: get_address:
; PIC:         .cfi_startproc
; PIC-NEXT:  // %bb.1:
; PIC-NEXT:    lli r1, %got_pcrel_lo16(myvar-.LPC0_0)
; PIC-NEXT:    lui r1, %got_pcrel_hi16(myvar-.LPC0_0)
; PIC-NEXT:  .LPC0_0:
; PIC-NEXT:    add r1, pc
; PIC-NEXT:    ldw r1, [r1 + 0]
; PIC-NEXT:    jmp lr
;
; STATIC-LABEL: get_address:
; STATIC:         .cfi_startproc
; STATIC-NEXT:  // %bb.1:
; STATIC-NEXT:    lli r1, %lo16(myvar)
; STATIC-NEXT:    lui r1, %hi16(myvar)
; STATIC-NEXT:    jmp lr
  ret ptr @myvar
}

define i32 @load_global() {
; PIC-LABEL: load_global:
; PIC:         .cfi_startproc
; PIC-NEXT:  // %bb.1:
; PIC-NEXT:    lli r1, %got_pcrel_lo16(myvar-.LPC1_0)
; PIC-NEXT:    lui r1, %got_pcrel_hi16(myvar-.LPC1_0)
; PIC-NEXT:  .LPC1_0:
; PIC-NEXT:    add r1, pc
; PIC-NEXT:    ldw r1, [r1 + 0]
; PIC-NEXT:    ldw r1, [r1 + 0]
; PIC-NEXT:    jmp lr
;
; STATIC-LABEL: load_global:
; STATIC:         .cfi_startproc
; STATIC-NEXT:  // %bb.1:
; STATIC-NEXT:    lli r1, %lo16(myvar)
; STATIC-NEXT:    lui r1, %hi16(myvar)
; STATIC-NEXT:    ldw r1, [r1 + 0]
; STATIC-NEXT:    jmp lr
  %v = load i32, ptr @myvar
  ret i32 %v
}

define void @store_global(i32 %v) {
; PIC-LABEL: store_global:
; PIC:         .cfi_startproc
; PIC-NEXT:  // %bb.1:
; PIC-NEXT:    lli r2, %got_pcrel_lo16(myvar-.LPC2_0)
; PIC-NEXT:    lui r2, %got_pcrel_hi16(myvar-.LPC2_0)
; PIC-NEXT:  .LPC2_0:
; PIC-NEXT:    add r2, pc
; PIC-NEXT:    ldw r2, [r2 + 0]
; PIC-NEXT:    stw r1, [r2 + 0]
; PIC-NEXT:    jmp lr
;
; STATIC-LABEL: store_global:
; STATIC:         .cfi_startproc
; STATIC-NEXT:  // %bb.1:
; STATIC-NEXT:    lli r2, %lo16(myvar)
; STATIC-NEXT:    lui r2, %hi16(myvar)
; STATIC-NEXT:    stw r1, [r2 + 0]
; STATIC-NEXT:    jmp lr
  store i32 %v, ptr @myvar
  ret void
}

; PIE test: a dso_local global is non-preemptible, so the PIC model uses
; PC-relative-direct (%pcrel) — no GOT slot, no GOT load, no startup reloc.
define dso_local ptr @get_pie_address() {
; PIC-LABEL: get_pie_address:
; PIC:       .Lget_pie_address$local:
; PIC-NEXT:    .type .Lget_pie_address$local,@function
; PIC-NEXT:    .cfi_startproc
; PIC-NEXT:  // %bb.1:
; PIC-NEXT:    lli r1, %pcrel_lo16(pievar-.LPC3_0)
; PIC-NEXT:    lui r1, %pcrel_hi16(pievar-.LPC3_0)
; PIC-NEXT:  .LPC3_0:
; PIC-NEXT:    add r1, pc
; PIC-NEXT:    jmp lr
;
; STATIC-LABEL: get_pie_address:
; STATIC:         .cfi_startproc
; STATIC-NEXT:  // %bb.1:
; STATIC-NEXT:    lli r1, %lo16(pievar)
; STATIC-NEXT:    lui r1, %hi16(pievar)
; STATIC-NEXT:    jmp lr
  ret ptr @pievar
}
