; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra -global-isel -O0 -relocation-model=pic \
; RUN:   -verify-machineinstrs < %s | FileCheck %s -check-prefix=PIC
; RUN: llc -mtriple=penumbra -global-isel -O0 -relocation-model=static \
; RUN:   -verify-machineinstrs < %s | FileCheck %s -check-prefix=STATIC

; PIC vs static global address materialization.

@myvar = global i32 42

define ptr @get_address() {
; PIC-LABEL: get_address:
; PIC:         .cfi_startproc
; PIC-NEXT:  // %bb.1:
; PIC-NEXT:    mov r1, r15
; PIC-NEXT:    add r1, %pcrel(myvar+4)
; PIC-NEXT:    jmp r13
;
; STATIC-LABEL: get_address:
; STATIC:         .cfi_startproc
; STATIC-NEXT:  // %bb.1:
; STATIC-NEXT:    lli r1, %lo16(myvar)
; STATIC-NEXT:    lui r1, %hi16(myvar)
; STATIC-NEXT:    jmp r13
  ret ptr @myvar
}

define i32 @load_global() {
; PIC-LABEL: load_global:
; PIC:         .cfi_startproc
; PIC-NEXT:  // %bb.1:
; PIC-NEXT:    mov r1, r15
; PIC-NEXT:    add r1, %pcrel(myvar+4)
; PIC-NEXT:    ldw r1, [r1 + 0]
; PIC-NEXT:    jmp r13
;
; STATIC-LABEL: load_global:
; STATIC:         .cfi_startproc
; STATIC-NEXT:  // %bb.1:
; STATIC-NEXT:    lli r1, %lo16(myvar)
; STATIC-NEXT:    lui r1, %hi16(myvar)
; STATIC-NEXT:    ldw r1, [r1 + 0]
; STATIC-NEXT:    jmp r13
  %v = load i32, ptr @myvar
  ret i32 %v
}

define void @store_global(i32 %v) {
; PIC-LABEL: store_global:
; PIC:         .cfi_startproc
; PIC-NEXT:  // %bb.1:
; PIC-NEXT:    mov r2, r15
; PIC-NEXT:    add r2, %pcrel(myvar+4)
; PIC-NEXT:    stw r1, [r2 + 0]
; PIC-NEXT:    jmp r13
;
; STATIC-LABEL: store_global:
; STATIC:         .cfi_startproc
; STATIC-NEXT:  // %bb.1:
; STATIC-NEXT:    lli r2, %lo16(myvar)
; STATIC-NEXT:    lui r2, %hi16(myvar)
; STATIC-NEXT:    stw r1, [r2 + 0]
; STATIC-NEXT:    jmp r13
  store i32 %v, ptr @myvar
  ret void
}
