; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra -global-isel -O0 -relocation-model=pic \
; RUN:   -verify-machineinstrs < %s | FileCheck %s -check-prefix=PIC
; RUN: llc -mtriple=penumbra -global-isel -O0 -relocation-model=static \
; RUN:   -verify-machineinstrs < %s | FileCheck %s -check-prefix=STATIC

; PIC vs static global address materialization.
; PIC/PIE uses GOT-indirect: LLI/LUI got_pcrel + ADD Rd, PC + LDW from GOT.
; The ADD's own PC is the anchor; LLI/LUI carry -8/-4 addends so the
; linker's sym + addend - fixup_addr formula yields GOT[sym] - Q at each half.
; Static uses absolute LLI+LUI.
; GOT entries are full data words — R_PENUMBRA_RELATIVE patches them for PIE.

@myvar = global i32 42
@pievar = dso_local global i32 99

define ptr @get_address() {
; PIC-LABEL: get_address:
; PIC:         .cfi_startproc
; PIC-NEXT:  // %bb.1:
; PIC-NEXT:    lli r1, %got_pcrel_lo16(myvar-8)
; PIC-NEXT:    lui r1, %got_pcrel_hi16(myvar-4)
; PIC-NEXT:    add r1, r15
; PIC-NEXT:    ldw r1, [r1 + 0]
; PIC-NEXT:    jmp r13
;
; STATIC-LABEL: get_address:
; STATIC:         .cfi_startproc
; STATIC-NEXT:  // %bb.1:
; STATIC-NEXT:    lli r1, %lo16(myvar)
; STATIC-NEXT:    lui r1, %hi16(myvar)
; STATIC-NEXT:    jmp r13
  ret ptr @myvar
}

define i32 @load_global() {
; PIC-LABEL: load_global:
; PIC:         .cfi_startproc
; PIC-NEXT:  // %bb.1:
; PIC-NEXT:    lli r1, %got_pcrel_lo16(myvar-8)
; PIC-NEXT:    lui r1, %got_pcrel_hi16(myvar-4)
; PIC-NEXT:    add r1, r15
; PIC-NEXT:    ldw r1, [r1 + 0]
; PIC-NEXT:    ldw r1, [r1 + 0]
; PIC-NEXT:    jmp r13
;
; STATIC-LABEL: load_global:
; STATIC:         .cfi_startproc
; STATIC-NEXT:  // %bb.1:
; STATIC-NEXT:    lli r1, %lo16(myvar)
; STATIC-NEXT:    lui r1, %hi16(myvar)
; STATIC-NEXT:    ldw r1, [r1 + 0]
; STATIC-NEXT:    jmp r13
  %v = load i32, ptr @myvar
  ret i32 %v
}

define void @store_global(i32 %v) {
; PIC-LABEL: store_global:
; PIC:         .cfi_startproc
; PIC-NEXT:  // %bb.1:
; PIC-NEXT:    lli r2, %got_pcrel_lo16(myvar-8)
; PIC-NEXT:    lui r2, %got_pcrel_hi16(myvar-4)
; PIC-NEXT:    add r2, r15
; PIC-NEXT:    ldw r2, [r2 + 0]
; PIC-NEXT:    stw r1, [r2 + 0]
; PIC-NEXT:    jmp r13
;
; STATIC-LABEL: store_global:
; STATIC:         .cfi_startproc
; STATIC-NEXT:  // %bb.1:
; STATIC-NEXT:    lli r2, %lo16(myvar)
; STATIC-NEXT:    lui r2, %hi16(myvar)
; STATIC-NEXT:    stw r1, [r2 + 0]
; STATIC-NEXT:    jmp r13
  store i32 %v, ptr @myvar
  ret void
}

; PIE test: dso_local globals also use GOT in PIC model.
; GOT entries are data words — R_RELATIVE patches them for PIE.
define dso_local ptr @get_pie_address() {
; PIC-LABEL: get_pie_address:
; PIC:       .Lget_pie_address$local:
; PIC-NEXT:    .type .Lget_pie_address$local,@function
; PIC-NEXT:    .cfi_startproc
; PIC-NEXT:  // %bb.1:
; PIC-NEXT:    lli r1, %got_pcrel_lo16(pievar-8)
; PIC-NEXT:    lui r1, %got_pcrel_hi16(pievar-4)
; PIC-NEXT:    add r1, r15
; PIC-NEXT:    ldw r1, [r1 + 0]
; PIC-NEXT:    jmp r13
;
; STATIC-LABEL: get_pie_address:
; STATIC:         .cfi_startproc
; STATIC-NEXT:  // %bb.1:
; STATIC-NEXT:    lli r1, %lo16(pievar)
; STATIC-NEXT:    lui r1, %hi16(pievar)
; STATIC-NEXT:    jmp r13
  ret ptr @pievar
}
