; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra-unknown-netbsd -relocation-model=pic < %s | FileCheck %s

; Switch cases that store through different GOT-loaded globals end in
; identical add/ldw/stw tails, which branch folding merges.  The merged
; tail must never absorb the PC-reading ADD: each case's GOT offset is
; relative to its own anchor (PC-anchored relocation pairs,
; doc/system/abi.md).  The Localizer pass clones G_GLOBAL_VALUE into
; each case block, so without anchor pairing the tail merge anchored
; two of the three cases against the wrong address and libc's
; dl_iterate_phdr_setup stored auxv values through unrelated GOT slots
; (NetBSD PR: init died with SIGBUS at boot).
;
; Each lli/lui pair below must reference the .LPC label of the add that
; actually executes with it.
;
; The globals are deliberately preemptible (default visibility), so they
; take the GOT path whose deref forms the mergeable common tail this test
; exists to guard.  A non-preemptible (internal/hidden) global would use
; PC-relative-direct (%pcrel), whose shorter add/stw tail does not merge
; into a shared anchor-absorbing block — see pic-dso-local.ll for that
; selection.

@dlpi_addr = global i32 0, align 4
@dlpi_phdr = global ptr null, align 4
@dlpi_phnum = global i16 0, align 2
@dlpi_name = global ptr null, align 4

define void @setup(ptr %aux) {
; CHECK-LABEL: setup:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    add r1, 4
; CHECK-NEXT:    b .LBB0_1
; CHECK-NEXT:  .LBB0_8: // %at_phnum
; CHECK-NEXT:    // in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    ldw r2, [r1 + 0]
; CHECK-NEXT:    lli r3, %got_pcrel_lo16(dlpi_phnum-.LPC0_2)
; CHECK-NEXT:    lui r3, %got_pcrel_hi16(dlpi_phnum-.LPC0_2)
; CHECK-NEXT:  .LPC0_2:
; CHECK-NEXT:    add r3, pc
; CHECK-NEXT:    ldw r3, [r3 + 0]
; CHECK-NEXT:    sth r2, [r3 + 0]
; CHECK-NEXT:  .LBB0_9: // %latch
; CHECK-NEXT:    // in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    add r1, 8
; CHECK-NEXT:  .LBB0_1: // %loop
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ldw r2, [r1 + -4]
; CHECK-NEXT:    cmp r2, 7
; CHECK-NEXT:    bls .LBB0_5
; CHECK-NEXT:  // %bb.2: // %loop
; CHECK-NEXT:    // in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    cmp r2, 2014
; CHECK-NEXT:    bne .LBB0_9
; CHECK-NEXT:  // %bb.3: // %at_execname
; CHECK-NEXT:    // in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    ldw r2, [r1 + 0]
; CHECK-NEXT:    lli r3, %got_pcrel_lo16(dlpi_name-.LPC0_0)
; CHECK-NEXT:    lui r3, %got_pcrel_hi16(dlpi_name-.LPC0_0)
; CHECK-NEXT:  .LPC0_0:
; CHECK-NEXT:    add r3, pc
; CHECK-NEXT:    b .LBB0_4
; CHECK-NEXT:  .LBB0_5: // %loop
; CHECK-NEXT:    // in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:  .LPC0_4:
; CHECK-NEXT:    mov r3, pc
; CHECK-NEXT:    add r3, %pcrel(.LJTI0_0-.LPC0_4)
; CHECK-NEXT:    shl r2, 2
; CHECK-NEXT:    add r2, r3
; CHECK-NEXT:    ldw r2, [r2 + 0]
; CHECK-NEXT:    add r2, r3
; CHECK-NEXT:    jmp r2
; CHECK-NEXT:  .LBB0_7: // %at_phdr
; CHECK-NEXT:    // in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    ldw r2, [r1 + 0]
; CHECK-NEXT:    lli r3, %got_pcrel_lo16(dlpi_phdr-.LPC0_1)
; CHECK-NEXT:    lui r3, %got_pcrel_hi16(dlpi_phdr-.LPC0_1)
; CHECK-NEXT:  .LPC0_1:
; CHECK-NEXT:    add r3, pc
; CHECK-NEXT:    b .LBB0_4
; CHECK-NEXT:  .LBB0_6: // %at_base
; CHECK-NEXT:    // in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    ldw r2, [r1 + 0]
; CHECK-NEXT:    lli r3, %got_pcrel_lo16(dlpi_addr-.LPC0_3)
; CHECK-NEXT:    lui r3, %got_pcrel_hi16(dlpi_addr-.LPC0_3)
; CHECK-NEXT:  .LPC0_3:
; CHECK-NEXT:    add r3, pc
; CHECK-NEXT:  .LBB0_4: // %latch
; CHECK-NEXT:    // in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    ldw r3, [r3 + 0]
; CHECK-NEXT:    stw r2, [r3 + 0]
; CHECK-NEXT:    add r1, 8
; CHECK-NEXT:    b .LBB0_1
; CHECK-NEXT:  .LBB0_10: // %done
; CHECK-NEXT:    jmp lr
entry:
  br label %loop

loop:
  %p = phi ptr [ %aux, %entry ], [ %next, %latch ]
  %tag = load i32, ptr %p, align 4
  switch i32 %tag, label %latch [
    i32 0, label %done
    i32 7, label %at_base
    i32 3, label %at_phdr
    i32 5, label %at_phnum
    i32 2014, label %at_execname
  ]

at_base:
  %vb.p = getelementptr inbounds i8, ptr %p, i32 4
  %vb = load i32, ptr %vb.p, align 4
  store i32 %vb, ptr @dlpi_addr, align 4
  br label %latch

at_phdr:
  %vp.p = getelementptr inbounds i8, ptr %p, i32 4
  %vp = load i32, ptr %vp.p, align 4
  %vp.ptr = inttoptr i32 %vp to ptr
  store ptr %vp.ptr, ptr @dlpi_phdr, align 4
  br label %latch

at_phnum:
  %vn.p = getelementptr inbounds i8, ptr %p, i32 4
  %vn = load i32, ptr %vn.p, align 4
  %vn.h = trunc i32 %vn to i16
  store i16 %vn.h, ptr @dlpi_phnum, align 2
  br label %latch

at_execname:
  %ve.p = getelementptr inbounds i8, ptr %p, i32 4
  %ve = load i32, ptr %ve.p, align 4
  %ve.ptr = inttoptr i32 %ve to ptr
  store ptr %ve.ptr, ptr @dlpi_name, align 4
  br label %latch

latch:
  %next = getelementptr inbounds i8, ptr %p, i32 8
  br label %loop

done:
  ret void
}

; Readers keep the globals alive through -O2 pipelines that
; would otherwise drop the stores.
define ptr @peek(i32 %i) {
; CHECK-LABEL: peek:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    cmp r1, 0
; CHECK-NEXT:    bne .LBB1_1
; CHECK-NEXT:  // %bb.4: // %ret_name
; CHECK-NEXT:    lli r1, %got_pcrel_lo16(dlpi_name-.LPC1_0)
; CHECK-NEXT:    lui r1, %got_pcrel_hi16(dlpi_name-.LPC1_0)
; CHECK-NEXT:  .LPC1_0:
; CHECK-NEXT:    add r1, pc
; CHECK-NEXT:    b .LBB1_5
; CHECK-NEXT:  .LBB1_1: // %entry
; CHECK-NEXT:    cmp r1, 1
; CHECK-NEXT:    bne .LBB1_2
; CHECK-NEXT:  // %bb.6: // %ret_addr
; CHECK-NEXT:    lli r1, %got_pcrel_lo16(dlpi_addr-.LPC1_1)
; CHECK-NEXT:    lui r1, %got_pcrel_hi16(dlpi_addr-.LPC1_1)
; CHECK-NEXT:  .LPC1_1:
; CHECK-NEXT:    add r1, pc
; CHECK-NEXT:    b .LBB1_5
; CHECK-NEXT:  .LBB1_2: // %entry
; CHECK-NEXT:    cmp r1, 2
; CHECK-NEXT:    bne .LBB1_7
; CHECK-NEXT:  // %bb.3: // %ret_phdr
; CHECK-NEXT:    lli r1, %got_pcrel_lo16(dlpi_phdr-.LPC1_2)
; CHECK-NEXT:    lui r1, %got_pcrel_hi16(dlpi_phdr-.LPC1_2)
; CHECK-NEXT:  .LPC1_2:
; CHECK-NEXT:    add r1, pc
; CHECK-NEXT:  .LBB1_5: // %ret_name
; CHECK-NEXT:    ldw r1, [r1 + 0]
; CHECK-NEXT:    ldw r1, [r1 + 0]
; CHECK-NEXT:    jmp lr
; CHECK-NEXT:  .LBB1_7: // %ret_phnum
; CHECK-NEXT:    lli r1, %got_pcrel_lo16(dlpi_phnum-.LPC1_3)
; CHECK-NEXT:    lui r1, %got_pcrel_hi16(dlpi_phnum-.LPC1_3)
; CHECK-NEXT:  .LPC1_3:
; CHECK-NEXT:    add r1, pc
; CHECK-NEXT:    ldw r1, [r1 + 0]
; CHECK-NEXT:    ldh r1, [r1 + 0]
; CHECK-NEXT:    jmp lr
entry:
  switch i32 %i, label %ret_phnum [
    i32 0, label %ret_name
    i32 1, label %ret_addr
    i32 2, label %ret_phdr
  ]

ret_name:
  %n = load ptr, ptr @dlpi_name, align 4
  ret ptr %n

ret_addr:
  %a = load i32, ptr @dlpi_addr, align 4
  %a.ptr = inttoptr i32 %a to ptr
  ret ptr %a.ptr

ret_phdr:
  %h = load ptr, ptr @dlpi_phdr, align 4
  ret ptr %h

ret_phnum:
  %m = load i16, ptr @dlpi_phnum, align 2
  %m.w = zext i16 %m to i32
  %m.ptr = inttoptr i32 %m.w to ptr
  ret ptr %m.ptr
}
