; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra -global-isel -O0 -relocation-model=pic \
; RUN:   -verify-machineinstrs < %s | FileCheck %s -check-prefix=PIC

; PIC jump tables use label-difference entries and add the JT base back.

define i32 @switch_test(i32 %x) {
; PIC-LABEL: switch_test:
; PIC:         .cfi_startproc
; PIC-NEXT:  // %bb.1: // %entry
; PIC-NEXT:    sub sp, 4
; PIC-NEXT:    add r1, 0
; PIC-NEXT:    stw r1, [sp + 0] // 4-byte Folded Spill
; PIC-NEXT:    cmp r1, 3
; PIC-NEXT:    bhi .LBB0_6
; PIC-NEXT:  // %bb.7: // %entry
; PIC-NEXT:    ldw r1, [sp + 0] // 4-byte Folded Reload
; PIC-NEXT:  .LPC0_0:
; PIC-NEXT:    mov r2, pc
; PIC-NEXT:    add r2, %pcrel(.LJTI0_0-.LPC0_0)
; PIC-NEXT:    shl r1, 2
; PIC-NEXT:    add r1, r2
; PIC-NEXT:    ldw r1, [r1 + 0]
; PIC-NEXT:    add r1, r2
; PIC-NEXT:    jmp r1
; PIC-NEXT:  .LBB0_2: // %bb0
; PIC-NEXT:    lli r1, 10
; PIC-NEXT:    add sp, 4
; PIC-NEXT:    jmp lr
; PIC-NEXT:  .LBB0_3: // %bb1
; PIC-NEXT:    lli r1, 20
; PIC-NEXT:    add sp, 4
; PIC-NEXT:    jmp lr
; PIC-NEXT:  .LBB0_4: // %bb2
; PIC-NEXT:    lli r1, 30
; PIC-NEXT:    add sp, 4
; PIC-NEXT:    jmp lr
; PIC-NEXT:  .LBB0_5: // %bb3
; PIC-NEXT:    lli r1, 40
; PIC-NEXT:    add sp, 4
; PIC-NEXT:    jmp lr
; PIC-NEXT:  .LBB0_6: // %default
; PIC-NEXT:    llis r1, -1
; PIC-NEXT:    add sp, 4
; PIC-NEXT:    jmp lr
entry:
  switch i32 %x, label %default [
    i32 0, label %bb0
    i32 1, label %bb1
    i32 2, label %bb2
    i32 3, label %bb3
  ]
bb0: ret i32 10
bb1: ret i32 20
bb2: ret i32 30
bb3: ret i32 40
default: ret i32 -1
}

; Entries are label differences (position-independent), inline in .text:
; PIC: .LJTI0_0:
; PIC-NEXT: .word .LBB0_{{[0-9]+}}-.LJTI0_0
; PIC-NEXT: .word .LBB0_{{[0-9]+}}-.LJTI0_0
; PIC-NEXT: .word .LBB0_{{[0-9]+}}-.LJTI0_0
; PIC-NEXT: .word .LBB0_{{[0-9]+}}-.LJTI0_0
