; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra-unknown-netbsd -global-isel -relocation-model=pic \
; RUN:   -verify-machineinstrs < %s | FileCheck %s

; In the PIC model the selector picks the materialization sequence by
; preemptibility (GV->isDSOLocal(), excluding undefined-weak):
;   - preemptible symbol  -> GOT-indirect: %got_pcrel + ADD pc + LDW(GOT) + deref
;   - non-preemptible      -> PC-relative-direct: %pcrel + ADD pc + deref
;     (no GOT slot, no GOT load, no startup relocation)
;   - undefined extern_weak -> must stay GOT-indirect even when hidden, so it
;     can resolve to 0 at link time (a %pcrel anchor cannot encode "absent").

@preempt  = global i32 0                              ; default visibility -> preemptible
@local    = internal global i32 0                     ; static -> dso_local
@hidden   = hidden global i32 0                       ; hidden -> dso_local
@dsolocal = dso_local global i32 0                    ; explicit dso_local
@weakhid  = extern_weak hidden global i32             ; undefined weak, even if hidden
@arr      = internal global [8 x i32] zeroinitializer ; offset folds into %pcrel

; Preemptible: GOT-indirect (two loads — GOT slot then deref).
define i32 @read_preempt() {
; CHECK-LABEL: read_preempt:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    lli r1, %got_pcrel_lo16(preempt-.LPC0_0)
; CHECK-NEXT:    lui r1, %got_pcrel_hi16(preempt-.LPC0_0)
; CHECK-NEXT:  .LPC0_0:
; CHECK-NEXT:    add r1, pc
; CHECK-NEXT:    ldw r1, [r1 + 0]
; CHECK-NEXT:    ldw r1, [r1 + 0]
; CHECK-NEXT:    jmp lr
  %v = load i32, ptr @preempt
  ret i32 %v
}

; Static (internal) -> dso_local -> PC-relative-direct (single deref).
define i32 @read_local() {
; CHECK-LABEL: read_local:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    lli r1, %pcrel_lo16(local-.LPC1_0)
; CHECK-NEXT:    lui r1, %pcrel_hi16(local-.LPC1_0)
; CHECK-NEXT:  .LPC1_0:
; CHECK-NEXT:    add r1, pc
; CHECK-NEXT:    ldw r1, [r1 + 0]
; CHECK-NEXT:    jmp lr
  %v = load i32, ptr @local
  ret i32 %v
}

; Hidden -> dso_local -> PC-relative-direct.
define i32 @read_hidden() {
; CHECK-LABEL: read_hidden:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    lli r1, %pcrel_lo16(hidden-.LPC2_0)
; CHECK-NEXT:    lui r1, %pcrel_hi16(hidden-.LPC2_0)
; CHECK-NEXT:  .LPC2_0:
; CHECK-NEXT:    add r1, pc
; CHECK-NEXT:    ldw r1, [r1 + 0]
; CHECK-NEXT:    jmp lr
  %v = load i32, ptr @hidden
  ret i32 %v
}

; Explicit dso_local -> PC-relative-direct.
define i32 @read_dsolocal() {
; CHECK-LABEL: read_dsolocal:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    lli r1, %pcrel_lo16(dsolocal-.LPC3_0)
; CHECK-NEXT:    lui r1, %pcrel_hi16(dsolocal-.LPC3_0)
; CHECK-NEXT:  .LPC3_0:
; CHECK-NEXT:    add r1, pc
; CHECK-NEXT:    ldw r1, [r1 + 0]
; CHECK-NEXT:    jmp lr
  %v = load i32, ptr @dsolocal
  ret i32 %v
}

; Undefined extern_weak: the hasExternalWeakLinkage() guard keeps it on the
; GOT path even though it is hidden (it may resolve to 0).
define i32 @read_weak() {
; CHECK-LABEL: read_weak:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    lli r1, %got_pcrel_lo16(weakhid-.LPC4_0)
; CHECK-NEXT:    lui r1, %got_pcrel_hi16(weakhid-.LPC4_0)
; CHECK-NEXT:  .LPC4_0:
; CHECK-NEXT:    add r1, pc
; CHECK-NEXT:    ldw r1, [r1 + 0]
; CHECK-NEXT:    ldw r1, [r1 + 0]
; CHECK-NEXT:    jmp lr
  %v = load i32, ptr @weakhid
  ret i32 %v
}

; Address of a dso_local array element: the base materializes via %pcrel and
; the constant element offset is added with ADDi.  (The selector bakes a
; G_GLOBAL_VALUE's own offset straight into the %pcrel operand; here the GEP
; constant reaches selection as a separate add, matching the GOT path.)
define ptr @addr_arr_elem() {
; CHECK-LABEL: addr_arr_elem:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    lli r1, %pcrel_lo16(arr-.LPC5_0)
; CHECK-NEXT:    lui r1, %pcrel_hi16(arr-.LPC5_0)
; CHECK-NEXT:  .LPC5_0:
; CHECK-NEXT:    add r1, pc
; CHECK-NEXT:    add r1, 20
; CHECK-NEXT:    jmp lr
  ret ptr getelementptr inbounds ([8 x i32], ptr @arr, i32 0, i32 5)
}
