; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra-unknown-netbsd -relocation-model=pic < %s | FileCheck %s

; The %pcrel sibling of pic-anchor-tail-merge.ll.  Internal (non-preemptible)
; globals take the PC-relative-direct sequence, whose anchor uses the same
; per-site .LPC label machinery as the GOT path.  Under -O2 the Localizer
; clones each G_GLOBAL_VALUE into its using block and BranchFolder may merge
; identical tails; the anchor-pairing must survive so each lli/lui pair still
; measures against the .LPC of the add that executes with it.  A mispaired
; anchor would compute a neighbouring symbol's address — the %pcrel analogue
; of the dl_iterate_phdr SIGBUS.

@a = internal global i32 0, align 4
@b = internal global i32 0, align 4
@c = internal global i32 0, align 4
@d = internal global i32 0, align 4

define void @store_sel(i32 %sel, i32 %v) {
; CHECK-LABEL: store_sel:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    cmp r1, 3
; CHECK-NEXT:    bhi .LBB0_7
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:  .LPC0_4:
; CHECK-NEXT:    mov r3, pc
; CHECK-NEXT:    add r3, %pcrel(.LJTI0_0-.LPC0_4)
; CHECK-NEXT:    shl r1, 2
; CHECK-NEXT:    add r1, r3
; CHECK-NEXT:    ldw r1, [r1 + 0]
; CHECK-NEXT:    add r1, r3
; CHECK-NEXT:    jmp r1
; CHECK-NEXT:  .LBB0_2: // %sa
; CHECK-NEXT:    lli r1, %pcrel_lo16(a-.LPC0_0)
; CHECK-NEXT:    lui r1, %pcrel_hi16(a-.LPC0_0)
; CHECK-NEXT:  .LPC0_0:
; CHECK-NEXT:    add r1, pc
; CHECK-NEXT:    b .LBB0_6
; CHECK-NEXT:  .LBB0_4: // %sc
; CHECK-NEXT:    lli r1, %pcrel_lo16(c-.LPC0_2)
; CHECK-NEXT:    lui r1, %pcrel_hi16(c-.LPC0_2)
; CHECK-NEXT:  .LPC0_2:
; CHECK-NEXT:    add r1, pc
; CHECK-NEXT:    b .LBB0_6
; CHECK-NEXT:  .LBB0_5: // %sd
; CHECK-NEXT:    lli r1, %pcrel_lo16(d-.LPC0_3)
; CHECK-NEXT:    lui r1, %pcrel_hi16(d-.LPC0_3)
; CHECK-NEXT:  .LPC0_3:
; CHECK-NEXT:    add r1, pc
; CHECK-NEXT:    b .LBB0_6
; CHECK-NEXT:  .LBB0_3: // %sb
; CHECK-NEXT:    lli r1, %pcrel_lo16(b-.LPC0_1)
; CHECK-NEXT:    lui r1, %pcrel_hi16(b-.LPC0_1)
; CHECK-NEXT:  .LPC0_1:
; CHECK-NEXT:    add r1, pc
; CHECK-NEXT:  .LBB0_6: // %done
; CHECK-NEXT:    stw r2, [r1 + 0]
; CHECK-NEXT:  .LBB0_7: // %done
; CHECK-NEXT:    jmp lr
  switch i32 %sel, label %done [
    i32 0, label %sa
    i32 1, label %sb
    i32 2, label %sc
    i32 3, label %sd
  ]
sa:
  store i32 %v, ptr @a, align 4
  br label %done
sb:
  store i32 %v, ptr @b, align 4
  br label %done
sc:
  store i32 %v, ptr @c, align 4
  br label %done
sd:
  store i32 %v, ptr @d, align 4
  br label %done
done:
  ret void
}

define ptr @addr_sel(i32 %sel) {
; CHECK-LABEL: addr_sel:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    cmp r1, 1
; CHECK-NEXT:    bne .LBB1_1
; CHECK-NEXT:  // %bb.4: // %rb
; CHECK-NEXT:    lli r1, %pcrel_lo16(b-.LPC1_0)
; CHECK-NEXT:    lui r1, %pcrel_hi16(b-.LPC1_0)
; CHECK-NEXT:  .LPC1_0:
; CHECK-NEXT:    add r1, pc
; CHECK-NEXT:    jmp lr
; CHECK-NEXT:  .LBB1_1:
; CHECK-NEXT:    cmp r1, 2
; CHECK-NEXT:    bne .LBB1_2
; CHECK-NEXT:  // %bb.5: // %rc
; CHECK-NEXT:    lli r1, %pcrel_lo16(c-.LPC1_1)
; CHECK-NEXT:    lui r1, %pcrel_hi16(c-.LPC1_1)
; CHECK-NEXT:  .LPC1_1:
; CHECK-NEXT:    add r1, pc
; CHECK-NEXT:    jmp lr
; CHECK-NEXT:  .LBB1_2:
; CHECK-NEXT:    cmp r1, 3
; CHECK-NEXT:    bne .LBB1_3
; CHECK-NEXT:  // %bb.6: // %rd
; CHECK-NEXT:    lli r1, %pcrel_lo16(d-.LPC1_2)
; CHECK-NEXT:    lui r1, %pcrel_hi16(d-.LPC1_2)
; CHECK-NEXT:  .LPC1_2:
; CHECK-NEXT:    add r1, pc
; CHECK-NEXT:    jmp lr
; CHECK-NEXT:  .LBB1_3: // %ra
; CHECK-NEXT:    lli r1, %pcrel_lo16(a-.LPC1_3)
; CHECK-NEXT:    lui r1, %pcrel_hi16(a-.LPC1_3)
; CHECK-NEXT:  .LPC1_3:
; CHECK-NEXT:    add r1, pc
; CHECK-NEXT:    jmp lr
  switch i32 %sel, label %ra [
    i32 1, label %rb
    i32 2, label %rc
    i32 3, label %rd
  ]
ra:
  ret ptr @a
rb:
  ret ptr @b
rc:
  ret ptr @c
rd:
  ret ptr @d
}
