; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; G_PREFETCH should be silently discarded — Penumbra has no cache hints.

declare void @llvm.prefetch.p0(ptr, i32, i32, i32)

define void @prefetch_read(ptr %p) {
; CHECK-LABEL: prefetch_read:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    jmp lr
  call void @llvm.prefetch.p0(ptr %p, i32 0, i32 3, i32 1)
  ret void
}

define void @prefetch_write(ptr %p) {
; CHECK-LABEL: prefetch_write:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    jmp lr
  call void @llvm.prefetch.p0(ptr %p, i32 1, i32 3, i32 1)
  ret void
}
