; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

define i32 @ptrtoint(ptr %p) {
; CHECK-LABEL: ptrtoint:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    jmp r13
  %addr = ptrtoint ptr %p to i32
  ret i32 %addr
}

define ptr @inttoptr(i32 %addr) {
; CHECK-LABEL: inttoptr:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    jmp r13
  %p = inttoptr i32 %addr to ptr
  ret ptr %p
}
