; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra-unknown-none -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; A select whose condition compares against a uimm16 constant folds the
; constant into the diamond's CMPi (SELECT_CCi_GPR) instead of materialising
; it with an LLI.  See emitSelectCC in PenumbraInstructionSelector.cpp.

; Signed predicate, constant RHS: cmp + blt with the constant immediate.
define i32 @sel_slt_imm(i32 %a, i32 %x, i32 %y) {
; CHECK-LABEL: sel_slt_imm:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r4, r1
; CHECK-NEXT:    mov r1, r2
; CHECK-NEXT:    cmp r4, 100
; CHECK-NEXT:    blt .LBB0_2
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    mov r1, r3
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    jmp lr
  %c = icmp slt i32 %a, 100
  %r = select i1 %c, i32 %x, i32 %y
  ret i32 %r
}

; Unsigned predicate, constant RHS: cmp + bcc with the constant immediate.
define i32 @sel_ult_imm(i32 %a, i32 %x, i32 %y) {
; CHECK-LABEL: sel_ult_imm:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r4, r1
; CHECK-NEXT:    mov r1, r2
; CHECK-NEXT:    cmp r4, 7
; CHECK-NEXT:    bcc .LBB1_2
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    mov r1, r3
; CHECK-NEXT:  .LBB1_2:
; CHECK-NEXT:    jmp lr
  %c = icmp ult i32 %a, 7
  %r = select i1 %c, i32 %x, i32 %y
  ret i32 %r
}

; Equality against a constant: cmp + beq with the constant immediate.
define i32 @sel_eq_imm(i32 %a, i32 %x, i32 %y) {
; CHECK-LABEL: sel_eq_imm:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r4, r1
; CHECK-NEXT:    mov r1, r2
; CHECK-NEXT:    cmp r4, 42
; CHECK-NEXT:    beq .LBB2_2
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    mov r1, r3
; CHECK-NEXT:  .LBB2_2:
; CHECK-NEXT:    jmp lr
  %c = icmp eq i32 %a, 42
  %r = select i1 %c, i32 %x, i32 %y
  ret i32 %r
}

; Constant on the LHS with an asymmetric predicate: operands swap so the
; constant folds, and the predicate swaps with them (100 < a  ==  a > 100,
; so bgt — a bge here would be the swapped/inverse confusion).
define i32 @sel_slt_imm_lhs(i32 %a, i32 %x, i32 %y) {
; CHECK-LABEL: sel_slt_imm_lhs:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r4, r1
; CHECK-NEXT:    mov r1, r2
; CHECK-NEXT:    cmp r4, 100
; CHECK-NEXT:    bgt .LBB3_2
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    mov r1, r3
; CHECK-NEXT:  .LBB3_2:
; CHECK-NEXT:    jmp lr
  %c = icmp slt i32 100, %a
  %r = select i1 %c, i32 %x, i32 %y
  ret i32 %r
}

; Constant too wide for uimm16: stays in a register (LLI+LUI + register CMP).
define i32 @sel_big_imm(i32 %a, i32 %x, i32 %y) {
; CHECK-LABEL: sel_big_imm:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r4, r1
; CHECK-NEXT:    mov r1, r2
; CHECK-NEXT:    lli r2, 4464
; CHECK-NEXT:    lui r2, 1
; CHECK-NEXT:    cmp r4, r2
; CHECK-NEXT:    blt .LBB4_2
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    mov r1, r3
; CHECK-NEXT:  .LBB4_2:
; CHECK-NEXT:    jmp lr
  %c = icmp slt i32 %a, 70000
  %r = select i1 %c, i32 %x, i32 %y
  ret i32 %r
}

; Negative constant zero-extends past uimm16: no fold.
define i32 @sel_neg_imm(i32 %a, i32 %x, i32 %y) {
; CHECK-LABEL: sel_neg_imm:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r4, r1
; CHECK-NEXT:    mov r1, r2
; CHECK-NEXT:    llis r2, -5
; CHECK-NEXT:    cmp r4, r2
; CHECK-NEXT:    blt .LBB5_2
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    mov r1, r3
; CHECK-NEXT:  .LBB5_2:
; CHECK-NEXT:    jmp lr
  %c = icmp slt i32 %a, -5
  %r = select i1 %c, i32 %x, i32 %y
  ret i32 %r
}

; Standalone signed icmp materialised as a value takes the same diamond
; (selectICmp's fallback), so the constant folds there too.
define i32 @signed_icmp_value(i32 %a) {
; CHECK-LABEL: signed_icmp_value:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r2, r1
; CHECK-NEXT:    lli r1, 1
; CHECK-NEXT:    lli r3, 0
; CHECK-NEXT:    cmp r2, 5
; CHECK-NEXT:    blt .LBB6_2
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    mov r1, r3
; CHECK-NEXT:  .LBB6_2:
; CHECK-NEXT:    jmp lr
  %c = icmp slt i32 %a, 5
  %r = zext i1 %c to i32
  ret i32 %r
}

; Pointer compared against null: the zero folds as CMPi 0.
define i32 @sel_ptr_null(ptr %p, i32 %x, i32 %y) {
; CHECK-LABEL: sel_ptr_null:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r4, r1
; CHECK-NEXT:    mov r1, r2
; CHECK-NEXT:    cmp r4, 0
; CHECK-NEXT:    beq .LBB7_2
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    mov r1, r3
; CHECK-NEXT:  .LBB7_2:
; CHECK-NEXT:    jmp lr
  %c = icmp eq ptr %p, null
  %r = select i1 %c, i32 %x, i32 %y
  ret i32 %r
}
