; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra -global-isel -O0 -relocation-model=static \
; RUN:   -verify-machineinstrs < %s | FileCheck %s

; Static-mode jump tables should also use label-difference entries
; (same as PIC), placed inline in .text.  This avoids dynamic
; relocations in PIE and enables future 16-bit entry optimization.

define i32 @switch_static(i32 %x) {
; CHECK-LABEL: switch_static:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.1: // %entry
; CHECK-NEXT:    sub sp, 4
; CHECK-NEXT:    add r1, 0
; CHECK-NEXT:    stw r1, [sp + 0] // 4-byte Folded Spill
; CHECK-NEXT:    cmp r1, 3
; CHECK-NEXT:    bhi .LBB0_6
; CHECK-NEXT:  // %bb.7: // %entry
; CHECK-NEXT:    ldw r1, [sp + 0] // 4-byte Folded Reload
; CHECK-NEXT:    lli r2, %lo16(.LJTI0_0)
; CHECK-NEXT:    lui r2, %hi16(.LJTI0_0)
; CHECK-NEXT:    shl r1, 2
; CHECK-NEXT:    add r1, r2
; CHECK-NEXT:    ldw r1, [r1 + 0]
; CHECK-NEXT:    add r1, r2
; CHECK-NEXT:    jmp r1
; CHECK-NEXT:  .LBB0_2: // %bb0
; CHECK-NEXT:    lli r1, 10
; CHECK-NEXT:    add sp, 4
; CHECK-NEXT:    jmp lr
; CHECK-NEXT:  .LBB0_3: // %bb1
; CHECK-NEXT:    lli r1, 20
; CHECK-NEXT:    add sp, 4
; CHECK-NEXT:    jmp lr
; CHECK-NEXT:  .LBB0_4: // %bb2
; CHECK-NEXT:    lli r1, 30
; CHECK-NEXT:    add sp, 4
; CHECK-NEXT:    jmp lr
; CHECK-NEXT:  .LBB0_5: // %bb3
; CHECK-NEXT:    lli r1, 40
; CHECK-NEXT:    add sp, 4
; CHECK-NEXT:    jmp lr
; CHECK-NEXT:  .LBB0_6: // %default
; CHECK-NEXT:    llis r1, -1
; CHECK-NEXT:    add sp, 4
; CHECK-NEXT:    jmp lr
entry:
  switch i32 %x, label %default [
    i32 0, label %bb0
    i32 1, label %bb1
    i32 2, label %bb2
    i32 3, label %bb3
  ]
bb0: ret i32 10
bb1: ret i32 20
bb2: ret i32 30
bb3: ret i32 40
default: ret i32 -1
}

; Entries are label differences (not absolute), inline in .text:
; CHECK: .LJTI0_0:
; CHECK-NEXT: .word .LBB0_{{[0-9]+}}-.LJTI0_0
; CHECK-NEXT: .word .LBB0_{{[0-9]+}}-.LJTI0_0
; CHECK-NEXT: .word .LBB0_{{[0-9]+}}-.LJTI0_0
; CHECK-NEXT: .word .LBB0_{{[0-9]+}}-.LJTI0_0

; Jump table must NOT be in .rodata:
; CHECK-NOT: .section{{.*}}.rodata
