; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra -global-isel -O0 -relocation-model=static \
; RUN:   -verify-machineinstrs < %s | FileCheck %s

; Static-mode jump tables should also use label-difference entries
; (same as PIC), placed inline in .text.  This avoids dynamic
; relocations in PIE and enables future 16-bit entry optimization.

define i32 @switch_static(i32 %x) {
; CHECK-LABEL: switch_static:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.1: // %entry
; CHECK-NEXT:    sub r14, 24
; CHECK-NEXT:    lli r2, 3
; CHECK-NEXT:    lli r3, 40
; CHECK-NEXT:    stw r3, [r14 + 0] // 4-byte Folded Spill
; CHECK-NEXT:    lli r3, 30
; CHECK-NEXT:    stw r3, [r14 + 4] // 4-byte Folded Spill
; CHECK-NEXT:    lli r3, 20
; CHECK-NEXT:    stw r3, [r14 + 8] // 4-byte Folded Spill
; CHECK-NEXT:    lli r3, 10
; CHECK-NEXT:    stw r3, [r14 + 12] // 4-byte Folded Spill
; CHECK-NEXT:    llis r3, -1
; CHECK-NEXT:    stw r3, [r14 + 16] // 4-byte Folded Spill
; CHECK-NEXT:    sub r1, 0
; CHECK-NEXT:    stw r1, [r14 + 20] // 4-byte Folded Spill
; CHECK-NEXT:    cmp r1, r2
; CHECK-NEXT:    bhi .LBB0_6
; CHECK-NEXT:  // %bb.7: // %entry
; CHECK-NEXT:    ldw r1, [r14 + 20] // 4-byte Folded Reload
; CHECK-NEXT:    lli r2, %lo16(.LJTI0_0)
; CHECK-NEXT:    lui r2, %hi16(.LJTI0_0)
; CHECK-NEXT:    shl r1, 2
; CHECK-NEXT:    add r1, r2
; CHECK-NEXT:    ldw r1, [r1 + 0]
; CHECK-NEXT:    add r1, r2
; CHECK-NEXT:    jmp r1
; CHECK-NEXT:  .LBB0_2: // %bb0
; CHECK-NEXT:    ldw r1, [r14 + 12] // 4-byte Folded Reload
; CHECK-NEXT:    add r14, 24
; CHECK-NEXT:    jmp r13
; CHECK-NEXT:  .LBB0_3: // %bb1
; CHECK-NEXT:    ldw r1, [r14 + 8] // 4-byte Folded Reload
; CHECK-NEXT:    add r14, 24
; CHECK-NEXT:    jmp r13
; CHECK-NEXT:  .LBB0_4: // %bb2
; CHECK-NEXT:    ldw r1, [r14 + 4] // 4-byte Folded Reload
; CHECK-NEXT:    add r14, 24
; CHECK-NEXT:    jmp r13
; CHECK-NEXT:  .LBB0_5: // %bb3
; CHECK-NEXT:    ldw r1, [r14 + 0] // 4-byte Folded Reload
; CHECK-NEXT:    add r14, 24
; CHECK-NEXT:    jmp r13
; CHECK-NEXT:  .LBB0_6: // %default
; CHECK-NEXT:    ldw r1, [r14 + 16] // 4-byte Folded Reload
; CHECK-NEXT:    add r14, 24
; CHECK-NEXT:    jmp r13
entry:
  switch i32 %x, label %default [
    i32 0, label %bb0
    i32 1, label %bb1
    i32 2, label %bb2
    i32 3, label %bb3
  ]
bb0: ret i32 10
bb1: ret i32 20
bb2: ret i32 30
bb3: ret i32 40
default: ret i32 -1
}

; Entries are label differences (not absolute), inline in .text:
; CHECK: .LJTI0_0:
; CHECK-NEXT: .word .LBB0_{{[0-9]+}}-.LJTI0_0
; CHECK-NEXT: .word .LBB0_{{[0-9]+}}-.LJTI0_0
; CHECK-NEXT: .word .LBB0_{{[0-9]+}}-.LJTI0_0
; CHECK-NEXT: .word .LBB0_{{[0-9]+}}-.LJTI0_0

; Jump table must NOT be in .rodata:
; CHECK-NOT: .section{{.*}}.rodata
