; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra -global-isel -O0 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=O0
; RUN: llc -mtriple=penumbra -global-isel -O1 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=O1

; Strength reduction of constant multiply/divide/remainder.

; --- Multiply by power-of-2 ---
define i32 @mul_by_8(i32 %a) {
; O0-LABEL: mul_by_8:
; O0:         .cfi_startproc
; O0-NEXT:  // %bb.1:
; O0-NEXT:    shl r1, 3
; O0-NEXT:    jmp r13
;
; O1-LABEL: mul_by_8:
; O1:         .cfi_startproc
; O1-NEXT:  // %bb.0:
; O1-NEXT:    shl r1, 3
; O1-NEXT:    jmp r13
  %r = mul i32 %a, 8
  ret i32 %r
}

; --- Multiply by power-of-2 + 1 ---
define i32 @mul_by_5(i32 %a) {
; O0-LABEL: mul_by_5:
; O0:         .cfi_startproc
; O0-NEXT:  // %bb.1:
; O0-NEXT:    mov r2, r1
; O0-NEXT:    mov r1, r2
; O0-NEXT:    shl r1, 2
; O0-NEXT:    add r1, r2
; O0-NEXT:    jmp r13
;
; O1-LABEL: mul_by_5:
; O1:         .cfi_startproc
; O1-NEXT:  // %bb.0:
; O1-NEXT:    mov r2, r1
; O1-NEXT:    shl r2, 2
; O1-NEXT:    add r2, r1
; O1-NEXT:    mov r1, r2
; O1-NEXT:    jmp r13
  %r = mul i32 %a, 5
  ret i32 %r
}

define i32 @mul_by_3(i32 %a) {
; O0-LABEL: mul_by_3:
; O0:         .cfi_startproc
; O0-NEXT:  // %bb.1:
; O0-NEXT:    mov r2, r1
; O0-NEXT:    mov r1, r2
; O0-NEXT:    shl r1, 1
; O0-NEXT:    add r1, r2
; O0-NEXT:    jmp r13
;
; O1-LABEL: mul_by_3:
; O1:         .cfi_startproc
; O1-NEXT:  // %bb.0:
; O1-NEXT:    mov r2, r1
; O1-NEXT:    shl r2, 1
; O1-NEXT:    add r2, r1
; O1-NEXT:    mov r1, r2
; O1-NEXT:    jmp r13
  %r = mul i32 %a, 3
  ret i32 %r
}

; --- Multiply by power-of-2 - 1 ---
define i32 @mul_by_7(i32 %a) {
; O0-LABEL: mul_by_7:
; O0:         .cfi_startproc
; O0-NEXT:  // %bb.1:
; O0-NEXT:    mov r2, r1
; O0-NEXT:    mov r1, r2
; O0-NEXT:    shl r1, 3
; O0-NEXT:    sub r1, r2
; O0-NEXT:    jmp r13
;
; O1-LABEL: mul_by_7:
; O1:         .cfi_startproc
; O1-NEXT:  // %bb.0:
; O1-NEXT:    mov r2, r1
; O1-NEXT:    shl r2, 3
; O1-NEXT:    sub r2, r1
; O1-NEXT:    mov r1, r2
; O1-NEXT:    jmp r13
  %r = mul i32 %a, 7
  ret i32 %r
}

define i32 @mul_by_15(i32 %a) {
; O0-LABEL: mul_by_15:
; O0:         .cfi_startproc
; O0-NEXT:  // %bb.1:
; O0-NEXT:    mov r2, r1
; O0-NEXT:    mov r1, r2
; O0-NEXT:    shl r1, 4
; O0-NEXT:    sub r1, r2
; O0-NEXT:    jmp r13
;
; O1-LABEL: mul_by_15:
; O1:         .cfi_startproc
; O1-NEXT:  // %bb.0:
; O1-NEXT:    mov r2, r1
; O1-NEXT:    shl r2, 4
; O1-NEXT:    sub r2, r1
; O1-NEXT:    mov r1, r2
; O1-NEXT:    jmp r13
  %r = mul i32 %a, 15
  ret i32 %r
}

; --- Multiply edge cases ---
define i32 @mul_by_0(i32 %a) {
; O0-LABEL: mul_by_0:
; O0:         .cfi_startproc
; O0-NEXT:  // %bb.1:
; O0-NEXT:    mov r1, r0
; O0-NEXT:    jmp r13
;
; O1-LABEL: mul_by_0:
; O1:         .cfi_startproc
; O1-NEXT:  // %bb.0:
; O1-NEXT:    mov r1, r0
; O1-NEXT:    jmp r13
  %r = mul i32 %a, 0
  ret i32 %r
}

define i32 @mul_by_1(i32 %a) {
; O0-LABEL: mul_by_1:
; O0:         .cfi_startproc
; O0-NEXT:  // %bb.1:
; O0-NEXT:    shl r1, 0
; O0-NEXT:    jmp r13
;
; O1-LABEL: mul_by_1:
; O1:         .cfi_startproc
; O1-NEXT:  // %bb.0:
; O1-NEXT:    jmp r13
  %r = mul i32 %a, 1
  ret i32 %r
}

; --- Multiply non-reducible (should still libcall) ---
define i32 @mul_by_6(i32 %a) {
; O0-LABEL: mul_by_6:
; O0:         .cfi_startproc
; O0-NEXT:  // %bb.1:
; O0-NEXT:    sub r14, 4
; O0-NEXT:    stw r13, [r14 + 0] // 4-byte Folded Spill
; O0-NEXT:    lli r2, 6
; O0-NEXT:    bl __mulsi3
; O0-NEXT:    ldw r13, [r14 + 0] // 4-byte Folded Reload
; O0-NEXT:    add r14, 4
; O0-NEXT:    jmp r13
;
; O1-LABEL: mul_by_6:
; O1:         .cfi_startproc
; O1-NEXT:  // %bb.0:
; O1-NEXT:    sub r14, 4
; O1-NEXT:    stw r13, [r14 + 0] // 4-byte Folded Spill
; O1-NEXT:    lli r2, 6
; O1-NEXT:    bl __mulsi3
; O1-NEXT:    ldw r13, [r14 + 0] // 4-byte Folded Reload
; O1-NEXT:    add r14, 4
; O1-NEXT:    jmp r13
  %r = mul i32 %a, 6
  ret i32 %r
}

; --- Unsigned divide by power-of-2 ---
define i32 @udiv_by_4(i32 %a) {
; O0-LABEL: udiv_by_4:
; O0:         .cfi_startproc
; O0-NEXT:  // %bb.1:
; O0-NEXT:    shr r1, 2
; O0-NEXT:    jmp r13
;
; O1-LABEL: udiv_by_4:
; O1:         .cfi_startproc
; O1-NEXT:  // %bb.0:
; O1-NEXT:    shr r1, 2
; O1-NEXT:    jmp r13
  %r = udiv i32 %a, 4
  ret i32 %r
}

define i32 @udiv_by_1(i32 %a) {
; O0-LABEL: udiv_by_1:
; O0:         .cfi_startproc
; O0-NEXT:  // %bb.1:
; O0-NEXT:    jmp r13
;
; O1-LABEL: udiv_by_1:
; O1:         .cfi_startproc
; O1-NEXT:  // %bb.0:
; O1-NEXT:    jmp r13
  %r = udiv i32 %a, 1
  ret i32 %r
}

; --- Unsigned remainder by power-of-2 ---
define i32 @urem_by_16(i32 %a) {
; O0-LABEL: urem_by_16:
; O0:         .cfi_startproc
; O0-NEXT:  // %bb.1:
; O0-NEXT:    and r1, 15
; O0-NEXT:    jmp r13
;
; O1-LABEL: urem_by_16:
; O1:         .cfi_startproc
; O1-NEXT:  // %bb.0:
; O1-NEXT:    and r1, 15
; O1-NEXT:    jmp r13
  %r = urem i32 %a, 16
  ret i32 %r
}

define i32 @urem_by_1(i32 %a) {
; O0-LABEL: urem_by_1:
; O0:         .cfi_startproc
; O0-NEXT:  // %bb.1:
; O0-NEXT:    mov r1, r0
; O0-NEXT:    jmp r13
;
; O1-LABEL: urem_by_1:
; O1:         .cfi_startproc
; O1-NEXT:  // %bb.0:
; O1-NEXT:    mov r1, r0
; O1-NEXT:    jmp r13
  %r = urem i32 %a, 1
  ret i32 %r
}

; --- Non-power-of-2 divide (should still libcall) ---
define i32 @udiv_by_3(i32 %a) {
; O0-LABEL: udiv_by_3:
; O0:         .cfi_startproc
; O0-NEXT:  // %bb.1:
; O0-NEXT:    sub r14, 4
; O0-NEXT:    stw r13, [r14 + 0] // 4-byte Folded Spill
; O0-NEXT:    lli r2, 3
; O0-NEXT:    bl __udivsi3
; O0-NEXT:    ldw r13, [r14 + 0] // 4-byte Folded Reload
; O0-NEXT:    add r14, 4
; O0-NEXT:    jmp r13
;
; O1-LABEL: udiv_by_3:
; O1:         .cfi_startproc
; O1-NEXT:  // %bb.0:
; O1-NEXT:    sub r14, 4
; O1-NEXT:    stw r13, [r14 + 0] // 4-byte Folded Spill
; O1-NEXT:    lli r2, 3
; O1-NEXT:    bl __udivsi3
; O1-NEXT:    ldw r13, [r14 + 0] // 4-byte Folded Reload
; O1-NEXT:    add r14, 4
; O1-NEXT:    jmp r13
  %r = udiv i32 %a, 3
  ret i32 %r
}
