; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra-unknown-none -O0 -relocation-model=pic < %s \
; RUN:   | FileCheck %s

; PIC TLS access: GOT-indirect PC-relative offset to tls_index pair,
; then call __tls_get_addr.

@tls_var = thread_local global i32 0

define ptr @get_tls_addr() {
; CHECK-LABEL: get_tls_addr:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    sub sp, 4
; CHECK-NEXT:    stw lr, [sp + 0] // 4-byte Folded Spill
; CHECK-NEXT:    lli r1, %tlsgd_got_pcrel_lo16(tls_var-.LPC0_0)
; CHECK-NEXT:    lui r1, %tlsgd_got_pcrel_hi16(tls_var-.LPC0_0)
; CHECK-NEXT:  .LPC0_0:
; CHECK-NEXT:    add r1, pc
; CHECK-NEXT:    bl __tls_get_addr
; CHECK-NEXT:    ldw lr, [sp + 0] // 4-byte Folded Reload
; CHECK-NEXT:    add sp, 4
; CHECK-NEXT:    jmp lr
  %p = call ptr @llvm.threadlocal.address(ptr @tls_var)
  ret ptr %p
}

; TLS variable goes in .tbss:
; CHECK: .section .tbss
; CHECK: tls_var:
