; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra-unknown-none -O0 \
; RUN:   -relocation-model=static < %s | FileCheck %s

; Local-Exec TLS model (non-PIC, static binary): inline TP+offset
; via read R12 (TP register) + LLI/LUI (TLS relocs that lld resolves
; as R_TPREL for static linking).  No __tls_get_addr call.

@tls_var = thread_local(localexec) global i32 0

define ptr @get_tls_le() {
; CHECK-LABEL: get_tls_le:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    lli r1, %tlsgd_lo16(tls_var)
; CHECK-NEXT:    lui r1, %tlsgd_hi16(tls_var)
; CHECK-NEXT:    //APP
; CHECK-NEXT:    mov r2, tp
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    add r1, r2
; CHECK-NEXT:    jmp lr
  %p = call ptr @llvm.threadlocal.address(ptr @tls_var)
  ret ptr %p
}
