; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra-unknown-none -O0 < %s | FileCheck %s

; Non-PIC TLS access: uses LE inline pattern (read TP + offset).
; The LLI/LUI carry TLS GD relocs that lld resolves as R_TPREL.

@tls_var = thread_local global i32 0

define ptr @get_tls_addr() {
; CHECK-LABEL: get_tls_addr:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    lli r1, %tlsgd_lo16(tls_var)
; CHECK-NEXT:    lui r1, %tlsgd_hi16(tls_var)
; CHECK-NEXT:    //APP
; CHECK-NEXT:    mov r2, tp
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    add r1, r2
; CHECK-NEXT:    jmp lr
  %p = call ptr @llvm.threadlocal.address(ptr @tls_var)
  ret ptr %p
}
