; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra-unknown-none -O2 < %s | FileCheck %s

; A narrowed i64 add/sub whose 32-bit sum is dead while its carry/borrow is
; live must still emit the flag-producing ADD/SUB.  The selector's carry-in
; fusion (carryInAlreadyLive) drops the consumer's use of the carry vreg; if
; the producer's sum has no other use, bottom-up selection then erased the
; producer as trivially dead, leaving the fused ADC/SBC to read a stale SR.C.
; Seen in the wild as compiler-rt wideMultiply computing __divdf3 quotients
; 2 ULPs short when the low product half is unused.

; Carry of one dead lo-half add: result is (a + b) >> 32 with the lo sum
; otherwise unused.
define i32 @uaddo_dead_sum(i64 %a, i64 %b) {
; CHECK-LABEL: uaddo_dead_sum:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    add r1, r3
; CHECK-NEXT:    mov r1, zero
; CHECK-NEXT:    adc r1, zero
; CHECK-NEXT:    cmp r1, 1
; CHECK-NEXT:    adc r2, r4
; CHECK-NEXT:    mov r1, r2
; CHECK-NEXT:    jmp lr
  %sum = add i64 %a, %b
  %hi = lshr i64 %sum, 32
  %t = trunc i64 %hi to i32
  ret i32 %t
}

; Two chained carries, both lo sums dead — the wideMultiply r1 shape:
; hiWord(zext(x) + zext(y) + zext(z)) counts the carries of the 32-bit adds.
define i32 @uaddo_dead_sum_chain(i32 %x, i32 %y, i32 %z) {
; CHECK-LABEL: uaddo_dead_sum_chain:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r4, zero
; CHECK-NEXT:    add r1, r2
; CHECK-NEXT:    mov r2, r4
; CHECK-NEXT:    adc r2, r2
; CHECK-NEXT:    add r1, r3
; CHECK-NEXT:    mov r1, r4
; CHECK-NEXT:    adc r1, zero
; CHECK-NEXT:    cmp r1, 1
; CHECK-NEXT:    adc r2, r4
; CHECK-NEXT:    mov r1, r2
; CHECK-NEXT:    jmp lr
  %xe = zext i32 %x to i64
  %ye = zext i32 %y to i64
  %ze = zext i32 %z to i64
  %s1 = add i64 %xe, %ye
  %s2 = add i64 %s1, %ze
  %hi = lshr i64 %s2, 32
  %t = trunc i64 %hi to i32
  ret i32 %t
}

; Borrow flavour: (a - b) >> 32 with the lo difference dead exercises the
; G_USUBO/G_USUBE path of the same fusion.
define i32 @usubo_dead_diff(i64 %a, i64 %b) {
; CHECK-LABEL: usubo_dead_diff:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub r1, r3
; CHECK-NEXT:    mov r1, zero
; CHECK-NEXT:    sbc r1, zero
; CHECK-NEXT:    and r1, 1
; CHECK-NEXT:    cmp zero, r1
; CHECK-NEXT:    sbc r2, r4
; CHECK-NEXT:    mov r1, r2
; CHECK-NEXT:    jmp lr
  %diff = sub i64 %a, %b
  %hi = lshr i64 %diff, 32
  %t = trunc i64 %hi to i32
  ret i32 %t
}
