; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; G_UMULO at s64 must legalize. Lowered as G_MUL + G_UMULH + ICMP_NE at s64;
; the G_MUL lands on the __muldi3 libcall, the G_UMULH narrows via
; narrowScalarMul to s32 schoolbook partial products. Reproduces the shape
; clang emits at -O2 for libcxx's __space() manual overflow check, which
; InstCombine's processUMulZExtIdiom rewrites into llvm.umul.with.overflow.i64.

declare {i64, i1} @llvm.umul.with.overflow.i64(i64, i64)

define i64 @umul_overflow_i64_clamp(i64 %a, i64 %b) {
; CHECK-LABEL: umul_overflow_i64_clamp:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub r14, 40
; CHECK-NEXT:    stw r5, [r14 + 36] // 4-byte Folded Spill
; CHECK-NEXT:    stw r6, [r14 + 32] // 4-byte Folded Spill
; CHECK-NEXT:    stw r7, [r14 + 28] // 4-byte Folded Spill
; CHECK-NEXT:    stw r8, [r14 + 24] // 4-byte Folded Spill
; CHECK-NEXT:    stw r9, [r14 + 20] // 4-byte Folded Spill
; CHECK-NEXT:    stw r10, [r14 + 16] // 4-byte Folded Spill
; CHECK-NEXT:    stw r13, [r14 + 12] // 4-byte Folded Spill
; CHECK-NEXT:    llis r11, -1
; CHECK-NEXT:    stw r11, [r14 + 8] // 4-byte Folded Spill
; CHECK-NEXT:    llis r11, -1
; CHECK-NEXT:    stw r11, [r14 + 4] // 4-byte Folded Spill
; CHECK-NEXT:    mov r5, r2
; CHECK-NEXT:    mul r5, r3
; CHECK-NEXT:    mov r7, r1
; CHECK-NEXT:    mul r7, r4
; CHECK-NEXT:    mov r6, r1
; CHECK-NEXT:    mulu r6, r3, r11
; CHECK-NEXT:    stw r11, [r14 + 0] // 4-byte Folded Spill
; CHECK-NEXT:    mov r9, r5
; CHECK-NEXT:    add r9, r7
; CHECK-NEXT:    mov r6, r0
; CHECK-NEXT:    mov r10, r6
; CHECK-NEXT:    adc r10, r0
; CHECK-NEXT:    and r10, 1
; CHECK-NEXT:    add r9, r11
; CHECK-NEXT:    mov r9, r6
; CHECK-NEXT:    adc r9, r0
; CHECK-NEXT:    and r9, 1
; CHECK-NEXT:    add r10, r9
; CHECK-NEXT:    mov r9, r2
; CHECK-NEXT:    mul r9, r4
; CHECK-NEXT:    mov r13, r2
; CHECK-NEXT:    mulu r13, r3, r11
; CHECK-NEXT:    mov r13, r1
; CHECK-NEXT:    mulu r13, r4, r8
; CHECK-NEXT:    add r9, r11
; CHECK-NEXT:    mov r11, r6
; CHECK-NEXT:    adc r11, r0
; CHECK-NEXT:    and r11, 1
; CHECK-NEXT:    add r9, r8
; CHECK-NEXT:    mov r13, r6
; CHECK-NEXT:    adc r13, r0
; CHECK-NEXT:    and r13, 1
; CHECK-NEXT:    add r11, r13
; CHECK-NEXT:    add r9, r10
; CHECK-NEXT:    mov r13, r6
; CHECK-NEXT:    adc r13, r0
; CHECK-NEXT:    and r13, 1
; CHECK-NEXT:    add r11, r13
; CHECK-NEXT:    mulu r2, r4, r4
; CHECK-NEXT:    add r4, r11
; CHECK-NEXT:    mul r1, r3
; CHECK-NEXT:    add r5, r7
; CHECK-NEXT:    ldw r2, [r14 + 0] // 4-byte Folded Reload
; CHECK-NEXT:    add r5, r2
; CHECK-NEXT:    xor r9, r6
; CHECK-NEXT:    xor r4, r6
; CHECK-NEXT:    or r9, r4
; CHECK-NEXT:    cmp r9, r6
; CHECK-NEXT:    bne .LBB0_2
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    stw r1, [r14 + 8] // 4-byte Folded Spill
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    cmp r9, r6
; CHECK-NEXT:    ldw r2, [r14 + 4] // 4-byte Folded Reload
; CHECK-NEXT:    bne .LBB0_4
; CHECK-NEXT:  // %bb.3:
; CHECK-NEXT:    mov r2, r5
; CHECK-NEXT:  .LBB0_4:
; CHECK-NEXT:    ldw r1, [r14 + 8] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r13, [r14 + 12] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r10, [r14 + 16] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r9, [r14 + 20] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r8, [r14 + 24] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r7, [r14 + 28] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r6, [r14 + 32] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r5, [r14 + 36] // 4-byte Folded Reload
; CHECK-NEXT:    add r14, 40
; CHECK-NEXT:    jmp r13
  %t = call {i64, i1} @llvm.umul.with.overflow.i64(i64 %a, i64 %b)
  %v = extractvalue {i64, i1} %t, 0
  %o = extractvalue {i64, i1} %t, 1
  %r = select i1 %o, i64 -1, i64 %v
  ret i64 %r
}

define i1 @umul_overflow_i64_flag(i64 %a, i64 %b) {
; CHECK-LABEL: umul_overflow_i64_flag:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub r14, 12
; CHECK-NEXT:    stw r5, [r14 + 8] // 4-byte Folded Spill
; CHECK-NEXT:    stw r6, [r14 + 4] // 4-byte Folded Spill
; CHECK-NEXT:    stw r13, [r14 + 0] // 4-byte Folded Spill
; CHECK-NEXT:    mov r13, r2
; CHECK-NEXT:    mul r13, r3
; CHECK-NEXT:    mov r11, r1
; CHECK-NEXT:    mul r11, r4
; CHECK-NEXT:    mov r5, r1
; CHECK-NEXT:    mulu r5, r3, r6
; CHECK-NEXT:    add r13, r11
; CHECK-NEXT:    mov r11, r0
; CHECK-NEXT:    mov r5, r11
; CHECK-NEXT:    adc r5, r0
; CHECK-NEXT:    and r5, 1
; CHECK-NEXT:    add r13, r6
; CHECK-NEXT:    mov r13, r11
; CHECK-NEXT:    adc r13, r0
; CHECK-NEXT:    and r13, 1
; CHECK-NEXT:    add r5, r13
; CHECK-NEXT:    mov r13, r2
; CHECK-NEXT:    mul r13, r4
; CHECK-NEXT:    mov r6, r2
; CHECK-NEXT:    mulu r6, r3, r3
; CHECK-NEXT:    mulu r1, r4, r6
; CHECK-NEXT:    add r13, r3
; CHECK-NEXT:    mov r1, r11
; CHECK-NEXT:    adc r1, r0
; CHECK-NEXT:    and r1, 1
; CHECK-NEXT:    add r13, r6
; CHECK-NEXT:    mov r3, r11
; CHECK-NEXT:    adc r3, r0
; CHECK-NEXT:    and r3, 1
; CHECK-NEXT:    add r1, r3
; CHECK-NEXT:    add r13, r5
; CHECK-NEXT:    mov r3, r11
; CHECK-NEXT:    adc r3, r0
; CHECK-NEXT:    and r3, 1
; CHECK-NEXT:    add r1, r3
; CHECK-NEXT:    mulu r2, r4, r3
; CHECK-NEXT:    add r3, r1
; CHECK-NEXT:    xor r13, r11
; CHECK-NEXT:    xor r3, r11
; CHECK-NEXT:    or r13, r3
; CHECK-NEXT:    lli r1, 1
; CHECK-NEXT:    lli r2, 0
; CHECK-NEXT:    cmp r13, r11
; CHECK-NEXT:    bne .LBB1_2
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    mov r1, r2
; CHECK-NEXT:  .LBB1_2:
; CHECK-NEXT:    ldw r13, [r14 + 0] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r6, [r14 + 4] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r5, [r14 + 8] // 4-byte Folded Reload
; CHECK-NEXT:    add r14, 12
; CHECK-NEXT:    jmp r13
  %t = call {i64, i1} @llvm.umul.with.overflow.i64(i64 %a, i64 %b)
  %o = extractvalue {i64, i1} %t, 1
  ret i1 %o
}
