; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra-unknown-none -global-isel < %s | FileCheck %s

; Penumbra is a strict-alignment target.  The legalizer has two jobs
; around under-aligned loads/stores, and this test locks in both:
;
;   1. Loads/stores of hardware-supported widths (s32/s16) whose
;      `align` is less than the memory size must be split into smaller
;      hardware-legal accesses by LegalizerHelper::lowerLoad/lowerStore.
;      A packed `int` at offset 5 (align 1) is the real-world trigger
;      — misaligned LDW would otherwise raise an alignment fault.
;
;   2. i64 values — which the ABI only aligns to 4 bytes, not 8 —
;      must be narrowed into two s32 halves, each preserving the
;      original alignment.  The unaligned-splitter must NOT fire on
;      the i64 load itself (treating align<size as "unaligned" for
;      s64 produces a shift/OR combine whose zero operands never get
;      folded away).

; ─── Aligned baselines (sanity: stay legal, no lowering) ────────

define i32 @load_i32_aligned(ptr %p) {
; CHECK-LABEL: load_i32_aligned:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ldw r1, [r1 + 0]
; CHECK-NEXT:    jmp lr
  %v = load i32, ptr %p, align 4
  ret i32 %v
}

define i16 @load_i16_aligned(ptr %p) {
; CHECK-LABEL: load_i16_aligned:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ldh r1, [r1 + 0]
; CHECK-NEXT:    jmp lr
  %v = load i16, ptr %p, align 2
  ret i16 %v
}

define void @store_i32_aligned(ptr %p, i32 %v) {
; CHECK-LABEL: store_i32_aligned:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    stw r2, [r1 + 0]
; CHECK-NEXT:    jmp lr
  store i32 %v, ptr %p, align 4
  ret void
}

; ─── Unaligned loads: byte-wise splitting via LegalizerHelper ───

define i32 @load_i32_align1(ptr %p) {
; CHECK-LABEL: load_i32_align1:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ldb r2, [r1 + 0]
; CHECK-NEXT:    ldb r3, [r1 + 1]
; CHECK-NEXT:    shl r3, 8
; CHECK-NEXT:    or r3, r2
; CHECK-NEXT:    ldb r2, [r1 + 2]
; CHECK-NEXT:    ldb r1, [r1 + 3]
; CHECK-NEXT:    shl r1, 8
; CHECK-NEXT:    or r1, r2
; CHECK-NEXT:    shl r1, 16
; CHECK-NEXT:    or r1, r3
; CHECK-NEXT:    jmp lr
  %v = load i32, ptr %p, align 1
  ret i32 %v
}

define i16 @load_i16_align1(ptr %p) {
; CHECK-LABEL: load_i16_align1:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ldb r2, [r1 + 0]
; CHECK-NEXT:    ldb r1, [r1 + 1]
; CHECK-NEXT:    shl r1, 8
; CHECK-NEXT:    or r1, r2
; CHECK-NEXT:    jmp lr
  %v = load i16, ptr %p, align 1
  ret i16 %v
}

; ─── Unaligned stores: byte-wise splitting via LegalizerHelper ──

define void @store_i32_align1(ptr %p, i32 %v) {
; CHECK-LABEL: store_i32_align1:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r3, r2
; CHECK-NEXT:    shr r3, 16
; CHECK-NEXT:    mov r4, r2
; CHECK-NEXT:    and r4, 65535
; CHECK-NEXT:    shr r4, 8
; CHECK-NEXT:    stb r2, [r1 + 0]
; CHECK-NEXT:    stb r4, [r1 + 1]
; CHECK-NEXT:    mov r2, r3
; CHECK-NEXT:    shr r2, 8
; CHECK-NEXT:    stb r3, [r1 + 2]
; CHECK-NEXT:    stb r2, [r1 + 3]
; CHECK-NEXT:    jmp lr
  store i32 %v, ptr %p, align 1
  ret void
}

define void @store_i16_align1(ptr %p, i16 %v) {
; CHECK-LABEL: store_i16_align1:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r3, r2
; CHECK-NEXT:    and r3, 65535
; CHECK-NEXT:    shr r3, 8
; CHECK-NEXT:    stb r2, [r1 + 0]
; CHECK-NEXT:    stb r3, [r1 + 1]
; CHECK-NEXT:    jmp lr
  store i16 %v, ptr %p, align 1
  ret void
}

; ─── Extending loads from unaligned memory ──────────────────────

define i32 @zextload_i16_align1(ptr %p) {
; CHECK-LABEL: zextload_i16_align1:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ldb r2, [r1 + 0]
; CHECK-NEXT:    ldb r1, [r1 + 1]
; CHECK-NEXT:    shl r1, 8
; CHECK-NEXT:    or r1, r2
; CHECK-NEXT:    jmp lr
  %v = load i16, ptr %p, align 1
  %ext = zext i16 %v to i32
  ret i32 %ext
}

define i32 @sextload_i16_align1(ptr %p) {
; CHECK-LABEL: sextload_i16_align1:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ldb r2, [r1 + 0]
; CHECK-NEXT:    ldbs r1, [r1 + 1]
; CHECK-NEXT:    shl r1, 8
; CHECK-NEXT:    or r1, r2
; CHECK-NEXT:    jmp lr
  %v = load i16, ptr %p, align 1
  %ext = sext i16 %v to i32
  ret i32 %ext
}

; ─── i64 with align=4: narrow to two s32 LDW, NO shift/OR chain ─
; Regression guard: ILP32 i64 only needs 4-byte alignment.  The
; unaligned-splitter must not treat "align 4 < mem 8" as unaligned —
; narrowScalar produces two clean s32 loads, not a shift-or chain.

define i64 @load_i64_align4(ptr %p) {
; CHECK-LABEL: load_i64_align4:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ldw r3, [r1 + 0]
; CHECK-NEXT:    ldw r2, [r1 + 4]
; CHECK-NEXT:    mov r1, r3
; CHECK-NEXT:    jmp lr
  %v = load i64, ptr %p, align 4
  ret i64 %v
}

define void @store_i64_align4(ptr %p, i64 %v) {
; CHECK-LABEL: store_i64_align4:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    stw r2, [r1 + 0]
; CHECK-NEXT:    stw r3, [r1 + 4]
; CHECK-NEXT:    jmp lr
  store i64 %v, ptr %p, align 4
  ret void
}

; i64 with align=1: each narrowed s32 half is itself unaligned and
; must then be byte-wise split.
define i64 @load_i64_align1(ptr %p) {
; CHECK-LABEL: load_i64_align1:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov r2, r1
; CHECK-NEXT:    ldb r1, [r2 + 0]
; CHECK-NEXT:    ldb r3, [r2 + 1]
; CHECK-NEXT:    shl r3, 8
; CHECK-NEXT:    or r3, r1
; CHECK-NEXT:    ldb r4, [r2 + 2]
; CHECK-NEXT:    ldb r1, [r2 + 3]
; CHECK-NEXT:    shl r1, 8
; CHECK-NEXT:    or r1, r4
; CHECK-NEXT:    shl r1, 16
; CHECK-NEXT:    or r1, r3
; CHECK-NEXT:    ldb r3, [r2 + 4]
; CHECK-NEXT:    ldb r4, [r2 + 5]
; CHECK-NEXT:    shl r4, 8
; CHECK-NEXT:    or r4, r3
; CHECK-NEXT:    ldb r3, [r2 + 6]
; CHECK-NEXT:    ldb r2, [r2 + 7]
; CHECK-NEXT:    shl r2, 8
; CHECK-NEXT:    or r2, r3
; CHECK-NEXT:    shl r2, 16
; CHECK-NEXT:    or r2, r4
; CHECK-NEXT:    jmp lr
  %v = load i64, ptr %p, align 1
  ret i64 %v
}
