; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; Tests varargs support: register spilling, va_start, va_arg.

declare void @llvm.va_start(ptr)
declare void @llvm.va_end(ptr)

; Simple variadic function that returns its first anonymous argument.
define i32 @first_vararg(i32 %named, ...) {
; CHECK-LABEL: first_vararg:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    sub r14, 20
; CHECK-NEXT:    stw r1, [r14 + 4]
; CHECK-NEXT:    stw r2, [r14 + 8]
; CHECK-NEXT:    stw r3, [r14 + 12]
; CHECK-NEXT:    stw r4, [r14 + 16]
; CHECK-NEXT:    mov r1, r14
; CHECK-NEXT:    add r1, 8
; CHECK-NEXT:    stw r1, [r14 + 0]
; CHECK-NEXT:    ldw r1, [r14 + 0]
; CHECK-NEXT:    lli r2, 3
; CHECK-NEXT:    add r1, r2
; CHECK-NEXT:    llis r2, -4
; CHECK-NEXT:    and r1, r2
; CHECK-NEXT:    lli r2, 4
; CHECK-NEXT:    mov r3, r1
; CHECK-NEXT:    add r3, r2
; CHECK-NEXT:    stw r3, [r14 + 0]
; CHECK-NEXT:    ldw r1, [r1 + 0]
; CHECK-NEXT:    add r14, 20
; CHECK-NEXT:    jmp r13
  %vl = alloca ptr, align 4
  call void @llvm.va_start(ptr %vl)
  %arg = va_arg ptr %vl, i32
  call void @llvm.va_end(ptr %vl)
  ret i32 %arg
}

; Variadic function with multiple named args.
define i32 @multi_named(i32 %a, i32 %b, i32 %c, ...) {
; CHECK-LABEL: multi_named:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    sub r14, 20
; CHECK-NEXT:    stw r1, [r14 + 4]
; CHECK-NEXT:    stw r2, [r14 + 8]
; CHECK-NEXT:    stw r3, [r14 + 12]
; CHECK-NEXT:    stw r4, [r14 + 16]
; CHECK-NEXT:    mov r1, r14
; CHECK-NEXT:    add r1, 16
; CHECK-NEXT:    stw r1, [r14 + 0]
; CHECK-NEXT:    ldw r1, [r14 + 0]
; CHECK-NEXT:    lli r2, 3
; CHECK-NEXT:    add r1, r2
; CHECK-NEXT:    llis r2, -4
; CHECK-NEXT:    and r1, r2
; CHECK-NEXT:    lli r2, 4
; CHECK-NEXT:    mov r3, r1
; CHECK-NEXT:    add r3, r2
; CHECK-NEXT:    stw r3, [r14 + 0]
; CHECK-NEXT:    ldw r1, [r1 + 0]
; CHECK-NEXT:    add r14, 20
; CHECK-NEXT:    jmp r13
  %vl = alloca ptr, align 4
  call void @llvm.va_start(ptr %vl)
  %arg = va_arg ptr %vl, i32
  call void @llvm.va_end(ptr %vl)
  ret i32 %arg
}
