; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; Tests varargs support: register spilling, va_start, va_arg.

declare void @llvm.va_start(ptr)
declare void @llvm.va_end(ptr)

; Simple variadic function that returns its first anonymous argument.
define i32 @first_vararg(i32 %named, ...) {
; CHECK-LABEL: first_vararg:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 20
; CHECK-NEXT:    stw r1, [sp + 4]
; CHECK-NEXT:    stw r2, [sp + 8]
; CHECK-NEXT:    stw r3, [sp + 12]
; CHECK-NEXT:    stw r4, [sp + 16]
; CHECK-NEXT:    mov r1, sp
; CHECK-NEXT:    add r1, 8
; CHECK-NEXT:    stw r1, [sp + 0]
; CHECK-NEXT:    ldw r2, [sp + 0]
; CHECK-NEXT:    ldw r1, [r2 + 0]
; CHECK-NEXT:    add r2, 4
; CHECK-NEXT:    stw r2, [sp + 0]
; CHECK-NEXT:    add sp, 20
; CHECK-NEXT:    jmp lr
  %vl = alloca ptr, align 4
  call void @llvm.va_start(ptr %vl)
  %arg = va_arg ptr %vl, i32
  call void @llvm.va_end(ptr %vl)
  ret i32 %arg
}

; Variadic function with multiple named args.
define i32 @multi_named(i32 %a, i32 %b, i32 %c, ...) {
; CHECK-LABEL: multi_named:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 20
; CHECK-NEXT:    stw r1, [sp + 4]
; CHECK-NEXT:    stw r2, [sp + 8]
; CHECK-NEXT:    stw r3, [sp + 12]
; CHECK-NEXT:    stw r4, [sp + 16]
; CHECK-NEXT:    mov r1, sp
; CHECK-NEXT:    add r1, 16
; CHECK-NEXT:    stw r1, [sp + 0]
; CHECK-NEXT:    ldw r2, [sp + 0]
; CHECK-NEXT:    ldw r1, [r2 + 0]
; CHECK-NEXT:    add r2, 4
; CHECK-NEXT:    stw r2, [sp + 0]
; CHECK-NEXT:    add sp, 20
; CHECK-NEXT:    jmp lr
  %vl = alloca ptr, align 4
  call void @llvm.va_start(ptr %vl)
  %arg = va_arg ptr %vl, i32
  call void @llvm.va_end(ptr %vl)
  ret i32 %arg
}

; Variadic function with more named args than registers (>4).
; Varargs must start past the stack-passed named args.
; 6 named i32 args: R1-R4 in regs, args 5-6 on stack (8 bytes).
; va_start should point to incoming SP+8.
define i32 @many_named(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e, i32 %f, ...) {
; CHECK-LABEL: many_named:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 20
; CHECK-NEXT:    stw r1, [sp + 4]
; CHECK-NEXT:    stw r2, [sp + 8]
; CHECK-NEXT:    stw r3, [sp + 12]
; CHECK-NEXT:    stw r4, [sp + 16]
; CHECK-NEXT:    mov r1, sp
; CHECK-NEXT:    add r1, 28
; CHECK-NEXT:    stw r1, [sp + 0]
; CHECK-NEXT:    ldw r2, [sp + 0]
; CHECK-NEXT:    ldw r1, [r2 + 0]
; CHECK-NEXT:    add r2, 4
; CHECK-NEXT:    stw r2, [sp + 0]
; CHECK-NEXT:    add sp, 20
; CHECK-NEXT:    jmp lr
  %vl = alloca ptr, align 4
  call void @llvm.va_start(ptr %vl)
  %arg = va_arg ptr %vl, i32
  call void @llvm.va_end(ptr %vl)
  ret i32 %arg
}

; Variadic function that reads an i64 argument via va_arg.
; The i64 must be read from two consecutive 4-byte slots WITHOUT
; alignment rounding — our ABI does not require 8-byte alignment
; for i64 values in varargs.
define i64 @vaarg_i64(i32 %named, ...) {
; CHECK-LABEL: vaarg_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 20
; CHECK-NEXT:    stw r1, [sp + 4]
; CHECK-NEXT:    stw r2, [sp + 8]
; CHECK-NEXT:    stw r3, [sp + 12]
; CHECK-NEXT:    stw r4, [sp + 16]
; CHECK-NEXT:    mov r1, sp
; CHECK-NEXT:    add r1, 8
; CHECK-NEXT:    stw r1, [sp + 0]
; CHECK-NEXT:    ldw r3, [sp + 0]
; CHECK-NEXT:    ldw r1, [r3 + 0]
; CHECK-NEXT:    ldw r2, [r3 + 4]
; CHECK-NEXT:    add r3, 8
; CHECK-NEXT:    stw r3, [sp + 0]
; CHECK-NEXT:    add sp, 20
; CHECK-NEXT:    jmp lr
  %vl = alloca ptr, align 4
  call void @llvm.va_start(ptr %vl)
  %arg = va_arg ptr %vl, i64
  call void @llvm.va_end(ptr %vl)
  ret i64 %arg
}

; Variadic function with i64 named args that fully consume R1-R4.
; Two i64 named args take R1:R2 and R3:R4 (16 bytes of register state),
; so va_start must point past the entire save area to incoming SP+0.
; A naive implementation using SplitArgs.size() * 4 would give 2*4 = 8
; bytes of named-reg-width, offsetting va_start by -8 into the save
; area (middle of the second i64).
define i32 @wide_named_all_regs(i64 %a, i64 %b, ...) {
; CHECK-LABEL: wide_named_all_regs:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 20
; CHECK-NEXT:    stw r1, [sp + 4]
; CHECK-NEXT:    stw r2, [sp + 8]
; CHECK-NEXT:    stw r3, [sp + 12]
; CHECK-NEXT:    stw r4, [sp + 16]
; CHECK-NEXT:    mov r1, sp
; CHECK-NEXT:    add r1, 20
; CHECK-NEXT:    stw r1, [sp + 0]
; CHECK-NEXT:    ldw r2, [sp + 0]
; CHECK-NEXT:    ldw r1, [r2 + 0]
; CHECK-NEXT:    add r2, 4
; CHECK-NEXT:    stw r2, [sp + 0]
; CHECK-NEXT:    add sp, 20
; CHECK-NEXT:    jmp lr
  %vl = alloca ptr, align 4
  call void @llvm.va_start(ptr %vl)
  %arg = va_arg ptr %vl, i32
  call void @llvm.va_end(ptr %vl)
  ret i32 %arg
}

; Variadic function with >4 named args including an i64.
; The i64 occupies two 4-byte stack slots.  va_start must account
; for the actual stack bytes, not just the number of IR arguments.
; 6 IR args: R1-R4 in regs, i64 on stack (8 bytes), i32 on stack (4 bytes).
; Total stack-passed = 12 bytes.  va_start should point to incoming SP+12.
define i32 @many_named_i64(i32 %a, i32 %b, i32 %c, i32 %d, i64 %e, i32 %f, ...) {
; CHECK-LABEL: many_named_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 20
; CHECK-NEXT:    stw r1, [sp + 4]
; CHECK-NEXT:    stw r2, [sp + 8]
; CHECK-NEXT:    stw r3, [sp + 12]
; CHECK-NEXT:    stw r4, [sp + 16]
; CHECK-NEXT:    mov r1, sp
; CHECK-NEXT:    add r1, 32
; CHECK-NEXT:    stw r1, [sp + 0]
; CHECK-NEXT:    ldw r2, [sp + 0]
; CHECK-NEXT:    ldw r1, [r2 + 0]
; CHECK-NEXT:    add r2, 4
; CHECK-NEXT:    stw r2, [sp + 0]
; CHECK-NEXT:    add sp, 20
; CHECK-NEXT:    jmp lr
  %vl = alloca ptr, align 4
  call void @llvm.va_start(ptr %vl)
  %arg = va_arg ptr %vl, i32
  call void @llvm.va_end(ptr %vl)
  ret i32 %arg
}
