; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=penumbra-unknown-none -global-isel < %s | FileCheck %s

; Penumbra has no vector unit, but accepts GCC __attribute__((vector_size))
; and OpenCL vector types in C source, plus the IR optimizer may
; auto-vectorize.  The legalizer scalarizes every vector op into
; per-element scalar ops so code compiles correctly (just unrolled),
; rather than triggering a backend fatal error.

define void @vector_add(ptr %dst, ptr %a, ptr %b) {
; CHECK-LABEL: vector_add:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 16
; CHECK-NEXT:    stw r5, [sp + 12] // 4-byte Folded Spill
; CHECK-NEXT:    stw r6, [sp + 8] // 4-byte Folded Spill
; CHECK-NEXT:    stw r7, [sp + 4] // 4-byte Folded Spill
; CHECK-NEXT:    stw r8, [sp + 0] // 4-byte Folded Spill
; CHECK-NEXT:    ldw r4, [r2 + 0]
; CHECK-NEXT:    ldw r11, [r2 + 4]
; CHECK-NEXT:    ldw r5, [r2 + 8]
; CHECK-NEXT:    ldw r2, [r2 + 12]
; CHECK-NEXT:    ldw r6, [r3 + 0]
; CHECK-NEXT:    ldw r7, [r3 + 4]
; CHECK-NEXT:    ldw r8, [r3 + 8]
; CHECK-NEXT:    ldw r3, [r3 + 12]
; CHECK-NEXT:    add r4, r6
; CHECK-NEXT:    add r11, r7
; CHECK-NEXT:    add r5, r8
; CHECK-NEXT:    add r2, r3
; CHECK-NEXT:    stw r4, [r1 + 0]
; CHECK-NEXT:    stw r11, [r1 + 4]
; CHECK-NEXT:    stw r5, [r1 + 8]
; CHECK-NEXT:    stw r2, [r1 + 12]
; CHECK-NEXT:    ldw r8, [sp + 0] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r7, [sp + 4] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r6, [sp + 8] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r5, [sp + 12] // 4-byte Folded Reload
; CHECK-NEXT:    add sp, 16
; CHECK-NEXT:    jmp lr
  %va = load <4 x i32>, ptr %a
  %vb = load <4 x i32>, ptr %b
  %sum = add <4 x i32> %va, %vb
  store <4 x i32> %sum, ptr %dst
  ret void
}

define void @vector_mul(ptr %dst, ptr %a, ptr %b) {
; CHECK-LABEL: vector_mul:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ldw r4, [r2 + 0]
; CHECK-NEXT:    ldw r2, [r2 + 4]
; CHECK-NEXT:    ldw r11, [r3 + 0]
; CHECK-NEXT:    ldw r3, [r3 + 4]
; CHECK-NEXT:    mul r4, r11
; CHECK-NEXT:    mul r2, r3
; CHECK-NEXT:    stw r4, [r1 + 0]
; CHECK-NEXT:    stw r2, [r1 + 4]
; CHECK-NEXT:    jmp lr
  %va = load <2 x i32>, ptr %a
  %vb = load <2 x i32>, ptr %b
  %prod = mul <2 x i32> %va, %vb
  store <2 x i32> %prod, ptr %dst
  ret void
}

define void @vector_shl(ptr %dst, ptr %a, ptr %b) {
; CHECK-LABEL: vector_shl:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 16
; CHECK-NEXT:    stw r5, [sp + 12] // 4-byte Folded Spill
; CHECK-NEXT:    stw r6, [sp + 8] // 4-byte Folded Spill
; CHECK-NEXT:    stw r7, [sp + 4] // 4-byte Folded Spill
; CHECK-NEXT:    stw r8, [sp + 0] // 4-byte Folded Spill
; CHECK-NEXT:    ldh r4, [r2 + 0]
; CHECK-NEXT:    ldh r11, [r2 + 2]
; CHECK-NEXT:    ldh r5, [r2 + 4]
; CHECK-NEXT:    ldh r2, [r2 + 6]
; CHECK-NEXT:    ldh r6, [r3 + 0]
; CHECK-NEXT:    ldh r7, [r3 + 2]
; CHECK-NEXT:    ldh r8, [r3 + 4]
; CHECK-NEXT:    ldh r3, [r3 + 6]
; CHECK-NEXT:    shl r4, r6
; CHECK-NEXT:    shl r11, r7
; CHECK-NEXT:    shl r5, r8
; CHECK-NEXT:    shl r2, r3
; CHECK-NEXT:    sth r4, [r1 + 0]
; CHECK-NEXT:    sth r11, [r1 + 2]
; CHECK-NEXT:    sth r5, [r1 + 4]
; CHECK-NEXT:    sth r2, [r1 + 6]
; CHECK-NEXT:    ldw r8, [sp + 0] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r7, [sp + 4] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r6, [sp + 8] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r5, [sp + 12] // 4-byte Folded Reload
; CHECK-NEXT:    add sp, 16
; CHECK-NEXT:    jmp lr
  %va = load <4 x i16>, ptr %a
  %vb = load <4 x i16>, ptr %b
  %shifted = shl <4 x i16> %va, %vb
  store <4 x i16> %shifted, ptr %dst
  ret void
}

define void @vector_select(ptr %dst, ptr %a, ptr %b, i1 %c) {
; CHECK-LABEL: vector_select:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sub sp, 20
; CHECK-NEXT:    stw r5, [sp + 16] // 4-byte Folded Spill
; CHECK-NEXT:    stw r6, [sp + 12] // 4-byte Folded Spill
; CHECK-NEXT:    stw r7, [sp + 8] // 4-byte Folded Spill
; CHECK-NEXT:    stw r8, [sp + 4] // 4-byte Folded Spill
; CHECK-NEXT:    stw r9, [sp + 0] // 4-byte Folded Spill
; CHECK-NEXT:    ldw r11, [r2 + 0]
; CHECK-NEXT:    ldw r5, [r2 + 4]
; CHECK-NEXT:    ldw r6, [r2 + 8]
; CHECK-NEXT:    ldw r2, [r2 + 12]
; CHECK-NEXT:    ldw r9, [r3 + 0]
; CHECK-NEXT:    ldw r8, [r3 + 4]
; CHECK-NEXT:    ldw r7, [r3 + 8]
; CHECK-NEXT:    ldw r3, [r3 + 12]
; CHECK-NEXT:    test r4, 1
; CHECK-NEXT:    beq .LBB3_1
; CHECK-NEXT:  // %bb.2:
; CHECK-NEXT:    test r4, 1
; CHECK-NEXT:    beq .LBB3_3
; CHECK-NEXT:  .LBB3_4:
; CHECK-NEXT:    test r4, 1
; CHECK-NEXT:    beq .LBB3_5
; CHECK-NEXT:  .LBB3_6:
; CHECK-NEXT:    test r4, 1
; CHECK-NEXT:    bne .LBB3_8
; CHECK-NEXT:  .LBB3_7:
; CHECK-NEXT:    mov r2, r3
; CHECK-NEXT:  .LBB3_8:
; CHECK-NEXT:    stw r11, [r1 + 0]
; CHECK-NEXT:    stw r5, [r1 + 4]
; CHECK-NEXT:    stw r6, [r1 + 8]
; CHECK-NEXT:    stw r2, [r1 + 12]
; CHECK-NEXT:    ldw r9, [sp + 0] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r8, [sp + 4] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r7, [sp + 8] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r6, [sp + 12] // 4-byte Folded Reload
; CHECK-NEXT:    ldw r5, [sp + 16] // 4-byte Folded Reload
; CHECK-NEXT:    add sp, 20
; CHECK-NEXT:    jmp lr
; CHECK-NEXT:  .LBB3_1:
; CHECK-NEXT:    mov r11, r9
; CHECK-NEXT:    test r4, 1
; CHECK-NEXT:    bne .LBB3_4
; CHECK-NEXT:  .LBB3_3:
; CHECK-NEXT:    mov r5, r8
; CHECK-NEXT:    test r4, 1
; CHECK-NEXT:    bne .LBB3_6
; CHECK-NEXT:  .LBB3_5:
; CHECK-NEXT:    mov r6, r7
; CHECK-NEXT:    test r4, 1
; CHECK-NEXT:    beq .LBB3_7
; CHECK-NEXT:    b .LBB3_8
  %va = load <4 x i32>, ptr %a
  %vb = load <4 x i32>, ptr %b
  %sel = select i1 %c, <4 x i32> %va, <4 x i32> %vb
  store <4 x i32> %sel, ptr %dst
  ret void
}
