; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; Store of constant zero should use R0 directly, not materialize with LLI.
define void @store_zero_word(ptr %p) {
; CHECK-LABEL: store_zero_word:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    stw zero, [r1 + 0]
; CHECK-NEXT:    jmp lr
  store i32 0, ptr %p, align 4
  ret void
}

define void @store_zero_byte(ptr %p) {
; CHECK-LABEL: store_zero_byte:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    stb zero, [r1 + 0]
; CHECK-NEXT:    jmp lr
  store i8 0, ptr %p, align 1
  ret void
}

define void @store_zero_half(ptr %p) {
; CHECK-LABEL: store_zero_half:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    sth zero, [r1 + 0]
; CHECK-NEXT:    jmp lr
  store i16 0, ptr %p, align 2
  ret void
}

; Non-zero store should NOT use R0.
define void @store_nonzero(ptr %p) {
; CHECK-LABEL: store_nonzero:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    lli r2, 42
; CHECK-NEXT:    stw r2, [r1 + 0]
; CHECK-NEXT:    jmp lr
  store i32 42, ptr %p, align 4
  ret void
}
