; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=penumbra -global-isel -verify-machineinstrs -O2 < %s \
; RUN:   | FileCheck %s

; Penumbra's LDB/LDH always zero-extend in hardware.  The post-legalizer
; combiner `penumbra_zextload_promote` rewrites plain `G_LOAD :: (load sX)
; -> sY` (where sX < sY) to `G_ZEXTLOAD`, which lets `redundant_and` drop
; the `G_AND %, 0xFF` masks the legalizer emits when widening the operands
; of an unsigned / eq / ne `G_ICMP` whose source type is sub-word.  See
; PenumbraCombine.td and PenumbraPostLegalizerCombiner.cpp.

;; strcmp-shaped loop: byte loaded into a value that flows through a PHI
;; into both an icmp (`*a == *b`) and the next iteration's PHI input.  The
;; load has multiple uses, so upstream's `load_and_mask` combine bails;
;; our target rule turns the LOAD into a ZEXTLOAD up front and the masks
;; dissolve via `redundant_and`.  No `and rN, 255` should appear anywhere
;; in this function.
define i32 @strcmp_like(ptr %a, ptr %b) {
; CHECK-LABEL: strcmp_like:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    ldb r4, [r1 + 0]
; CHECK-NEXT:    mov r3, zero
; CHECK-NEXT:    cmp r4, 0
; CHECK-NEXT:    beq .LBB0_5
; CHECK-NEXT:  // %bb.1: // %loop.preheader
; CHECK-NEXT:    add r1, 1
; CHECK-NEXT:  .LBB0_2: // %loop
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ldb r3, [r2 + 0]
; CHECK-NEXT:    cmp r4, r3
; CHECK-NEXT:    bne .LBB0_3
; CHECK-NEXT:  // %bb.4: // %loop.next
; CHECK-NEXT:    // in Loop: Header=BB0_2 Depth=1
; CHECK-NEXT:    add r2, 1
; CHECK-NEXT:    ldb r4, [r1 + 0]
; CHECK-NEXT:    mov r3, zero
; CHECK-NEXT:    add r1, 1
; CHECK-NEXT:    cmp r4, 0
; CHECK-NEXT:    bne .LBB0_2
; CHECK-NEXT:    b .LBB0_5
; CHECK-NEXT:  .LBB0_3:
; CHECK-NEXT:    mov r3, r4
; CHECK-NEXT:  .LBB0_5: // %exit
; CHECK-NEXT:    ldb r1, [r2 + 0]
; CHECK-NEXT:    sub r3, r1
; CHECK-NEXT:    mov r1, r3
; CHECK-NEXT:    jmp lr
entry:
  %a0 = load i8, ptr %a
  %a0z = zext i8 %a0 to i32
  %a0nz = icmp ne i32 %a0z, 0
  br i1 %a0nz, label %loop, label %exit
loop:
  %ap = phi ptr [ %a, %entry ], [ %ap.next, %loop.next ]
  %bp = phi ptr [ %b, %entry ], [ %bp.next, %loop.next ]
  %av = phi i8  [ %a0, %entry ], [ %av.next, %loop.next ]
  %bv = load i8, ptr %bp
  %eq = icmp eq i8 %av, %bv
  br i1 %eq, label %loop.next, label %exit
loop.next:
  %ap.next = getelementptr i8, ptr %ap, i32 1
  %bp.next = getelementptr i8, ptr %bp, i32 1
  %av.next = load i8, ptr %ap.next
  %nz = icmp ne i8 %av.next, 0
  br i1 %nz, label %loop, label %exit
exit:
  %lhs = phi i8 [ 0, %entry ], [ %av, %loop ], [ 0, %loop.next ]
  %rhs.ptr = phi ptr [ %b, %entry ], [ %bp, %loop ], [ %bp.next, %loop.next ]
  %lhs.z = zext i8 %lhs to i32
  %rhs = load i8, ptr %rhs.ptr
  %rhs.z = zext i8 %rhs to i32
  %r = sub nsw i32 %lhs.z, %rhs.z
  ret i32 %r
}

;; Negative: a *signed* comparison against zero on the loaded byte means
;; the legalizer widens with G_SEXT.  Our match guard skips promotion
;; when a direct user is G_SEXT/G_SEXT_INREG so upstream's `extending_loads`
;; combine can still fold single-use sext-of-load to G_SEXTLOAD where it
;; applies.  The whole-loop signed case (PHI-mediated) is still suboptimal
;; and tracked in doc/TODO.md; this test only pins the single-use path so
;; we don't break it.
define i32 @signed_byte(ptr %p) {
; CHECK-LABEL: signed_byte:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ldbs r1, [r1 + 0]
; CHECK-NEXT:    jmp lr
  %v = load i8, ptr %p
  %z = sext i8 %v to i32
  ret i32 %z
}
