# $NetBSD$

# Penumbra minicomputer: serial console + SD block device + USB
# (pusbhc controller with umass -> sd disks).

init)
	makedev std ld0 ld1
	makedev tty00
	makedev bpf
	makedev random
	makedev md0
	makedev ipty
	makedev local
	makedev sd0 sd1
	makedev usb usb0
	;;

all_md)
	makedev tty00 tty01
	makedev ld0 ld1
	makedev sd0 sd1
	makedev usb usb0
	;;

minimal)
	makedev std ld0
	makedev tty00
	;;
