MKX11=no
MKLLVM=no
MKGDB=no
MKMAN=no
MKHTML=no
MKDTRACE=no
MKZFS=no
MKDEBUG=no
MKREPRO=no
MKRUMP=no
MKPAM=no

# Tolerate missing files in checkflist (binutils not built, rtld not yet ported)
SLOPPY_FLIST=yes
