#	$NetBSD$
#
# Makefile for NetBSD/penumbra kernels.
#
# This makefile is constructed from a machine description:
#	config machineid
# Most changes should be made in the machine description
#	/sys/arch/penumbra/conf/``machineid''
# after which you should do
#	config machineid
# Machine generic makefile changes should be made in
#	/sys/arch/penumbra/conf/Makefile.penumbra
# after which config should be rerun for all machines of that type.

USETOOLS?=	no
NEED_OWN_INSTALL_TARGET?=no
.include <bsd.own.mk>

##
## (1) port identification
##
.ifndef S
S=		../../../..
.endif
PENUMBRA=	$S/arch/penumbra
GENASSYM_CONF=	${PENUMBRA}/penumbra/genassym.cf

##
## (2) compile settings
##
# Add compiler resource dir for freestanding headers (limits.h, stdint.h, etc.)
# needed because -nostdinc strips the compiler's built-in include path.
COMPILER_RESOURCE_DIR!=	${CC} -print-resource-dir
CPPFLAGS+=	-Dpenumbra -D__NetBSD__ -isystem ${COMPILER_RESOURCE_DIR}/include
CFLAGS+=	-ffreestanding -Wno-unused-command-line-argument
AFLAGS+=	-x assembler-with-cpp

##
## (3) libkern and compat
##
OPT_MODULAR=	%MODULAR%

##
## (4) local objects, compile rules, and dependencies
##
MD_OBJS=	locore.o
MD_CFILES=
MD_SFILES=	${PENUMBRA}/penumbra/locore.S

locore.o: ${PENUMBRA}/penumbra/locore.S assym.h
	${NORMAL_S}

##
## (5) link settings
##
TEXTADDR?=	${DEFTEXTADDR}
KERNLDSCRIPT?=	${PENUMBRA}/conf/kern.ldscript
EXTRA_LINKFLAGS=
LINKFLAGS_NORMAL=	-X
OBJCOPY_STRIPFLAGS=	-g -X

##
## (6) port specific target dependencies
##

# depend on configuration
machdep.o trap.o: Makefile

# assembly files that depend on assym.h
locore.o: assym.h

##
## (7) misc settings
##

##
## (8) config(8) generated machinery
##
%INCLUDES

%OBJS

%CFILES

%SFILES

%LOAD

%RULES

##
## (9) port independent kernel machinery
##
.include "$S/conf/Makefile.kern.inc"

##
## (10) Appending make options.
##
%MAKEOPTIONSAPPEND
