// Penumbra USB host MAC test wrapper (simulation DUT)
//
// usbhc_mac with a short frame period and connect debounce so the
// testbench can exercise many frame boundaries and attach cycles in a
// fast run. Pure pass-through otherwise.

module usbhc_mac_test (
    input  logic        i_clk,
    input  logic        i_rst,
    input  logic        i_start,
    input  logic [1:0]  i_pid_sel,
    input  logic [6:0]  i_devaddr,
    input  logic [3:0]  i_endpoint,
    input  logic        i_toggle,
    input  logic [6:0]  i_length,
    output logic        o_busy,
    output logic        o_done,
    output logic [2:0]  o_result,
    output logic [6:0]  o_rxlen,
    output logic        o_rxtoggle,
    input  logic        i_run,
    input  logic        i_power,
    input  logic        i_reset,
    input  logic        i_suspend,
    input  logic        i_resume,
    output logic        o_connect,
    output logic        o_enabled,
    output logic        o_reset_active,
    output logic        o_suspended,
    output logic [1:0]  o_port_speed,
    output logic [1:0]  o_port_line,
    output logic        o_port_change,
    output logic        o_sof_irq,
    output logic [10:0] o_frame,
    output logic [6:0]  o_buf_raddr,
    input  logic [7:0]  i_buf_rdata,
    output logic [6:0]  o_buf_waddr,
    output logic [7:0]  o_buf_wdata,
    output logic        o_buf_we,
    output logic [7:0]  o_tx_data,
    output logic        o_tx_valid,
    input  logic        i_tx_ready,
    input  logic [7:0]  i_rx_data,
    input  logic        i_rx_valid,
    input  logic        i_rx_active,
    input  logic        i_rx_error,
    input  logic [1:0]  i_line_state,
    input  logic [2:0]  i_caps,
    output logic [1:0]  o_xcvr_sel,
    output logic        o_term_sel,
    output logic [1:0]  o_opmode,
    output logic        o_port_power
);
    usbhc_mac #(
        .CLKS_PER_MS   (4000),
        .DEBOUNCE_CLKS (30)
    ) u_mac (
        .i_clk          (i_clk),
        .i_rst          (i_rst),
        .i_start        (i_start),
        .i_pid_sel      (i_pid_sel),
        .i_devaddr      (i_devaddr),
        .i_endpoint     (i_endpoint),
        .i_toggle       (i_toggle),
        .i_length       (i_length),
        .o_busy         (o_busy),
        .o_done         (o_done),
        .o_result       (o_result),
        .o_rxlen        (o_rxlen),
        .o_rxtoggle     (o_rxtoggle),
        .i_run          (i_run),
        .i_power        (i_power),
        .i_reset        (i_reset),
        .i_suspend      (i_suspend),
        .i_resume       (i_resume),
        .o_connect      (o_connect),
        .o_enabled      (o_enabled),
        .o_reset_active (o_reset_active),
        .o_suspended    (o_suspended),
        .o_port_speed   (o_port_speed),
        .o_port_line    (o_port_line),
        .o_port_change  (o_port_change),
        .o_sof_irq      (o_sof_irq),
        .o_frame        (o_frame),
        .o_buf_raddr    (o_buf_raddr),
        .i_buf_rdata    (i_buf_rdata),
        .o_buf_waddr    (o_buf_waddr),
        .o_buf_wdata    (o_buf_wdata),
        .o_buf_we       (o_buf_we),
        .o_tx_data      (o_tx_data),
        .o_tx_valid     (o_tx_valid),
        .i_tx_ready     (i_tx_ready),
        .i_rx_data      (i_rx_data),
        .i_rx_valid     (i_rx_valid),
        .i_rx_active    (i_rx_active),
        .i_rx_error     (i_rx_error),
        .i_line_state   (i_line_state),
        .i_caps         (i_caps),
        .o_xcvr_sel     (o_xcvr_sel),
        .o_term_sel     (o_term_sel),
        .o_opmode       (o_opmode),
        .o_port_power   (o_port_power)
    );
endmodule
