# $NetBSD$

INCSDIR= /usr/include/penumbra

INCS=	ansi.h aout_machdep.h asm.h \
	bootinfo.h bswap.h bus_defs.h bus_funcs.h byte_swap.h \
	cdefs.h cpu.h cpu_counter.h \
	db_machdep.h disklabel.h \
	elf_machdep.h endian.h endian_machdep.h \
	fenv.h float.h frame.h \
	ieee.h ieeefp.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	intr.h \
	kcore.h \
	limits.h loadfile_machdep.h lock.h \
	math.h \
	mcontext.h mutex.h \
	param.h pbbus.h pcb.h pmap.h \
	proc.h profile.h psl.h ptrace.h \
	reg.h rwlock.h \
	setjmp.h signal.h sysreg.h \
	types.h \
	userret.h \
	vmparam.h \
	wchar_limits.h

.include <bsd.kinc.mk>
