#!/usr/bin/env python3
"""Convert a raw binary file to $readmemh hex format.

Pipeline:  llvm-mc -filetype=obj → llvm-objcopy -O binary → bin2hex.py

Usage:
    python3 bin2hex.py input.bin -o output.hex
"""

import argparse
import struct
import sys


def main():
    parser = argparse.ArgumentParser(
        description="Convert raw binary to $readmemh hex format")
    parser.add_argument("input", help="Input binary file")
    parser.add_argument("-o", "--output", required=True,
                        help="Output hex file")
    args = parser.parse_args()

    with open(args.input, "rb") as f:
        data = f.read()

    # Pad to word boundary if needed.
    padding_needed = (4 - len(data) % 4) % 4
    data = data + b'\x00' * padding_needed

    n_words = len(data) // 4
    with open(args.output, "w") as f:
        f.write("// Penumbra program \u2014 generated by bin2hex.py\n\n")
        for i in range(n_words):
            word, = struct.unpack_from('<I', data, i * 4)
            f.write(f"{word:08X}\n")

    print(f"bin2hex: {n_words} words -> {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
