# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=penumbra -run-pass=penumbra-postlegalizer-combiner %s -o - \
# RUN:   | FileCheck %s

# A G_MUL and a G_[SU]MULH over the same operands fuse into one two-result
# G_[SU]MUL_LOHI, which selects to a single MUL_P / MULU_P.  Operand order
# does not matter (multiplication commutes), but the two must be in the same
# block: the fused instruction is placed at whichever comes first, which only
# dominates the other's uses within one block.

---
name:            unsigned_pair
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r1, $r2
    ; CHECK-LABEL: name: unsigned_pair
    ; CHECK: liveins: $r1, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r2
    ; CHECK-NEXT: [[UMUL_LOHI:%[0-9]+]]:_(s32), [[UMUL_LOHI1:%[0-9]+]]:_ = G_UMUL_LOHI [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $r1 = COPY [[UMUL_LOHI]](s32)
    ; CHECK-NEXT: $r2 = COPY [[UMUL_LOHI1]](s32)
    ; CHECK-NEXT: RET implicit $r1, implicit $r2
    %0:_(s32) = COPY $r1
    %1:_(s32) = COPY $r2
    %2:_(s32) = G_MUL %0, %1
    %3:_(s32) = G_UMULH %0, %1
    $r1 = COPY %2(s32)
    $r2 = COPY %3(s32)
    RET implicit $r1, implicit $r2
...
---
name:            signed_pair
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r1, $r2
    ; CHECK-LABEL: name: signed_pair
    ; CHECK: liveins: $r1, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r2
    ; CHECK-NEXT: [[SMUL_LOHI:%[0-9]+]]:_(s32), [[SMUL_LOHI1:%[0-9]+]]:_ = G_SMUL_LOHI [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $r1 = COPY [[SMUL_LOHI]](s32)
    ; CHECK-NEXT: $r2 = COPY [[SMUL_LOHI1]](s32)
    ; CHECK-NEXT: RET implicit $r1, implicit $r2
    %0:_(s32) = COPY $r1
    %1:_(s32) = COPY $r2
    %2:_(s32) = G_MUL %0, %1
    %3:_(s32) = G_SMULH %0, %1
    $r1 = COPY %2(s32)
    $r2 = COPY %3(s32)
    RET implicit $r1, implicit $r2
...
---
name:            commuted_operands
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r1, $r2
    ; CHECK-LABEL: name: commuted_operands
    ; CHECK: liveins: $r1, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r2
    ; CHECK-NEXT: [[UMUL_LOHI:%[0-9]+]]:_(s32), [[UMUL_LOHI1:%[0-9]+]]:_ = G_UMUL_LOHI [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $r1 = COPY [[UMUL_LOHI]](s32)
    ; CHECK-NEXT: $r2 = COPY [[UMUL_LOHI1]](s32)
    ; CHECK-NEXT: RET implicit $r1, implicit $r2
    %0:_(s32) = COPY $r1
    %1:_(s32) = COPY $r2
    %2:_(s32) = G_MUL %1, %0
    %3:_(s32) = G_UMULH %0, %1
    $r1 = COPY %2(s32)
    $r2 = COPY %3(s32)
    RET implicit $r1, implicit $r2
...
---
name:            squared
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r1
    ; CHECK-LABEL: name: squared
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[SMUL_LOHI:%[0-9]+]]:_(s32), [[SMUL_LOHI1:%[0-9]+]]:_ = G_SMUL_LOHI [[COPY]], [[COPY]]
    ; CHECK-NEXT: $r1 = COPY [[SMUL_LOHI]](s32)
    ; CHECK-NEXT: $r2 = COPY [[SMUL_LOHI1]](s32)
    ; CHECK-NEXT: RET implicit $r1, implicit $r2
    %0:_(s32) = COPY $r1
    %1:_(s32) = G_MUL %0, %0
    %2:_(s32) = G_SMULH %0, %0
    $r1 = COPY %1(s32)
    $r2 = COPY %2(s32)
    RET implicit $r1, implicit $r2
...
---
name:            different_operands_not_fused
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r1, $r2, $r3
    ; CHECK-LABEL: name: different_operands_not_fused
    ; CHECK: liveins: $r1, $r2, $r3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r3
    ; CHECK-NEXT: [[MUL:%[0-9]+]]:_(s32) = G_MUL [[COPY]], [[COPY2]]
    ; CHECK-NEXT: [[UMULH:%[0-9]+]]:_(s32) = G_UMULH [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $r1 = COPY [[MUL]](s32)
    ; CHECK-NEXT: $r2 = COPY [[UMULH]](s32)
    ; CHECK-NEXT: RET implicit $r1, implicit $r2
    %0:_(s32) = COPY $r1
    %1:_(s32) = COPY $r2
    %2:_(s32) = COPY $r3
    %3:_(s32) = G_MUL %0, %2
    %4:_(s32) = G_UMULH %0, %1
    $r1 = COPY %3(s32)
    $r2 = COPY %4(s32)
    RET implicit $r1, implicit $r2
...
---
name:            cross_block_not_fused
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: cross_block_not_fused
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $r1, $r2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r2
  ; CHECK-NEXT:   [[MUL:%[0-9]+]]:_(s32) = G_MUL [[COPY]], [[COPY1]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   [[UMULH:%[0-9]+]]:_(s32) = G_UMULH [[COPY]], [[COPY1]]
  ; CHECK-NEXT:   $r1 = COPY [[MUL]](s32)
  ; CHECK-NEXT:   $r2 = COPY [[UMULH]](s32)
  ; CHECK-NEXT:   RET implicit $r1, implicit $r2
  bb.0:
    liveins: $r1, $r2
    %0:_(s32) = COPY $r1
    %1:_(s32) = COPY $r2
    %2:_(s32) = G_MUL %0, %1

  bb.1:
    %3:_(s32) = G_UMULH %0, %1
    $r1 = COPY %2(s32)
    $r2 = COPY %3(s32)
    RET implicit $r1, implicit $r2
...
