# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=penumbra-unknown-none -run-pass=instruction-select -verify-machineinstrs %s -o - | FileCheck %s

# Selection of G_ICMP + G_SELECT into the SELECT_CC pseudos: a uimm16-constant
# compare operand folds into the immediate form (SELECT_CCi_GPR), with a
# constant LHS canonicalized to the RHS by swapping the predicate's operand
# order.  See emitSelectCC / canonicalizeCompareOperands in
# PenumbraInstructionSelector.cpp.  The upstream commute_constant_to_rhs
# combine usually commutes constants before selection at -O1+; this pins the
# selection-time canonicalization that covers -O0 and combiner gaps.
#
# The pseudos' trailing cc operand is a raw Penumbra branch opcode number
# (regenerate CHECK lines if instruction definitions renumber).  What matters
# below is that the swapped case picks a *different* branch than the
# unswapped one: BLT for slt(a, 100) vs BGT for slt(100, a).

--- |
  define void @select_imm_rhs() { ret void }
  define void @select_imm_lhs_swaps_predicate() { ret void }
  define void @select_imm_too_wide() { ret void }
...

# Constant RHS in range: immediate pseudo, predicate unchanged (slt).
---
name:            select_imm_rhs
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $r1, $r2, $r3
    ; CHECK-LABEL: name: select_imm_rhs
    ; CHECK: liveins: $r1, $r2, $r3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr_allocatable = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr_allocatable = COPY $r2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gpr_allocatable = COPY $r3
    ; CHECK-NEXT: [[SELECT_CCi_GPR:%[0-9]+]]:gpr = SELECT_CCi_GPR [[COPY1]], [[COPY2]], [[COPY]], 100, 353, implicit-def $sr
    ; CHECK-NEXT: $r1 = COPY [[SELECT_CCi_GPR]]
    ; CHECK-NEXT: RET implicit $r1
    %0:gprbank(s32) = COPY $r1
    %1:gprbank(s32) = COPY $r2
    %2:gprbank(s32) = COPY $r3
    %3:gprbank(s32) = G_CONSTANT i32 100
    %4:gprbank(s1) = G_ICMP intpred(slt), %0(s32), %3
    %5:gprbank(s32) = G_SELECT %4(s1), %1, %2
    $r1 = COPY %5(s32)
    RET implicit $r1
...

# Constant LHS with an asymmetric predicate: operands swap so the constant
# folds, and the predicate swaps with them — slt(100, a) is gt(a, 100), so the
# cc operand must encode BGT.  (BGE here would be the swapped-vs-inverse
# predicate confusion.)
---
name:            select_imm_lhs_swaps_predicate
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $r1, $r2, $r3
    ; CHECK-LABEL: name: select_imm_lhs_swaps_predicate
    ; CHECK: liveins: $r1, $r2, $r3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr_allocatable = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr_allocatable = COPY $r2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gpr_allocatable = COPY $r3
    ; CHECK-NEXT: [[SELECT_CCi_GPR:%[0-9]+]]:gpr = SELECT_CCi_GPR [[COPY1]], [[COPY2]], [[COPY]], 100, 348, implicit-def $sr
    ; CHECK-NEXT: $r1 = COPY [[SELECT_CCi_GPR]]
    ; CHECK-NEXT: RET implicit $r1
    %0:gprbank(s32) = COPY $r1
    %1:gprbank(s32) = COPY $r2
    %2:gprbank(s32) = COPY $r3
    %3:gprbank(s32) = G_CONSTANT i32 100
    %4:gprbank(s1) = G_ICMP intpred(slt), %3(s32), %0
    %5:gprbank(s32) = G_SELECT %4(s1), %1, %2
    $r1 = COPY %5(s32)
    RET implicit $r1
...

# Constant wider than uimm16: register pseudo, constant materialised normally.
---
name:            select_imm_too_wide
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $r1, $r2, $r3
    ; CHECK-LABEL: name: select_imm_too_wide
    ; CHECK: liveins: $r1, $r2, $r3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr_allocatable = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr_allocatable = COPY $r2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gpr_allocatable = COPY $r3
    ; CHECK-NEXT: [[LLI:%[0-9]+]]:gpr_allocatable = LLI 4464
    ; CHECK-NEXT: [[LUI:%[0-9]+]]:gpr = LUI [[LLI]], 1
    ; CHECK-NEXT: [[SELECT_CC_GPR:%[0-9]+]]:gpr = SELECT_CC_GPR [[COPY1]], [[COPY2]], [[COPY]], [[LUI]], 353, implicit-def $sr
    ; CHECK-NEXT: $r1 = COPY [[SELECT_CC_GPR]]
    ; CHECK-NEXT: RET implicit $r1
    %0:gprbank(s32) = COPY $r1
    %1:gprbank(s32) = COPY $r2
    %2:gprbank(s32) = COPY $r3
    %3:gprbank(s32) = G_CONSTANT i32 70000
    %4:gprbank(s1) = G_ICMP intpred(slt), %0(s32), %3
    %5:gprbank(s32) = G_SELECT %4(s1), %1, %2
    $r1 = COPY %5(s32)
    RET implicit $r1
...
