# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=penumbra-unknown-none -run-pass=instruction-select -verify-machineinstrs %s -o - | FileCheck %s

# Selection of the add/sub-with-carry generic ops onto the hardware carry chain
# (ADD/ADC, SUB/SBC threading SR.C).  See selectAddSubCarry in
# PenumbraInstructionSelector.cpp.

--- |
  define void @uaddo_carry_out() { ret void }
  define void @uadde_fast() { ret void }
  define void @uadde_slow() { ret void }
  define void @usube_slow() { ret void }
...

# G_UADDO with a *used* carry-out: ADD sets SR.C, then the carry bit is read
# back into a GPR (R0 + R0 + C via ADC) — emitCarryToValue, add path.
---
name:            uaddo_carry_out
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $r1, $r2
    ; CHECK-LABEL: name: uaddo_carry_out
    ; CHECK: liveins: $r1, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr_allocatable = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr_allocatable = COPY $r2
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:gpr = ADD [[COPY]], [[COPY1]], implicit-def $sr
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gpr_allocatable = COPY $r0
    ; CHECK-NEXT: [[ADC:%[0-9]+]]:gpr = ADC [[COPY2]], $r0, implicit-def $sr, implicit $sr
    ; CHECK-NEXT: [[ANDi:%[0-9]+]]:gpr = ANDi [[ADC]], 1, implicit-def $sr
    ; CHECK-NEXT: $r1 = COPY [[ADD]]
    ; CHECK-NEXT: $r2 = COPY [[ANDi]]
    ; CHECK-NEXT: RET implicit $r1, implicit $r2
    %0:gprbank(s32) = COPY $r1
    %1:gprbank(s32) = COPY $r2
    %2:gprbank(s32), %3:gprbank(s1) = G_UADDO %0, %1
    %4:gprbank(s32) = G_ZEXT %3
    $r1 = COPY %2(s32)
    $r2 = COPY %4(s32)
    RET implicit $r1, implicit $r2
...

# Adjacent G_UADDO -> G_UADDE chain (the narrowed-i64 shape): the carry is
# already live in SR.C, so the consumer is a bare ADC with no carry-in fixup.
---
name:            uadde_fast
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $r1, $r2, $r3, $r4
    ; CHECK-LABEL: name: uadde_fast
    ; CHECK: liveins: $r1, $r2, $r3, $r4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr_allocatable = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr_allocatable = COPY $r2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gpr_allocatable = COPY $r3
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gpr_allocatable = COPY $r4
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:gpr = ADD [[COPY]], [[COPY2]], implicit-def $sr
    ; CHECK-NEXT: [[ADC:%[0-9]+]]:gpr = ADC [[COPY1]], [[COPY3]], implicit-def $sr, implicit $sr
    ; CHECK-NEXT: $r1 = COPY [[ADD]]
    ; CHECK-NEXT: $r2 = COPY [[ADC]]
    ; CHECK-NEXT: RET implicit $r1, implicit $r2
    %0:gprbank(s32) = COPY $r1
    %1:gprbank(s32) = COPY $r2
    %2:gprbank(s32) = COPY $r3
    %3:gprbank(s32) = COPY $r4
    %4:gprbank(s32), %5:gprbank(s1) = G_UADDO %0, %2
    %6:gprbank(s32), %7:gprbank(s1) = G_UADDE %1, %3, %5
    $r1 = COPY %4(s32)
    $r2 = COPY %6(s32)
    RET implicit $r1, implicit $r2
...

# G_UADDE whose carry-in is NOT a preceding carry op (here a plain value): the
# 0/1 value must be loaded into SR.C first.  Add family wants SR.C == bit, so
# CMPi v, 1 (SR.C = v >= 1) does it — emitSetCarryFromValue, add path.
---
name:            uadde_slow
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $r1, $r2, $r3
    ; CHECK-LABEL: name: uadde_slow
    ; CHECK: liveins: $r1, $r2, $r3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr_allocatable = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr_allocatable = COPY $r2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gpr_allocatable = COPY $r3
    ; CHECK-NEXT: CMPi [[COPY2]], 1, implicit-def $sr
    ; CHECK-NEXT: [[ADC:%[0-9]+]]:gpr = ADC [[COPY]], [[COPY1]], implicit-def $sr, implicit $sr
    ; CHECK-NEXT: $r1 = COPY [[ADC]]
    ; CHECK-NEXT: RET implicit $r1
    %0:gprbank(s32) = COPY $r1
    %1:gprbank(s32) = COPY $r2
    %2:gprbank(s32) = COPY $r3
    %3:gprbank(s1) = G_TRUNC %2
    %4:gprbank(s32), %5:gprbank(s1) = G_UADDE %0, %1, %3
    $r1 = COPY %4(s32)
    RET implicit $r1
...

# G_USUBE whose carry-in is a plain value: SBC subtracts ~C, so the sub family
# wants SR.C == NOT bit.  CMP R0, v (SR.C = 0 >= v) gives that — the sub path of
# emitSetCarryFromValue.
---
name:            usube_slow
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $r1, $r2, $r3
    ; CHECK-LABEL: name: usube_slow
    ; CHECK: liveins: $r1, $r2, $r3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr_allocatable = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr_allocatable = COPY $r2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gpr_allocatable = COPY $r3
    ; CHECK-NEXT: CMP $r0, [[COPY2]], implicit-def $sr
    ; CHECK-NEXT: [[SBC:%[0-9]+]]:gpr = SBC [[COPY]], [[COPY1]], implicit-def $sr, implicit $sr
    ; CHECK-NEXT: $r1 = COPY [[SBC]]
    ; CHECK-NEXT: RET implicit $r1
    %0:gprbank(s32) = COPY $r1
    %1:gprbank(s32) = COPY $r2
    %2:gprbank(s32) = COPY $r3
    %3:gprbank(s1) = G_TRUNC %2
    %4:gprbank(s32), %5:gprbank(s1) = G_USUBE %0, %1, %3
    $r1 = COPY %4(s32)
    RET implicit $r1
...
