# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=penumbra-unknown-none -run-pass=instruction-select -verify-machineinstrs %s -o - | FileCheck %s

# Tests that the AddrRegImm ComplexPattern folds constant GEP offsets and
# frame indices into the offset slot of LDW/STW/LDH/LDB memory instructions.

--- |
  define i32 @load_bare_reg(ptr %p) { ret i32 0 }
  define i32 @load_ptr_add_const(ptr %p) { ret i32 0 }
  define i32 @load_ptr_add_large(ptr %p) { ret i32 0 }

  define i32 @load_frame_index() {
    %x = alloca i32
    ret i32 0
  }

  define i32 @load_frame_index_offset() {
    %x = alloca [4 x i32]
    ret i32 0
  }

  define void @store_ptr_add_const(ptr %p, i32 %v) { ret void }
...

# Bare register base: fallback case emits LDW Rb, 0.
---
name:            load_bare_reg
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $r1
    ; CHECK-LABEL: name: load_bare_reg
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr_allocatable = COPY $r1
    ; CHECK-NEXT: [[LDW:%[0-9]+]]:gpr = LDW [[COPY]], 0 :: (load (s32))
    ; CHECK-NEXT: $r1 = COPY [[LDW]]
    ; CHECK-NEXT: RET implicit $r1
    %0:gprbank(p0) = COPY $r1
    %1:gprbank(s32) = G_LOAD %0(p0) :: (load (s32))
    $r1 = COPY %1(s32)
    RET implicit $r1
...

# G_PTR_ADD with small constant (fits simm16): folded as LDW base, 12.
---
name:            load_ptr_add_const
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $r1
    ; CHECK-LABEL: name: load_ptr_add_const
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr_allocatable = COPY $r1
    ; CHECK-NEXT: [[LDW:%[0-9]+]]:gpr = LDW [[COPY]], 12 :: (load (s32))
    ; CHECK-NEXT: $r1 = COPY [[LDW]]
    ; CHECK-NEXT: RET implicit $r1
    %0:gprbank(p0) = COPY $r1
    %1:gprbank(s32) = G_CONSTANT i32 12
    %2:gprbank(p0) = G_PTR_ADD %0, %1(s32)
    %3:gprbank(s32) = G_LOAD %2(p0) :: (load (s32))
    $r1 = COPY %3(s32)
    RET implicit $r1
...

# G_PTR_ADD with out-of-range constant (> simm16): fallback — constant
# gets materialized as ADDi, then LDW reg, 0.
---
name:            load_ptr_add_large
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $r1
    ; CHECK-LABEL: name: load_ptr_add_large
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr_allocatable = COPY $r1
    ; CHECK-NEXT: [[ADDi:%[0-9]+]]:gpr = ADDi [[COPY]], 40000, implicit-def dead $sr
    ; CHECK-NEXT: [[LDW:%[0-9]+]]:gpr = LDW [[ADDi]], 0 :: (load (s32))
    ; CHECK-NEXT: $r1 = COPY [[LDW]]
    ; CHECK-NEXT: RET implicit $r1
    %0:gprbank(p0) = COPY $r1
    %1:gprbank(s32) = G_CONSTANT i32 40000
    %2:gprbank(p0) = G_PTR_ADD %0, %1(s32)
    %3:gprbank(s32) = G_LOAD %2(p0) :: (load (s32))
    $r1 = COPY %3(s32)
    RET implicit $r1
...

# Bare G_FRAME_INDEX base: folded as LDW FI, 0 — eliminateFrameIndex
# will later rewrite FI to R14 + stack offset.
---
name:            load_frame_index
legalized:       true
regBankSelected: true
tracksRegLiveness: true
stack:
  - { id: 0, name: x, type: default, offset: 0, size: 4, alignment: 4 }
body: |
  bb.0:
    ; CHECK-LABEL: name: load_frame_index
    ; CHECK: [[LDW:%[0-9]+]]:gpr = LDW %stack.0.x, 0
    ; CHECK-NEXT: $r1 = COPY [[LDW]]
    ; CHECK-NEXT: RET implicit $r1
    %0:gprbank(p0) = G_FRAME_INDEX %stack.0.x
    %1:gprbank(s32) = G_LOAD %0(p0) :: (load (s32))
    $r1 = COPY %1(s32)
    RET implicit $r1
...

# G_PTR_ADD FI + constant: folded as LDW FI, offset — the FI operand
# carries the stack slot identity, the imm carries the GEP offset.
---
name:            load_frame_index_offset
legalized:       true
regBankSelected: true
tracksRegLiveness: true
stack:
  - { id: 0, name: x, type: default, offset: 0, size: 16, alignment: 4 }
body: |
  bb.0:
    ; CHECK-LABEL: name: load_frame_index_offset
    ; CHECK: [[LDW:%[0-9]+]]:gpr = LDW %stack.0.x, 8 :: (load (s32))
    ; CHECK-NEXT: $r1 = COPY [[LDW]]
    ; CHECK-NEXT: RET implicit $r1
    %0:gprbank(p0) = G_FRAME_INDEX %stack.0.x
    %1:gprbank(s32) = G_CONSTANT i32 8
    %2:gprbank(p0) = G_PTR_ADD %0, %1(s32)
    %3:gprbank(s32) = G_LOAD %2(p0) :: (load (s32))
    $r1 = COPY %3(s32)
    RET implicit $r1
...

# Store side of the same fold — STW rather than LDW.
---
name:            store_ptr_add_const
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $r1, $r2
    ; CHECK-LABEL: name: store_ptr_add_const
    ; CHECK: liveins: $r1, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr_allocatable = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr_allocatable = COPY $r2
    ; CHECK-NEXT: STW [[COPY1]], [[COPY]], 24 :: (store (s32))
    ; CHECK-NEXT: RET
    %0:gprbank(p0) = COPY $r1
    %1:gprbank(s32) = COPY $r2
    %2:gprbank(s32) = G_CONSTANT i32 24
    %3:gprbank(p0) = G_PTR_ADD %0, %2(s32)
    G_STORE %1(s32), %3(p0) :: (store (s32))
    RET
...
