#!/usr/bin/env python3
"""Fix Yosys $readmemh bug: remove zero-fill loops that precede $readmemh.

Yosys has a bug where a for-loop zero-fill in an initial block
overrides a subsequent $readmemh, causing the memory to be all zeros.
This script strips the zero-fill loops so $readmemh works correctly.

The pattern we remove (generated by sv2v from SystemVerilog):
    initial begin
        begin : sv2v_autoblock_N
            reg signed [31:0] i;
            for (i = 0; i < N; i = i + 1)
                array[i] = W'b000...0;
        end
        $readmemh("file.hex", array);
    end

becomes:
    initial begin
        $readmemh("file.hex", array);
    end

Usage: python3 inline_hex.py input.v output.v
"""

import re
import sys

def strip_zerofill_before_readmemh(content):
    """Remove sv2v zero-fill blocks that precede $readmemh calls."""
    # Pattern: named begin block with for-loop zeroing, followed by $readmemh
    # The sv2v_autoblock contains: reg declaration, for loop zeroing the array
    pattern = (
        r'begin\s*:\s*sv2v_autoblock_\d+\s*'     # begin : sv2v_autoblock_N
        r'reg\s+signed\s+\[31:0\]\s+\w+;\s*'     # reg signed [31:0] i;
        r'for\s*\([^)]+\)\s*'                      # for (i = 0; i < N; i = i + 1)
        r'\w+\[\w+\]\s*=\s*\d+\'b0+;\s*'          # array[i] = N'b000...0;
        r'end\s*'                                   # end
    )
    result = re.sub(pattern, '', content)

    count = content.count('sv2v_autoblock') - result.count('sv2v_autoblock')
    if count > 0:
        print(f"  stripped {count} zero-fill loop(s) before $readmemh", file=sys.stderr)

    return result

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} input.v output.v", file=sys.stderr)
        sys.exit(1)

    with open(sys.argv[1]) as f:
        content = f.read()

    content = strip_zerofill_before_readmemh(content)

    with open(sys.argv[2], 'w') as f:
        f.write(content)
