#!/usr/bin/env python3
"""text2cells — plain-text screen image to display cell data.

Reads a text file describing an 80x30 character screen and emits it
in one of two forms:

  --format hex  the $readmemh image for video_cell_ram — 4096 lines
                of one 4-hex-digit {attr, glyph} cell, row-major.
                Used by the CPU-free bring-up probe, which has no
                bus master to draw a screen for it.
  --format c    a C header of one string per row, for firmware that
                draws the screen itself.

Input lines shorter than the grid pad with spaces; the attribute is
uniform (--attr, default 0x07 = light grey on black — the contract's
default). The file is UTF-8, the encoding every editor writes; each
character is transcoded to its CP437 glyph index, so box drawing,
shades, and blocks all map to the font the hardware carries. A
character with no CP437 equivalent is an error naming the offender.

Usage: text2cells.py [--attr HH] [--format hex|c] <screen.txt> <out>
"""

import argparse
import sys

COLS, ROWS, DEPTH = 80, 30, 4096


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--attr", default="07",
                    help="attribute byte for every cell (hex, default 07)")
    ap.add_argument("--format", choices=("hex", "c"), default="hex",
                    help="output form: $readmemh image or C header")
    ap.add_argument("screen")
    ap.add_argument("output")
    args = ap.parse_args()

    attr = int(args.attr, 16)
    if not 0 <= attr <= 0xFF:
        sys.exit(f"error: attribute {args.attr} is not a byte")

    with open(args.screen, encoding="utf-8") as f:
        lines = f.read().split("\n")
    while lines and lines[-1] == "":
        lines.pop()
    lines = [l.rstrip("\r") for l in lines]

    if len(lines) > ROWS:
        sys.exit(f"error: {args.screen}: {len(lines)} lines exceed the "
                 f"{ROWS}-row grid")

    rows = []
    for n, l in enumerate(lines):
        try:
            raw = l.encode("cp437")
        except UnicodeEncodeError as e:
            sys.exit(f"error: {args.screen}:{n + 1}: {e.object[e.start]!r} "
                     "has no CP437 glyph")
        if len(raw) > COLS:
            sys.exit(f"error: {args.screen}:{n + 1}: {len(raw)} columns "
                     f"exceed the {COLS}-column grid")
        rows.append(raw)

    if args.format == "c":
        with open(args.output, "w") as f:
            f.write(f"/* Generated by text2cells.py from {args.screen}. */\n\n")
            f.write(f"#define SPLASH_ROWS {len(rows)}\n")
            f.write(f"#define SPLASH_ATTR 0x{attr:02x}\n\n")
            f.write("static const char *const splash_art[SPLASH_ROWS] = {\n")
            for raw in rows:
                # Octal escapes throughout: three digits always
                # terminate, so no glyph can extend into the next
                # character the way a short \x escape would.
                body = "".join(
                    chr(b) if 0x20 <= b < 0x7F and b not in b'"\\' else f"\\{b:03o}"
                    for b in raw)
                f.write(f'\t"{body}",\n')
            f.write("};\n")
        return

    blank = (attr << 8) | 0x20
    cells = [blank] * DEPTH
    for r, raw in enumerate(rows):
        for c, glyph in enumerate(raw):
            cells[r * COLS + c] = (attr << 8) | glyph

    with open(args.output, "w") as f:
        f.write(f"// text2cells: {args.screen}, attr {attr:02x}\n")
        for cell in cells:
            f.write(f"{cell:04x}\n")


if __name__ == "__main__":
    main()
